### ISSUE TITLE
Add node v16 globals

### ISSUE THREAD

**Issue by devinivy** [hapijs/lab#1003]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*:  v16
* *module version*: v24
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone, on hapi v16
* *any other relevant information*: This follows from reports via citgm: https://github.com/nodejs/citgm/issues/852#issuecomment-814529996

#### What problem are you trying to solve?

We would like lab test suites to pass on node v16 without extra configuration.  Currently they fail because node v16 has added some new global variables: `btoa`, `atob`, and `performance`.

#### Do you have a new or modified API suggestion to solve the problem?

We should add `btoa`, `atob`, and `performance` to lab's list of allowed globals in preparation for node v16.

**Comment by kanongil** [comment]
Node 16 has been released, and this is causing my tests to fail on it.

**Comment by devinivy** [comment]
There is now a PR open for this in #1004 and as a temporary workaround you can configure lab to ignore these globals with `-I 'atob,btoa,performance'`.
