### ISSUE TITLE
How to get `--seed` using lab API?

### ISSUE THREAD

**Issue by gerardolima** [hapijs/lab#1010]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v14.16.0
* *module version*: 24.1.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): AWS Lambda
* *any other relevant information*:

#### How can we help?

I use [Chance](https://www.npmjs.com/package/chance) to inject some randomness into my unit tests and use `shuffle: true` on `.labrc.js` to randomise the order of the tests. I would like to know whether there is a way to get the `seed` value from `lab`-cli, in order to have repeatable tests:

```sh
$ lab --shuffle --seed 123456
````
```ts
import { script } from '@hapi/lab'
export const lab = script()
console.log(lab.seed) // 123456
```

**Comment by devinivy** [comment]
The best-supported way to get the seed is through lab's reporter API.  You can see an example of how the seed can be referenced within a reporter in the console reporter, which currently outputs the seed to console: https://github.com/hapijs/lab/blob/faae6f10aa8469f09f6d5ef6ef6d8a28bd8d70e3/lib/reporters/console.js#L275-L277
