### ISSUE TITLE
DOMException will be a global in Node.js 17+

### ISSUE THREAD

**Issue by targos** [hapijs/lab#1019]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v17.0.0-pre
* *module version with issue*: latest
* *last module version without issue*: none
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): `@hapi/shot`
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

Run tests of `@hapi/shot` with prerelease of Node.js 17

#### What was the result you got?

 The following leaks were detected:DOMException

https://ci.nodejs.org/job/citgm-smoker/nodes=ubuntu1804-64/2751/testReport/junit/(root)/citgm/_hapi_shot_v5_0_5/

#### What result did you expect?

No leak detected

**Comment by Nargonath** [comment]
Alright, thanks @targos for the heads-up.

**Comment by targos** [comment]
https://github.com/nodejs/node/pull/39759 is about to land, so there will also probably be `structuredClone`
