### ISSUE TITLE
Update linter to work with ESLint 8

### ISSUE THREAD

**Issue by cjihrig** [hapijs/lab#1021]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): not yet
* *is this issue affecting a production system?* (yes/no): not yet

#### Context

* *node version*:  v16.8.0
* *module version*:  v24.3.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### What problem are you trying to solve?

ESLint 8 is currently in beta. It would be good to start migrating to ESLint 8 before it goes stable because there are some updates to be made in Lab. Lab uses ESLint's `CLIEngine` class, which has been [removed in ESLint 8](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#the-cliengine-class-has-been-removed).

#### Do you have a new or modified API suggestion to solve the problem?

Update Lab's ESLint according to the [migration guide](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0).

**Comment by Nargonath** [comment]
I looked a bit into it when I migrated `lab` to our new ESLint plugin but this might imply big changes hence I didn't handle it in my previous PR. We go from a synchronous API for some functions to an async one i.e [`getConfigForFile`](https://eslint.org/docs/developer-guide/nodejs-api#clienginegetconfigforfile) vs [`calculateConfigForFile`](https://eslint.org/docs/developer-guide/nodejs-api#-eslintcalculateconfigforfilefilepath).

**Comment by cjihrig** [comment]
@geek does https://github.com/cjihrig/belly-button/commit/4a151b3b5886288b870d012558639c12bce18818 make any difference? I was able to get ESLint 8 running.

**Comment by cjihrig** [comment]
https://github.com/babel/babel/pull/13782 has landed and apparently released: https://babeljs.io/blog/2021/10/29/7.16.0

**Comment by geek** [comment]
@cjihrig thanks, yeah I started incorporating it last weekend, but ran into some issues. Hoping to have a PR next week.

**Comment by geek** [comment]
I ran into an issue with https://github.com/nodejs/node/blob/873119385f4b59d9a0df75284790203102054ea1/lib/internal/modules/cjs/loader.js#L975 assuming a sync function, which we assign at https://github.com/hapijs/lab/blob/e7b0550d286574e1f817c87c2947cd389f359ffc/lib/modules/coverage.js#L119

With the async change in eslint for `calculateConfigForFile` this will require `instrument` to become async as well as this "extensions" function. Fortunately, the `calculateConfigForFile` doesn't need to be async, so I submitted a PR for that change here: https://github.com/eslint/eslint/pull/15275 We will see what the eslint folks think of the change.

**Comment by Nargonath** [comment]
Good catch @geek. I didn't check whether it was purposefully `async` or not. I assumed it was.

**Comment by geek** [comment]
@cjihrig I don't see a way to make this work. If I try to load the cli engine directly it throws ERR_PACKAGE_PATH_NOT_EXPORTED due to not being part of the official eslint export.

**Comment by devinivy** [comment]
I took a look at this, and I agree it's not pretty!  My recommendation is to call [`calculateConfigForFile()`](https://eslint.org/docs/developer-guide/nodejs-api#-eslintcalculateconfigforfilefilepath) once for `Path.join(coveragePath, 'x')` (the file doesn't actually need to exist), then use the resulting `parserConfig` for all file coverage.  This is a breaking change and a limitation, but I think it's pretty reasonable/workable to only support one parser config for coverage purposes.

**Comment by devinivy** [comment]
There is a PR implementing the suggestion in my previous comment here: https://github.com/hapijs/lab/pull/1035
