### ISSUE TITLE
How to run individual tests: updated docs

### ISSUE THREAD

**Issue by santicalvo** [hapijs/lab#1030]
This is just a new version of this closed ticket: https://github.com/hapijs/lab/issues/114.

I'd like to see the documentation on how to run individual tests, also I would like to use a debugger to do it...

The answer there links to a link that redirects to https://github.com/hapijs/lab#command-line. 

Where can we find it documented?

Thank you.

**Comment by devinivy** [comment]
You can find the documentation on hapi.dev here: https://hapi.dev/module/lab/api#command-line. You'll want to check-out docs for the `-i` flag 👍
