### ISSUE TITLE
Uncovered lines in test report

### ISSUE THREAD

**Issue by rsc1975** [hapijs/lab#1054]
#### Support plan

* *is this issue currently blocking your project?* no:
* *is this issue affecting a production system?* no:

#### Context

* *node version*:  v14.19.1
* *module version*:   "@hapi/hapi": "^20.2.2", "@hapi/lab": "^25.0.1"
* *environment*: node 
* *used with*: hapi + lab + code
* *any other relevant information*: Code in typescript

#### How can we help?

I'm creating a mock server with hapi, It's my first app with hapi, so maybe I'm missing something. With my first test suite I got the following output:
![image](https://user-images.githubusercontent.com/3704272/176708839-ddc5cdaf-5000-4bfa-9f4b-32815b3887d8.png)

As you can see there are several lines that according to lab report are not covered by test cases, this lines are the following:
![image](https://user-images.githubusercontent.com/3704272/176710308-9515908f-19c4-47df-a0cc-ec73dc3c865b.png)
![image](https://user-images.githubusercontent.com/3704272/176710659-e1a73d6b-4ee1-4a88-b4ce-8e30cf124b4d.png)

About the first 3 lines, How can I test them?, I mean, How can I  inject some custom values for env vars for an specific test case ? The module is imported just once time in my test file, right? And about the last one, I don't understand the report comment, actually is not true, that condition is only `true` in some cases not all, Could it be a bug?

**Comment by rsc1975** [comment]
I've fixed both cases, I saw that the lines with conditions where one of the conditions are always `true` or `false` in all test cases are marked as "no covered", even when the entire condition can change and all executions branches are tested, for instance:

```
  if (2 === 2 && objects.length === 2) {
      console.log("I'm in");
  }
```

I suppose that this is the expected behavior, so I'll close this issue, If I didn't understand correctly, please, let me know.

**Comment by devinivy** [comment]
Yep, I think that's right!  Lab provides branch-level coverage, which is more granular than ensuring each line is hit.
