### ISSUE TITLE
Easy way to use with Coffeescript and other compiled languages

### ISSUE THREAD

**Issue by KyleAMathews** [hapijs/lab#106]
Jest's pattern for supporting other languages is nice: http://facebook.github.io/jest/docs/tutorial-coffeescript.html#content

**Comment by nickux** [comment]
Just to add my $.02, I'd really like this too. I've been hacking with require('coffee-script/register') for the past hour trying to get this to work... no luck.

Basically, unless you precompile all of your CS into JS (which I don't - I let it compile at runtime and cache on the server), you can't use Lab to test.

**Comment by starhawkhkk** [comment]
It'd be great to be able to serve js files to frontend that are compiled on the fly.

**Comment by starhawkhkk** [comment]
Don't you guys think Hapi should marry Harp?

**Comment by KyleAMathews** [comment]
Transpiling is supported now. Search on the README for `coffee`

**Comment by geek** [comment]
@nickux and @linjunpop as @KyleAMathews points out, lab now supports CoffeeScript, JSX, and others :)

**Comment by linjunpop** [comment]
:fireworks:

**Comment by rodoabad** [comment]
@geek What about ES6? Do we still need to use `require('babel-core/register')`?

**Comment by geek** [comment]
@rodoabad if you are using ES6 features you will be fine without the extra require... lab now works only with node v4 and newer.

**Comment by rodoabad** [comment]
@geek I would still need to transpile my ES6/7 code with Babel before being able to run it especially if I am using `export` or `import`.

**Comment by geek** [comment]
@rodoabad right, any language feature thats not supported by the version of node you are running requires transpiling.
