### ISSUE TITLE
Authentication Testing

### ISSUE THREAD

**Issue by kidtronnix** [hapijs/lab#173]
Hi,

I am trying to use Lab to test an application I wrote using Hapi, https://github.com/smaxwellstewart/hapi-dash.

I would like to test my authentication by:
1. Doing an injection of an auth protected route WITHOUT a session cookie and making sure I am redirected to '/login'.
2. Doing an injection of '/login' to make sure the login works. At this point collect a cookie (could i collect it using yar?).
3. Doing an injection of an auth protected route WITH a session cookie and making sure I am allowed to view route (status code 200).

Is there an easy way to do this using Lab? I think I could do the first test but number 2 and 3 are a little trickier.

Generally, is there full documentation for this utility? Would love to be able to review some docs.

Simon

**Comment by vinkaga** [comment]
I created [hapi-session-inject](https://github.com/vinkaga/hapi-session-inject) to make session slightly more convenient in tests.
