### ISSUE TITLE
Stop Tests On First Failure

### ISSUE THREAD

**Issue by tsilvia** [hapijs/lab#214]
The idea would be to add a command line flag to lab that would cause the set of test cases to stop on first failure and show the output of that failed test instead of having to wait for all tests to complete and then see the output.

You could also make it an option that it shows the reason for the test failure in line with the verbose output so you can see the reason for the failure as the tests continue to run so you can determine if tests are failing due to the same issue. Again without waiting for the entire set of tests to complete.

**Comment by bkendall** [comment]
:+1: would be nice to have large test suites stop quickly on an early failure

**Comment by anandkumarpatel** [comment]
:+1:  would reduce our test time drastically

**Comment by Danlock** [comment]
Can a --bail option be added (such as the one in mocha) ?

**Comment by Marsup** [comment]
The label `help wanted` means anyone can go ahead and make a PR, if you need it you know what to do.

**Comment by goddyZhao** [comment]
+1, this is really helpful especially for the tests which are with heavy tasks

**Comment by TangMonk** [comment]
+1
