### ISSUE TITLE
Set expected number of assertions

### ISSUE THREAD

**Issue by Marsup** [hapijs/lab#257]
Related to #115.

Now that we can count assertions, it would be very useful to assert all the expected assertions ran.

**Comment by aymericbeaumet** [comment]
What's the current status about this? What about https://github.com/Marsup/lab/commit/a1b1b3f?

**Comment by Marsup** [comment]
My patch was working when lab was explicitly using chai, it would need an update to work with various assertion framework now. I'd also be curious to explore a solution based on continuation-local-storage.

**Comment by aymericbeaumet** [comment]
Hum yeah, not sure how to tackle the assertion-framework-agnostic issue here. Maybe something like this: `var expect = Lab.assert(require('chai')).expect;`. But that would imply to explicitly support a list of assertion libraries.

How would you would leverage continuation-local-storage?

**Comment by Marsup** [comment]
There's already the -a switch, we could use that and add hooks when we know the library.
CLS could be used as a context to store assertion counts to avoid using the this.

**Comment by aymericbeaumet** [comment]
Yeah I suppose we could support the main libraries at first. `-a` is fine, but we should also expose an API for people loading their assertion library manually.
CLS > Fine by me. In that case we would need a way to generate unique ids for each test (unless that's already done by lab).

**Comment by Marsup** [comment]
Unless I misunderstood CLS, it doesn't have to be unique. I'd pick a single one here.

**Comment by aymericbeaumet** [comment]
> Unless I misunderstood CLS

The misunderstanding was on my side. A single id is enough.

**Comment by Marsup** [comment]
@geek time to take a decision, should anyone take action or shall we close the issue ?

**Comment by devinivy** [comment]
Just adding that I would use this feature if the API for it were simple enough.

**Comment by geek** [comment]
@Marsup I like the idea and will gladly merge it in :)

**Comment by Marsup** [comment]
My vision of the API is :
```js
it('works', { plan: 4 }, (done) => {
  4x expect(...)
});
```
So no `this` if possible.

I'm assuming CLS but maybe the future is zones.js or async-listener, it's still not clear to me, maybe someone followed that better than me ?
Also only libraries using that would work of course.

**Comment by aymericbeaumet** [comment]
:+1:

Note that we might not require a `done` parameter if the user specifies `options.plan`.

**Comment by Marsup** [comment]
I'd keep it anyway for consistency.

**Comment by geek** [comment]
Looks good to me.  I am fine with naming it `plan`, might consider naming it `expect` as instead.

```
it('works', { expect: 4 }, (done) => {
  4x expect(...)
});
```

**Comment by devinivy** [comment]
I like `plan`, since that's possibly more familiar due to popularization in `tap`.  Either way looks good, though.

**Comment by geek** [comment]
@devinivy sounds good, I know thats what tape names it... so should be easier for people who are familiar with that style.
