### ISSUE TITLE
Failed Assertion Causing Timeout

### ISSUE THREAD

**Issue by 58bits** [hapijs/lab#273]
I'm having a problem with some tests I'm writing using Lab. When an assertion/expect fails, I get errors reported against the 'previous' test - 

Test script errors:

```
Multiple callbacks or thrown errors received in test: Cache first test (error)
      at Domain.emit (events.js:95:17)
      at process._fatalException (node.js:249:27)

There were 1 test script error(s).

Failed tests:

  2) Cache second test:

      Timed out (2000ms)
```

Here's the test fixture.

```javascript
'use strict';

var Memcached = require('memcached');
var Cache;

var Code = require('code');   // assertion library
var Lab = require('lab');
var lab = exports.lab = Lab.script();

lab.experiment('Cache', function() {

  lab.before(function (done) {
    Cache = new Memcached('localhost:11211', {retries:10,retry:10000});
    done();
  });

  lab.after(function (done) {
    Cache.end();
    done();
  });

  lab.test('first test', function(done){
    var key = 'TEST-ARRAY';
    var i = [1,2,3,4];
    Cache.set(key, i, 1000, function (err) {
      if (err) {
        done(err);
      } else {
        Cache.get(key, function (err, data) {
          Code.expect(data).to.be.an.array();
          Code.expect(data.length).to.equal(4);
          done();
        });
      }
    });
  });

  lab.test('second test', function(done) {
    var key = 'TEST-STRING';
    var i = "hello";
    Cache.set(key, i, 1000, function (err) {
      if (err) {
        done(err);
      } else {
        Cache.get(key, function (err, data) {
          Code.expect(data).to.be.a.string();
          Code.expect(data).to.equal('boo');
          done();
        });
      }
    });
  });
});
```

I've forced the expectation to fail in the second test with `Code.expect(data).to.equal('boo');`, and this generates the error above. I suspect it's because `done()` is never called, and that the Cache client is handling the error raised by Code.expect.

I can solve this by wrapping the Code.expect statements in a try,catch block as follows:

```javascript
lab.test('second test', function(done) {
    var key = 'TEST-STRING';
    var i = "hello";
    Cache.set(key, i, 1000, function (err) {
      if (err) {
        done(err);
      } else {
        Cache.get(key, function (err, data) {
          try {
            Code.expect(data).to.be.a.string();
            Code.expect(data).to.equal('boo');
            done();
          } catch(e) {
            done(e);
          }
        });
      }
    });
  });
```

I guess my question is whether this is expected behavior not?

**Comment by KeKs0r** [comment]
Facing the same issue. I am wondering how you solved it.

**Comment by 58bits** [comment]
Hi @KeKs0r  - unfortunately I haven't been able to get back to this, and have left this particular set of tests as is, with try/catch blocks around `Code.expect` statements.

**Comment by rusticode** [comment]
Sadly, got  the same issue. Not using caching. 
Any chance someone resolved that issue?

**Comment by geek** [comment]
@58bits is this still an issue for you?  I see that @rusticode had been calling done more than once.  I am closing, but feel free to reopen if that doesn't fix the issue for you @58bits.

**Comment by salimkapadia** [comment]
@geek I'm having the same issue
`vagrant@vagrant-ubuntu-trusty-64: lab test/controllers/authController.js

Failed tests:
  1) method:post, url:/auth/login  Login with an invalid network:
      Timed out (2000ms) - method:post, url:/auth/login  Login with an invalid network

test/controllers/authController.js

var Lab = require("lab");
var Code = require('code');   // assertion library
var server = require("../../");
var models = require('../../database');

// Test shortcuts
var lab = exports.lab = Lab.script();

lab.experiment("method:post, url:/auth/login ", function() {
		lab.test("Login with an invalid network", function(done) {
		    var options = {
		        method: "post",
						url: "/auth/login",
						payload:
		        {
	            network: "yahoo",
	            email: "testemail@yahoo.com",
	            password: "testpassword"
		        }
		    };
		    server.inject(options, function(response) {
					console.log('response:');
					console.log(response);
		        var result = response.result;
		        Code.expect(response.statusCode).to.equal(4100);
						done();
		    });
		});
});

//controllers/authController.js
var models = require('../database');
var async = require('async');
var config = require('../config/config');
var	Boom = require('boom');
var	Joi = require('joi');

// private internal functions
var internals = {};

exports.login = {
	tags: ['auth', 'login'],
	description: "App login endpoint with cookie session init",
	auth: {
		mode: 'try',
		strategy: 'session'
	},
	plugins: {
		'hapi-auth-cookie': {
			redirectTo: false
		}
	},
	validate: {
		payload: {
           network: Joi.string().valid(config.login.validNetworks).required(),
            email: Joi.string().email().max(60),
            password: Joi.string().min(6).max(60)
        }
	},
handler: function (request, reply) {
		if (request.pre.user){
			return reply.redirect('/');
		}else{
			return reply(Boom.badRequest('Please register.'));
		}
};

`

**Comment by Marsup** [comment]
Might be because you're not even trying to catch the error of the promise in pre.

**Comment by geek** [comment]
@salimkapadia are you all using hapi for boomrat?  If so, fee free to add your company name to http://hapijs.com/community

**Comment by salimkapadia** [comment]
@Marsup I've updated the code block and removed all pre functions. I am still getting the same error. 
@geek I've moved on from boomrat and using hapi for a personal project

**Comment by Marsup** [comment]
Do you at least get any logs from your console.log ? It seems like you're not even hitting the handler.

**Comment by salimkapadia** [comment]
@Marsup nothing in the log. It's not even hitting the handler. Time to put try catch in the above require statements and see if there is an issue.

**Comment by Marsup** [comment]
Do you have any hooks on the request lifecycle ?

**Comment by salimkapadia** [comment]
@Marsup Below is my main server.js file for my app

```
/**
 * Dependencies.
 */
var Hapi        = require('happy')
var config      = require('./config/config');
var routes      = require('./routes');

var server = new Hapi.Server(Number(config.api.port));;
server.pack.register(config.hapi.plugins, function(err) {
	    if (err) throw err;

	    // Configure the plugins that are now attached to the server.
	    for (var index=0; index < config.hapi.auth.strategy.length; index++){
				server.auth.strategy(
					config.hapi.auth.strategy[index].name,
					config.hapi.auth.strategy[index].scheme,
					config.hapi.auth.strategy[index].options
				);
	    }

	    // Configure database connection
		var dbHandler = require('./database');
		dbHandler.init(config.database);

	    // Add configured routes to the server routes
		for (var tmp in routes){
		    server.route(routes[tmp]);
		};
});

// If the script is being required as a module by another script, don’t start the server.
if (!module.parent)
{
	server.start(function() {
        console.log("Hapi server started @ " + server.info.ui);
    });
}

// Make the server available as the top-level export of this module.
module.exports = server;
```

**Comment by Marsup** [comment]
Wow, that's some VERY old hapi you got there, can't remember last time I've seen pack. Also, what the hell is `happy` ?

**Comment by salimkapadia** [comment]
@Marsup sorry, stupid autocorrect changed it from hapi to happy. This was an older project that I left incomplete, that i'm finally wrapping up.

**Comment by Marsup** [comment]
You should upgrade, we're not supporting those old versions and we worked a lot on domains error catching since then.

**Comment by salimkapadia** [comment]
@Marsup I found the issue. The bcrypt module was not installed and the error was being caught by promises but wasn't being thrown. I've updated my code and now I'm getting a different error.  I'll start a new issue.
