### ISSUE TITLE
Make linter pluggable? (PR offer)

### ISSUE THREAD

**Issue by smikes** [hapijs/lab#282]
Hi! 

I just tried out lab and I'm really loving it, but the standard here is to use `jslint` for linting.  I'd be happy to write the code necessary to make the choice of linter be a pluggable option for `lab`.  

Does that sound useful? Is there anything I should be aware of, when writing this patch?  (Beyond the CONTRIBUTING and code style guidelines, which I have read..)

**Comment by tjmehta** [comment]
+1, how can I support alternative linters like [standard](https://github.com/feross/standard)

**Comment by cjihrig** [comment]
`standard` isn't a linter. It's a config file and some other tooling built on top of ESLint. You can specify the `standard` ESLint file through Lab. Or just install `standard` and add it to your `package.json` or whatever you use.

**Comment by geek** [comment]
@tjmehta add `.eslintrc` file to your project with the following contents:

```json
{
  "extends": "standard"
}
```

next you just need to install a couple of packages: `"eslint-config-standard", "eslint-plugin-standard"`

**Comment by tjmehta** [comment]
Looks like `eslint@^1.10.0` is currently bundled w/ `lab`, can `lab` use an external `eslint`?

Specific Problem: `eslint-config-standard` now requires `eslint@^2.0.0`. Am I stuck using an old eslint-config that is compatible with `eslint@1`?

**Comment by gergoerdosi** [comment]
I was about to send a pull request this week for eslint 2.0.0, because we need it too. If that change gets published with a new major version of lab, then our problem gets solved. Of course pluggable linters would be the best, but I assume it would require a lot more work.

**Comment by geek** [comment]
@tjmehta and @gergoerdosi we will update to eslint 2, I also want to make linters pluggable so that I can pull out jshint from being bundled.

**Comment by geek** [comment]
see https://github.com/hapijs/lab/pull/519
