### ISSUE TITLE
Use reporters from json, support multiple reports

### ISSUE THREAD

**Issue by lloydbenson** [hapijs/lab#285]
I have a use case where I want to get the nice native json output (which includes the code coverage) and from that json output, use the built-in reporters to put it in various formats.  The reason, I want to use the json file as the source, is because doing lab over and over for each format can potentially give different results (think unreliable downstream dependency) but is also obviously wasteful to re-test again.  It is nice having the 1 data source as the run result dataset, and then printing out whichever reporter you want (it would be nice to include console, html (coverage), junit, etc).  I don't care if i have to run each of these commands separately as they should be fast once the json file is complete.  I am open to really any ideas here.  The goal is to have 1 data set from a run, and use the internal reporters to format it based on that data set.

You could expose the functions so I could write another module or natively support this.  Let me know what you think and what the issues may be with doing this.

**Comment by hofan41** [comment]
Agree with this issue. Currently I need to upload an lcov file to coveralls but also display the test output results to console so I can have a record of the test report. This is important because if my only reporter is lcov and my test run fails, there is no output to the console with the test failure details.

**Comment by bkendall** [comment]
:+1: this is something that I've hit a couple times, and it would be amazing to have :)

**Comment by ndt75** [comment]
Would love to have support for multiple reports too!

**Comment by walling** [comment]
I just want to voice my support for this feature. My use case is to run the tests on a CI service and:

1. Generate JUnit XML that the CI service can analyse
2. Generate HTML coverage report to display in browser

I think it would be nice to support reporter/output pairs to get one report in one file, another report in another file and maybe a third in the console. Something along those lines.

**Comment by hofan41** [comment]
I've got basic functionality working right now and I have a question I would like to pose to the community: how should output file/formats be specified since there can be multiple reporters now? 

For example, you might want lcov to go to lcov.info file, while console is printed out to standard out. How should we tie the reporter to the output format?

**Comment by ndt75** [comment]
@hofan41 (Thanks for doing this, btw.)
For my use case, "--reporter console --reporter html --output test_results" would print the standard output on the terminal and the html-format output would be saved in test_results.html.

The logic would be something like:
- if console is specified, send the standard output the terminal.
- for each of the other reporters, save the output to the specified output file and automatically attaching the extension based on the reporter.
e.g. "--reporter console --reporter html --reporter json --output test_results" would do the standard console output and generate 2 files test_results.html and test_results.json

Hope that helps.

**Comment by hofan41** [comment]
@ndt75 thanks for discussing the potential usage scenario with me. As I understand it, lab currently makes no assumptions about the file extension of the output file, thus leading me to believe adding this type of logic may not be accepted. In addition, there are scenarios where I can envision someone wanting to save the console reporter type to a file as well, and not just print it to stdout. 

My proposal for output format would be this:

1. Normal/Original behavior if only one reporter is specified.
2. If there are multiple reporters specified, and no output specified, default to stdout.
3. If there are multiple reporters specified, and output is specified, there must be exactly the same number of output arguments as there are reporters, and the order in which they are entered are aligned. 

So for example:

```
lab -r html -r console -o test.html -o stdout
```

**Comment by ndt75** [comment]
@hofan41 
I think console should just be console. i.e. if someone wants to save console output of anything, that's what the > is for, right? 

As for specifying multiple files where the order of arguments has to match, that can get pretty tedious.
Not sure how lab feels about default extensions but personally prefer passing one single output argument. Or maybe we can an optional list in the output argument like "-o html=output.html,json=output.json". That way we don't have to keep track of the order of multiple "-o".

**Comment by hofan41** [comment]
@ndt75 an example why cli '>' may not be used is if lab is run with grunt via grunt-lab. In that case some folks may wish to save console output to a file but not be allowed to because of your proposed restriction.
