### ISSUE TITLE
self-run scripts don't generate output or respect CLI arguments

### ISSUE THREAD

**Issue by garthk** [hapijs/lab#288]
The README documentation for `schedule` suggests lab 3.x style self-run scripts should work. They do, in that they run the tests and exit with a status code. They don't, in that they don't generate output and ignore command line arguments including `--id`, `--verbose`, and `--reporter`. Both output and options worked in self-run scripts in lab 3.x. Is their omission undocumented, or unintended?

**Comment by hueniverse** [comment]
It was never meant to work in the first place. It must have been a side effect. As for what to do now, I'll leave it up to @geek.

**Comment by geek** [comment]
This does seem like a bug.  Most likely we should update the readme to be clearer.

**Comment by larsenjh** [comment]
The output works fine if you pass in { output: process.stdout } in the first argument of script(). You can basically mimic most of the cli switches with the main config object there.

**Comment by garthk** [comment]
Is there a one-liner to call lab's CLI parsing to get the options argument for script()? From my quick look, `lib/cli` hides it as `internals.options`.
