### ISSUE TITLE
False result on code coverage for assignment with logical OR

### ISSUE THREAD

**Issue by blundin** [hapijs/lab#289]
This line of code fails code coverage:
````
server.app.environment = process.env.NODE_ENV || 'development';
````
with this passing test in place:
````  
it('sets process.env.NODE_ENV correctly', function(done) {
  server.app.environment.should.equal('test');
  done();
});
````
If I change the line of code to:
````
server.app.environment = process.env.NODE_ENV;
````
the code coverage passes.

Using Hapi 8.0.0 and Lab 5.1.1

**Comment by Marsup** [comment]
Well yes, you tested the 1st part of the operator, not the 2nd, so it's not covered. Why do you think it's a bug ?

**Comment by geek** [comment]
@blundin if you use the `html` reporter it will give you a better overview of what part is missing coverage.

**Comment by divramod** [comment]
@Marsup @geek

you have some recommendation on how to cover both cases (process.env.??? is set [1] and  process.env.??? is not set [2])

how should the two tests look like?

should i delete process.env.??? in one testfile and reset it after done()?

**Comment by geek** [comment]
@divramod I would do as you suggest and delete the property in one test and set it in another
