### ISSUE TITLE
coverage line chunks returns false string rather than false boolean

### ISSUE THREAD

**Issue by lloydbenson** [hapijs/lab#292]
Here is an example when looking at the json output:

                    "74": {
                        "source": "   if (pail.scm && pail.scm.branch !== payload.scm.branch) {",
                        "chunks": [
                            {
                                "source": "   if ("
                            },
                            {
                                "source": "pail.scm",
                                "miss": "false"
                            },
                            {
                                "source": " && "
                            },
                            {
                                "source": "pail.scm.branch !== payload.scm.branch",
                                "miss": "never"
                            },
                            {
                                "source": ") {"
                            }
                        ],

Notice that the miss is "false" rather than just false.  I am writing a utllity that checks to see if this is a miss or not but since its string the check fails.  I would think it should be consistent with the other miss output which is just straight boolean false.

**Comment by geek** [comment]
We also want to track if the code line will never be covered, meaning it can be deleted.

**Comment by lloydbenson** [comment]
The reason this came up for me, is I am parsing out the json response.  I am using handlebars, which does pretty primitive if checks (if you want to avoid doing helpers).  In order to check which chuck of the line is failing I was checking to see what the miss was.  In this case if (misses) is matched because its the string 'false' rather than just regular boolean false.  It still seems like you'd want this as a boolean false to be consistent with the rest of the application.  

It sounds like the never is there to check to see if it is ever possible to even hit that code.  In my case, I am a little dubious that isn't not possible to hit this part of the code.  It is a case where i'm checking to see if a prev vs current value changed.  I haven't covered this in my test case yet, but I certainly think it will be possible to hit it.  If you think this is what it really does I can try to get a more simple use case to prove that out.  Let me know if that is the case or you need more explanation.
