### ISSUE TITLE
More details from a domain exception

### ISSUE THREAD

**Issue by jedireza** [hapijs/lab#294]
Recently I was getting an error:

```
Multiple callbacks or thrown errors received in test: ...
      at Domain.emit (events.js:95:17)
      at process._fatalException (node.js:249:27)
```

Which proved tricky to track down. I eventually opened up the local `./node_modules/lab/lib/runner.js` and added some debug info to the [domain error handler](https://github.com/hapijs/lab/blob/master/lib/runner.js#L390-L393):

```js
var onError = function (err) {

    console.log('*** ERR', err.stack);
    finish(err, 'error');
};
```

In my case, it turned out there was a `setTimeout` that wasn't being cleared before the test finished. So maybe that's why the stack wasn't shown.

Would it be helpful to add a `--debug` (for lack of a better name) option that printed the stack to help track down these kinds of issues?

**Comment by motdotla** [comment]
:+1: I ran into this as well.

**Comment by geek** [comment]
@jedireza I like the debug flag idea.

**Comment by garthk** [comment]
I've found [stackup](https://www.npmjs.com/package/stackup) immensely helpful for tracking down stray domain errors reported by lab.

**Comment by garthk** [comment]
Aand, just had to use @jedireza's `lib/runner.js` hack.

**Comment by jedireza** [comment]
We can now use the `-d`, `--debug` flag. If you can, please give it a try with the use cases you've come across and send feedback and change requests if needed.

**Comment by geek** [comment]
@garthk and @jedireza this is now published as lab v5.4.0

**Comment by jedireza** [comment]
:grin: nice

**Comment by motdotla** [comment]
Thanks for this. :100:
