### ISSUE TITLE
Global before() and after() hooks

### ISSUE THREAD

**Issue by gagle** [hapijs/lab#301]
I'd like to perform some setup tasks before all the tests are executed and teardown tasks after all the tests finish. Right now I'm opening and closing a connection to mongodb for each test file and I'd like to do this only once.

I'd like to have some kind of cli switch where I could pass a file which exports setup and teardown functions, something like:

```
$ lab testDir --hooks file.js
```

```javascript
// file.js
exports.before = function (done) {
  // Set up tasks, e.g. open database connection
  done();
}
exports.after = function (done) {
  // Tear down tasks, e.g. close database connection
  done();
}
```

**Comment by gagle** [comment]
I ended up using a programmatically approach (please document it). This also allowed me to have control over the `coveragePath` and `coverageExclude` (https://github.com/hapijs/lab/issues/298). Why are you hardcoding a value instead of exposing them in the cli interface?

**Comment by Marsup** [comment]
I'm using gulp with gulp-lab to run my tests, all it needs is ordering and it's done.
```js
gulp.src(['before.js', 'test/**/*.js', 'after.js'])
  .pipe(lab(options))
  ...
```
The same thing can be achieved with pure shell syntax.

Not saying your approach is wrong but it seems convoluted.

**Comment by gagle** [comment]
The problem with gulp-lab is that it is spawning a child process and you cannot pass objects. I the before hook I set up a database connection, it is used in the tests and is disconnected in the after hook.

**Comment by Marsup** [comment]
That's exactly what I'm doing, creating globals in the before and destroying in after.

**Comment by gergoerdosi** [comment]
@Marsup How does your before hook look like? Can you share some code? I would be interested in a bootstrap file too. The best would be if objects could be assigned to the global namespace (like server for `server.inject()` calls) before the test suite runs. I would also like to move the `var before =`, `var describe = `, etc. declarations out of the test files.

**Comment by Marsup** [comment]
It looks the same as any test.

Currently it's similar to that : (sorry, ES6)
```js
import Lab from 'lab';
export var lab = Lab.script();

lab.it('before test suite', (done) => {
  global.foo = 'bar';
  done();
});
```
Subsequent tests just have to call `foo` :

```js
import Lab from 'lab';
export var lab = Lab.script();

lab.it('works', (done) => {
  expect(foo).to.equal('bar');
  done();
});
```
Gotta remember to remove that at the end though :
```js
import Lab from 'lab';
export var lab = Lab.script();

lab.it('after test suite', (done) => {
  delete global.foo;
  done();
});
```

Maybe there are better ways, this one works for sure.

**Comment by gagle** [comment]
Please, look at this issue: https://github.com/hapijs/lab/issues/303

What we really need is a programmatic way to use `lab`.

**Comment by gergoerdosi** [comment]
@Marsup I see, thanks!

**Comment by Marsup** [comment]
@gagle I noticed this issue, that's why I completed this one, I don't see the need for it.

**Comment by shinzui** [comment]
Using globals seems like a horrible hack. It's surprising that lab does not have a proper way to handle this common use case.

**Comment by geek** [comment]
If you need to do cleanup after an individual test use the onCleanup solution:

```
lab.test('cleanups after test', (done, onCleanup) => {

    onCleanup((next) => {

        cleanup_logic();
        return next();
    });

    Code.expect(1 + 1).to.equal(2);
    done();
});
```

If you need to do cleanup after each test use `afterEach`, if you need to do cleanup after all tests have run in a script file use `after`.  If you need to do cleanup before the node process exits you `process.once('exit')` or simply run a cleanup script afterwards.

**Comment by shinzui** [comment]
@geek Thank you for your reply. How about bootstrapping? I am trying to run my schema migrations before running **all** the tests, and I want to drop the database when I'm done. 

I already solved my problem by doing something similar to #303, it's just weird that it's not intuitive and built-in. Isn't that a common use case?

**Comment by jamesdixon** [comment]
> The same thing can be achieved with pure shell syntax.

@Marsup were you speaking of using the `grep` option?

**Comment by Marsup** [comment]
Nah, I kind of expect just doing something like `lab test/before.js test test/after.js` would work but I have no idea so don't take my word for it ;)

**Comment by jamesdixon** [comment]
Has anyone gotten this to successfully work when using `.only` to run a specific test? I can get my `bootstrap.js` file to run when all tests are run, but if I run a specific test, it's never run.

**Comment by geek** [comment]
@jamesdixon yes, I use the `.only` feature, I just double-tested it to be sure. What version of lab are you using, also can you share the tests that are not working?

**Comment by jamesdixon** [comment]
@geek thanks for the quick reply.  I'm using Lab 15.3.1.

Could you share the specific command you run to ensure that your bootstrap file always runs? I think that may be part of the issue.

It's with any test I run. I'll post one shortly.
