### ISSUE TITLE
Testcase should fail with uncaught exceptions

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/lab#302]
I am not sure if everyone agrees, but I would think that uncaught exceptions should cause an testcase to fail. I also dont know if this can easily achieved with lab. I just had testcases that passed although an exception was thrown. I only saw it in the logs. 

Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot call method 'create' of undefined
    at Object.ondone (d:\gambify\lib\modules\session\service\setToken.js:33:17)

**Comment by geek** [comment]
@KeKs0r can you provide an example of the test code.  Looks to me like this is more an issue with what the test case is checking

**Comment by KeKs0r** [comment]
I think u are right i was not able to reproduce this in plain lab. Its probably because the error was not further populated in my application.
