### ISSUE TITLE
Allow a programmatic usage

### ISSUE THREAD

**Issue by gagle** [hapijs/lab#303]
Related: https://github.com/hapijs/lab/issues/301

I'm trying to run the tests programmatically and after looking to the source files I've ended up writing a [module](https://github.com/gagle/node-labby).

I need to execute a "global" very slow task. Before using this programmatic approach, the "global" task was executed for each test and the tests were executed in 1700ms. Now the "global" task is executed only once, just before executing the tests. They are executed in 200ms.

```javascript
require('labby')({
  base: __dirname + '/../../test/api',
  coverage: true,
  coverageBase: __dirname + '/../..',
  coverageExclude: ['lib/**', 'test/**'],
  globals: [
    '__require',
    '__root'
  ],
  paths: process.argv.slice(2)
}).start();
```

The module is still not documented because first I need your advice, but it basically allows a better control over the paths.

1. When the tests finish, the process is forced to exit: [lib/reporters/index.js#L53](https://github.com/hapijs/lab/blob/3c857b5d72932f9a862b7ac272b1b31cc5375e04/lib/reporters/index.js#L53).

  I'm monkey-patching `process.exit()` to prevent that. The process exit doesn't need to be forced.

2. When lab is required, the require extension loader for `.js` files is monkey-patched: [lib/coverage.js#L23-L37](https://github.com/hapijs/lab/blob/3c857b5d72932f9a862b7ac272b1b31cc5375e04/lib/coverage.js#L23-L37)

  I'm saving the original function and restoring it when the tests finish. I'm also delaying the `require('lab')` as much as I can. You can call to `internals.prime()` the first time `exports.instrument()` is called.

3. The final callback never returns an error: [lib/reporters/index.js#L50](https://github.com/hapijs/lab/blob/3c857b5d72932f9a862b7ac272b1b31cc5375e04/lib/reporters/index.js#L50). The error is completely ignored in this function [lib/runner.js#L80](https://github.com/hapijs/lab/blob/3c857b5d72932f9a862b7ac272b1b31cc5375e04/lib/runner.js#L80) and in other internal callbacks in the same file ([lib/runner.js](https://github.com/hapijs/lab/blob/3c857b5d72932f9a862b7ac272b1b31cc5375e04/lib/runner.js)). The error handling could be improved a lot.

**Comment by KeKs0r** [comment]
+1 for the global before and after hooks. I am facing similiar issues, but I have a system with multiple plugins (=folders) and every plugin has its own testsuite. I would love to see also the option to run global hooks for a folder or a certain testsuite. Although I have no idea how this could be achieved.

**Comment by tribou** [comment]
:+1: for this issue unless there's a better architecture...  

For instance, to do Sails.js testing, the following bootstrap file is recommended to use with mocha: https://github.com/balderdashy/sails-docs/blob/master/concepts/Testing/Testing.md#bootstraptestjs  But I can't find any info about `bootstrap.test.js` in the mocha documentation.

However, would it be possible/better to just instantiate a singleton instance of lab with a `before()` and `after()` in one bootstrap file and require it throughout all of the other test files?

**Comment by tribou** [comment]
Created a workaround with a `/test/bootstrap.js` file:

```javascript
// bootstrap all the tests and export server and lab

// Include all needed modules
var Hapi = require('hapi');
var Lab = require('lab');
var requireDirectory = require('require-directory');
var Config = requireDirectory(module, '../config');
var Plugins = Config.plugins;
var Routes = Config.routes;
var server = new Hapi.Server();

// Create shortcuts for easier reading
var lab = exports.lab = Lab.script();
var describe = lab.describe;
var it = lab.it;
var before = lab.before;
var beforeEach = lab.beforeEach;
var after = lab.after;
var afterEach = lab.afterEach;

before(function (done) {
    // Initialize your connection before your routes
    server.connection();

    // Pull in the production routes
    server.route(Routes);

    // Register plugins
    server.register(Plugins, function (err) {
        if (err) {
            return console.error(err);
        }

        done();
    });
});

module.exports = {
    lab: lab,
    server: server
};
```

And an example of a test that uses it:

```javascript
var Code = require('code');

// Create shortcuts for easier reading
var bootstrap = require('../bootstrap');
var server = bootstrap.server;
var lab = bootstrap.lab;
var describe = lab.describe;
var it = lab.it;
var before = lab.before;
var beforeEach = lab.beforeEach;
var after = lab.after;
var afterEach = lab.afterEach;
var expect = Code.expect;

// scrub the user table in the database before each test
beforeEach(function (done) {
    var Dogwater = server.plugins.dogwater;
    Dogwater.user.destroy(function () {
        done();
    });
});

describe('POST /users', function () {

    it('should create one user with good request', function (done) {
        var data = '{"user": {"login": "userid"}}';
        // Run test
        var options = {
            method: 'POST',
            url: '/v2/users',
            payload: data
        };

        var expected = {
            'user': {
                'login': 'userid'
            }
        };

        server.inject(options, function (res) {
            var payload = JSON.parse(res.payload);
            expect(res.statusCode).to.equal(201);
            expect(payload.user).to.include(expected.user);
            done();
        });
    });
});
```

**Comment by danecando** [comment]
+1 and thanks for sharing @tribou 

hapi promotes splitting up functionality into smaller plugin units so it would make sense to be able to include your tests in a single plugin and test all your plugins at the same time from your project root

**Comment by albertovasquez** [comment]
If you want to run the tests directly instead of npm test then I needed to 
```
let lab;
if (GLOBAL._labScriptRun) {
  lab = exports.lab = bootstrap.lab;
} else {
  lab = bootstrap.lab;
}
```

Otherwise I would get this error
```
The file: /path/xxxx.js includes a lab script that is not exported via exports.lab npm ERR! Test failed.  
```
