### ISSUE TITLE
Add src level transforms

### ISSUE THREAD

**Issue by ldesplat** [hapijs/lab#306]
I hacked my current copy of lab to support react's JSX syntax and I was wondering if a generalized PR for applying source level transforms would be welcome?
This would allow you to write tests but also your application using ES6 syntax & beyond, support compile to javascript languages, and extensions like JSX without using a compile step before running tests.

To enable this, a transform option would have to be created and the following 2 files would have to support it:
- cli.js, loading test scripts in traverse function. Would have to overwrite require.extensions[] with new method & then return it once we're done with require of all test files.
- coverage.cli, in internals.instrument, would have to apply the transforms right after reading the contents of the file.

I am asking this question also because some transforms could change line numbers so coverage line numbers could be different. So, it is not very ideal if you are not careful what transforms you are applying to the files.

Any thoughts? I don't mind modifying Lab for my use case, but it would be nice to have such a feature in upstream.

**Comment by Marsup** [comment]
I personally think it's out of the scope of lab and there are countless build systems, I'd rather have people deal with that on their own. Lab already supports sourcemaps which should help.

We'll see what other people think.

**Comment by jedireza** [comment]
I was just talking to @geek about sourcemaps and jsx. I threw a spike together to demonstrate the `Coverage: 0.00% (0/0)` I see when trying using `node-jsx`. You can see it here:

 - https://github.com/jedireza/lab-jsx

Maybe [`node-jsx`](https://github.com/petehunt/node-jsx) isn't doing something right with sourcemaps.

@ldesplat are your modifications to lab on GitHub?

**Comment by ldesplat** [comment]
@jedireza You can find them there: [https://github.com/ldesplat/lab/commit/da36d454e12b7de06d779570f6087df6297ee241?diff=split](ldesplat/lab)

I get the following output when running it in my project:
```
No global variable leaks detected
Coverage: 71.70% (45/159)
lib/components/Image.js missing coverage on line(s): 19, 20, ... 163, 164, 171, 172, 179, 180
Code coverage below threshold: 71.70 < 100
```

**Comment by Marsup** [comment]
@jedireza I think node-jsx doesn't do anything at all about sourcemaps, which might be the problem here, and probably yours later :)

**Comment by jedireza** [comment]
@ldesplat's changes do get coverage to display. https://github.com/jedireza/lab-jsx/tree/ldesplat

Sourcemaps are not my strong suit. [`node-jsx`](https://github.com/petehunt/node-jsx/blob/master/index.js) isn't very big and @ldesplat's changes don't seem very involved. How can we get this out of lab and still get this to work? Is there something we can do to `node-jsx` that would get the `--sourcemaps` feature to work?

**Comment by ldesplat** [comment]
@jedireza We are now going out of bounds for this issue but here's the way that I see it working with --sourcemaps feature.

Use a transpiler like [6to5](6to5.org) and AST generator like [acorn-jsx](https://github.com/RReverser/acorn-jsx) or esprima-fb. You could use them using webpack or browserify. Tell them to generate an inline sourcemap. Then, it should work. I have not tried that way yet.

**Comment by ldesplat** [comment]
Since, there has not been much comment I will close this issue for now. if it bothers me again for another project, then I will make sure to revisit it. My code will continue being available in case someone wants to see how it can be hacked together.
+1 for Lab having accurate code coverage. It is so hard to find.

**Comment by geek** [comment]
@ldesplat I was thinking about updating to Esprima 2.0 for the ES6 coverage too, will that help this case as well?

**Comment by ldesplat** [comment]
@geek I am all for some ES6 coverage so it would help a bit! Moving to esprima-fb would help my case (JSX), but I think that's a stupid decision for Lab.
