### ISSUE TITLE
Teamcity reporter integration?

### ISSUE THREAD

**Issue by joseph-norman** [hapijs/lab#309]
Since there's a number of reporter types already available in lab ( `console, tap, lcov, clover, ...`), would it be an option to include a teamcity CI reporter? Can create PR if so.

**Comment by Marsup** [comment]
It would probably be better solved with #216.

**Comment by antipin** [comment]
There is a custom reporter for TeamCity https://www.npmjs.com/package/lab-teamcity-reporter

**Comment by geek** [comment]
Thanks, @antipin...  we will to start linking to these somewhere in our documentation.
