### ISSUE TITLE
Support multiple reporters

### ISSUE THREAD

**Issue by feugy** [hapijs/lab#312]
We're trying to use lab output into a forge where 
- Jenkins needs junit file report 
- Sonar needs lcov file report.

It could be very nice to allow specifying multiple reporters, because today, the only option I have is to run tests twice with a different configuration.

Mocha has the [same feature in progress](https://github.com/mochajs/mocha/pull/930), mainly for the same reasons.

**Comment by lloydbenson** [comment]
I think this is a dupe of https://github.com/hapijs/lab/issues/285.
