### ISSUE TITLE
Support multiple linter

### ISSUE THREAD

**Issue by feugy** [hapijs/lab#313]
Adding the possibility of calling a linter is a very interresting option.
But we need several linters: 
- [jsHint](http://jshint.com/docs/) for "compiler-style" validations
- [jsCS](http://jscs.info) for "code style" validations
- [jscpd](https://github.com/kucherenko/jscpd) for "duplicated code" checks
- ...

Currently, we are calling linters independently from lab, it would be very nice to use this feature.

**Comment by AdriVanHoudt** [comment]
Related? https://github.com/hapijs/lab/pull/290

**Comment by geek** [comment]
@feugy we do support jshint.  We don't use the other ones you mentioned.  With eslint you can achieve a lot of code style rules.  Are you interested in adding in jscs?

**Comment by Marsup** [comment]
@geek I think he meant multiple linters at the same time.

**Comment by geek** [comment]
Ahh, thats a cool idea.  We could probably do that, but is it useful/worth it?

**Comment by AdriVanHoudt** [comment]
Make it an option?

**Comment by Marsup** [comment]
It is for us. (we're in the same team)

This needs to be well thought if we introduce thresholds for linters.

**Comment by Marsup** [comment]
@geek what would you think of the ability to provide a (json ?) configuration file to lab ? I like it way better than the #321 you just merged.

**Comment by geek** [comment]
Sounds like you have a pretty awesome team if you two are on it!

I am for it... definitely open to a PR for this feature.

**Comment by geek** [comment]
@Marsup that seems to be the direction we need to go, `.labrc` or a config being passed in?

**Comment by Marsup** [comment]
Something like that yes, the CLI is a mess with all those switches. I don't know if it's better to have it implicit or explicit though.

**Comment by AdriVanHoudt** [comment]
I like the `.labrc` way. Keeps the `npm test` commando clean for example.

**Comment by ldesplat** [comment]
+1 to a way to specify a configuration file or implicit `.labrc`. Does not matter much to me. There are just too many configuration switches!

@Marsup for #321 I was working with what I had. I agree it's not pretty :(

**Comment by Marsup** [comment]
@ldesplat I know I know, nothing personal :)

Should we completely drop the CLI and go file-only ?

**Comment by AdriVanHoudt** [comment]
How would you run different configs of lab? e.g. with html output or not.
Add options in the config file? leading to running `lab html` or `lab default`, both `html` and `default` would be keys in the config.

**Comment by Marsup** [comment]
Different files ? Environment ? Override file settings with CLI switches ? There are solutions, I don't know if we need to have several though.

**Comment by geek** [comment]
Can now use custom linters
