### ISSUE TITLE
Leak Checking Output

### ISSUE THREAD

**Issue by tjsail33** [hapijs/lab#315]
I'm confused by the output of the leak checking being run, which is `The following leaks were detected:$M, $P, $V, $L`.

Do any of you know what those symbols mean? I couldnt find them mentioned anywhere in this repo.

**Comment by cjihrig** [comment]
Those symbols are from the code that is being tested.

**Comment by krazik** [comment]
I'm encountering this same error, I've tracked it to a 3rd party package I'm using but can't find the source.  is there a workaround when you can't control the other code?

```The following leaks were detected:$V, $M, $L, $P```

**Comment by krazik** [comment]
found the source: https://github.com/NaturalNode/node-sylvester/issues/6

**Comment by cjihrig** [comment]
If the leak is out of your control, you can whitelist the global using `-I`. An example is here https://github.com/continuationlabs/big-time/blob/master/package.json#L7

**Comment by alexandrebodin** [comment]
@krazik Too ignore those leaks:

### `package.json`
```json
{
    "scripts": {
        "test": "lab -S -T test/babelTransform.js -I '$L,$V,$P,$M'"
    }
}
```
