### ISSUE TITLE
Catching async thrown errors & validating

### ISSUE THREAD

**Issue by ldesplat** [hapijs/lab#325]
I needed to catch a thrown error from an async method. I have the following test that does works somewhat with very bad errors because Code throws its own errors which are caught by our own domain! I am probably cleaning up the domain all wrong too.

I was wondering if anybody has any hints on how to solve such a scenario?

PS. I have removed all thrown code as much as I can so I don't need this anymore but I am still curious. These domains are way too confusing.

```javascript
var Lab = require('lab');
var Code = require('code');
var Domain = require('domain');

var expect = Code.expect;
var lab = exports.lab = Lab.script();

function badFunction(callback) {

	setTimeout(function () { throw new Error('help me') }, 1);
}

lab.experiment('async', function () {

	lab.test('badFunction', function (done) {

		var d = Domain.create();
		d.on('error', function (error) {

			expect(error).to.be.an.instanceof(Error);
			expect(error.message).to.equal('help me');
			done();
		});

		d.run(function() {
			badFunction();
		});

		d.exit();
	});
});
```

**Comment by Marsup** [comment]
You don't need the final exit.

**Comment by ldesplat** [comment]
Thanks. I guess it's very much an anti-pattern to do so, so it's not so bad it's hard to test.
