### ISSUE TITLE
Debugging with node-inspector

### ISSUE THREAD

**Issue by duro** [hapijs/lab#328]
I seem to be unable to debug lab tests with node-inspector. With mocha, you can pass the --debug-brk flag to the test running and it will start the debugger.

If I do the same with lab:

```
lab --debug-brk=5355 -v -t 50 --ignore window,document,regeneratorRuntime,jQuery,_babelPolyfill,core,Reflect test/client/
```

I get the following error:

```
Unknown option: debug-brk=5355
```

Any idea how I can get lab tests debugging the same way I can in Mocha?

**Comment by arb** [comment]
Try 
> `node-debug node_modules/.bin/lab -v -t 50 --ignore window,document,regeneratorRuntime,jQuery,_babelPolyfill,core,Reflect test/client/`

**Comment by jamesdixon** [comment]
@arb I gave that command a shot, but no luck with using node-inspector to debug lab tests. Here's the output I get from node-inspector:

![image](https://cloud.githubusercontent.com/assets/110114/10116007/1ecd2214-63de-11e5-99b3-7891effd4508.png)

Any ideas?

Thanks!
James

**Comment by mtharrison** [comment]
Press the start/pause button to kick it off.

**Comment by jamesdixon** [comment]
Wow. Thanks, @mtharrison. I'm now sitting here trying to determine whether or not I should feel like an idiot for not realizing that...

**Comment by jamesdixon** [comment]
@mtharrison one last question for you: when I kick things off, it takes quite a while for all of the libraries to load; much slower than running lab directly. Is this unavoidable or is there a way to speed it up? Thanks!

**Comment by mtharrison** [comment]
Yes it is slow. Not sure there's anything that can be done about that. Running with the built in node debugger is usually a bit faster (node debug vs node-debug) but the experience isn't as good.

**Comment by jamesdixon** [comment]
Gotcha. Thanks again for the help!
