### ISSUE TITLE
Upgrade eslint or permit custom lint adapters

### ISSUE THREAD

**Issue by garthk** [hapijs/lab#330]
I'd like to use `lab` in `prepublish` to enforce both tests and style, but it wants `eslint` version `0.14.x` rather than the most recent `0.17.1`. Any chance of an upgrade?

I'll settle for `lib/lint` forking with `path.resolve(settings.lintingPath, settings.linter))` as the first argument if that value passes `path.existsSync`.

**Comment by AdriVanHoudt** [comment]
Try just updating the package.json to 0.17.x and see if it breaks. If not the PR should be super easy

**Comment by Marsup** [comment]
It would be far easier for us if ESLint reached 1.x, which doesn't seem to be that far if their milestone is correct. I'd say this problem is only temporary and leave it at that.

**Comment by AdriVanHoudt** [comment]
w8 I did a PR for 0.17.x https://github.com/hapijs/lab/pull/327

**Comment by geek** [comment]
Published lab with the eslint 0.17.

**Comment by AdriVanHoudt** [comment]
ok that solved it prob :D
