### ISSUE TITLE
`--lint-options` to be defined as filepath, not JSON string

### ISSUE THREAD

**Issue by tunnckoCore** [hapijs/lab#333]
How you see to define my all 20 lines jshint config as JSON in console, actually in package.json scripts object (`npm test`)? Yea there is a tricky way, but its enormous..

**Comment by ldesplat** [comment]
Specify a .jshintrc file in your project. You can use --lint-options if there are any options that cannot be passed through the .jshintrc file.

Issue #313 although it has a different title, also touches on a unified config file for not just lint-options but all of lab's options.
