### ISSUE TITLE
Different test results with coverage option

### ISSUE THREAD

**Issue by MathieuLoutre** [hapijs/lab#340]
I've spent a few hours investigating this and I'm really not sure where it comes from. I'm using CoffeeScript, compile it to JavaScript and then run the tests with `lab 5.1.x`.

Here's the CoffeeScript code:

```coffee
rejected = ['rejected']
for o in objects
    if o.status in rejected
        console.log(o.status in rejected)
```

It compiles to this:

```js
var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

var o, k, len, ref, ref1;
for (k = 0, len = animals.length; k < len; k++) {
	o = objects[k];
	
	if (ref = o.status, indexOf.call(rejected, ref) >= 0) {
		console.log((ref1 = o.status, indexOf.call(rejected, ref1) >= 0));
	}
}
```

When running with:
`lab unit.js -m 0`

I get this very sensible output:
```
true
true
true
```

But when running the tests with this command:
`lab unit.js -m 0 -c -r console`

I get this crazy output:
```
false
false
false
false
true
true
true
```

It turns out that when running the tests with coverage, what's returned on the if is _always_ true. If I change the `if` statement to a more JavaScript-like `rejected.indexOf(o.status) >= 0` it does work, both with and without coverage enabled.

I'm unclear if it's a bug in Lab or in CoffeeScript, but I really can't pinpoint it. Anyone can shine a light on this?

**Comment by Marsup** [comment]
Best way to debug that case is to see the code once transformed for coverage, maybe the problem is the comma.

**Comment by MathieuLoutre** [comment]
I thought I had seen the transformed code somewhere a while ago, but it doesn't seem to be there anymore. What's the best way to access it?

**Comment by geek** [comment]
@MathieuLoutre are you running the CoffeeScript code through coverage or the transpiled version?

If you aren't already, can you change to the JavaScript form and see if the issue is reproduced, just to narrow it down.

**Comment by MathieuLoutre** [comment]
Thanks for having a look @geek, I'm running the transpiled version. I'm compiling the CoffeeScript first, then running the tests all in JavaScript. The problem definitely happens when CoffeeScript generates this line `if (ref = o.status, indexOf.call(rejected, ref) >= 0) {` because `rejected.indexOf(o.status) >= 0` works like a charm.

**Comment by MathieuLoutre** [comment]
@geek haven't tried this in a while, but is that fixed? that would be really cool.

**Comment by geek** [comment]
@MathieuLoutre it should, we redid the reporters command.  Let me know if not and we can investigate
