### ISSUE TITLE
no-catch-shadow

### ISSUE THREAD

**Issue by hueniverse** [hapijs/lab#369]
https://jslinterrors.com/value-of-a-may-be-overwritten-in-ie8

Why do we care?!

**Comment by Marsup** [comment]
Variable shadowing is usually a bad practice, catch or not.

**Comment by jzorn** [comment]
I agree. Makes the code harder to understand, too.

**Comment by hueniverse** [comment]
is there a better error than one about IE8?

**Comment by geek** [comment]
We can use https://jslinterrors.com/a-is-already-defined instead, it accomplishes the same thing.

**Comment by hueniverse** [comment]
wfm

**Comment by Marsup** [comment]
@geek that would be `no-shadow`, which is currently disabled.
