### ISSUE TITLE
Reduce the overhead of lab require statements

### ISSUE THREAD

**Issue by martinheidegger** [hapijs/lab#373]
I have used `lab` extensively in the past. When I recently started using lab again I had to update my code templates to accommodate for the features that have been cut out of lab. This is how the overhead looks like:

```JavaScript
'use strict';

var Lab = require('lab'),
    code = require('code'),
    lab = Lab.script(),
    expect = code.expect,
    describe = lab.describe,
    it = lab.it;

// 

module.exports = lab;
```

Putting aside the fact that this block with unsorted variable names (`lab` is after `describe` in the alphabet) is problematic for linting: for most of the statements in this block I don't see a reason why I have to write them in every file in my test folder and a beginner would wonder why to write any of those lines at all.

My suggestion to reduce this clutter would be a two way strategy:

1) Make use of npm's deep link capabilites
```JavaScript
'use strict';

var lab = require('lab/script')(),
    expect = require('code/expect'),
    describe = lab.describe,
    it = lab.it;

// 

module.exports = lab;
```

2) Create variable test-preset options for as cli argument.
`module.exports = lab` is required to separate tool files from test files in my understanding and also to mix different test suites. A `test-preset` option could do following:

`lab -P test/**/*.js prefix.js`

Meaning: For all files that match the pattern `test/**/*.js` execute `prefix.js` to prepare global variables **and** all those files are treated as tests by default (no module-exports required)

Content of `prefix.js`
```JavaScript
'use strict';
var expect = require('code/expect'),
     script =  require('lab/script');

module.exports = function (global) {
    global.lab = lab;
    global.describe = global.lab.describe;
    global.it = global.lab.it;
    global.expect = expect;
    return global;
}
```

Which then would reduce the test files to:

```JavaScript
describe('...', function () {
  it('heythere', function(done) {
  });
});
```

**Comment by hueniverse** [comment]
Sorry but No. Not using globals was one of the main motivations behind replacing mocha with lab. The boilerplate text is easy enough to cut/paste and is the right approach.
