### ISSUE TITLE
Experiment description not showing in output

### ISSUE THREAD

**Issue by thebinarypenguin** [hapijs/lab#375]
I have multiple sub-experiments with the same description and only one is displayed in the output.

Code:
```js
var Code = require('code');
var Lab  = require('lab');

var lab = exports.lab = Lab.script();

lab.experiment('Alpha', function() {

  lab.experiment('foo', function() {

    lab.test('bar', function(done) {
      done();
    });
  });
});

lab.experiment('Bravo', function() {

  lab.experiment('foo', function() {

    lab.test('bar', function(done) {
      done();
    });
  });
});
```

Output:
```
Alpha
  foo
    ✔ 1) bar (2 ms)
Bravo
    ✔ 2) bar (2 ms)


2 tests complete
Test duration: 6 ms
No global variable leaks detected
```

- Notice that 'foo' does not appear under the 'Bravo' section
- If I change the 'foo' in the "bravo' section to 'fu' or even 'foo ' it will show up

**Comment by joseph-norman** [comment]
After running some initial tests, this looks to be confined to just `console` reporting - I've managed to get it printing experiment names which may be the same. Would you like me to raise a PR with this fix?

**Comment by geek** [comment]
@joseph-norman yes please.  Thank you!
