### ISSUE TITLE
Lint too aggressive with empty lines before comments

### ISSUE THREAD

**Issue by hueniverse** [hapijs/lab#376]
See: https://travis-ci.org/hapijs/vision/jobs/67770146

Basically, it is common to comment at the end of a require block as well as default values in an object. Not sure if this is easy to specify of just to drop this style rule.

**Comment by AdriVanHoudt** [comment]
Yeah when I added the rule I also noticed that default values would be a problem, there is an option to not enable this rule on `/*  */` style comments but that does not fully solve your issue. The at the end of a require block seems weird, why not at the start? 
Full rule spec [here](http://eslint.org/docs/rules/lines-around-comment)

**Comment by hueniverse** [comment]
The way vision uses comments is consistent with the overall style, we just need a way to articulate it.

**Comment by AdriVanHoudt** [comment]
Ok then we have 3 options
1. use `/* */` (not really wanted ofc)
2. disable the rule
3. Make a custom rule that allows the rule with the edge cases (and probably disable the current rule until then)

**Comment by hueniverse** [comment]
3 otherwise 2.

**Comment by AdriVanHoudt** [comment]
Since 3 includes 2 disable it for now (I might do a PR tomorrow for the new eslint version and I will include it then if no one else has already), and @cjihrig since you made the other custom rules, any way you might be able to make this work?

**Comment by cjihrig** [comment]
I would recommend dropping this rule. From a quick glance it looks like you're going to require too much context to do anything useful. For example, the rule would have to recognize comments that immediately follow variable declarations whose right hand side is a `require()` call in the global scope. Or recognize comments inside an object literal whose name is `internals.defaults`. I think you'd likely end up with something very hacky.

**Comment by AdriVanHoudt** [comment]
ok, so 2 :P we could set it as a warning but I'm 99% sure that's not wanted
