### ISSUE TITLE
Shadow lint error going too far

### ISSUE THREAD

**Issue by hueniverse** [hapijs/lab#379]
See: https://travis-ci.org/hapijs/wreck/jobs/67856616

Basically, it is fine to shadow some variables like `err` in callback. If you didn't handle it at the top of the method you clearly don't care. I have never seen bugs because of `err` argument shadows. I am going to go over the warning in hapi and see which one I find useful and fix those. I'll be back here with my findings but just heads up that I am going to want to see this rule changed at least for some cases.

**Comment by geek** [comment]
I think you are correct.  This change has improved my code, but in some cases with `err` it is likely overkill.

**Comment by geek** [comment]
I created https://www.npmjs.com/package/no-shadow-relaxed

We can allow certain variables to be shadowed, like `err, done, res`... any others?

**Comment by hueniverse** [comment]
I think just `err` and `done` for now. `res` is an special one in tests so probably better to require doing `res1`, `res2`...
