### ISSUE TITLE
File name matching glob pattern

### ISSUE THREAD

**Issue by walling** [hapijs/lab#384]
With nested folders for your code, it is sometimes nice to make your test files be along the production code, fx. `my-route-test.js` accompanying `my-route.js`. I would basically love to have an option for matching file patterns like this:

```bash
lab -P src/**/*-test.js
```

Is it on the roadmap?

**Comment by walling** [comment]
Looking at [cli.js:329-331](https://github.com/hapijs/lab/blob/master/lib/cli.js#L329-L331) it might not be super easy to implement. I would also be happy with just matching filename (without extension), like so:

```bash
lab -P *-test src  # Running in src/ directory and looking for files named *-test.js
```

This way the extension overwrite system can be kept. I think it would be a minor change.

**Comment by smaxwellstewart** [comment]
Hey any chance of how to implement this enhancement? I can't get this to work with.

```bash
$ lab --pattern **/*_test.js
```
My test files are not located in a `test` folder.

**Comment by gergoerdosi** [comment]
Here is an example: `lab --pattern '_test' src`. This command will look for files ending with `_test.js` in the `src` directory.

**Comment by smaxwellstewart** [comment]
Yeah I was struggling to make it look in any sub directory as my tests are next to the source code they are testing, but everything is located in two sub directories so i think i could make it work.

Is there an easy way to get lab to look in all folders?

**Comment by gergoerdosi** [comment]
If those directories don't change, you can just specify two directories:

```sh
lab --pattern '_test' api web
```

I suppose `lab --pattern '_test' .` should work too, but it throws an error for me. Probably a bug.
