### ISSUE TITLE
Custom reporter not working from command line

### ISSUE THREAD

**Issue by georgeflugq** [hapijs/lab#391]
I am trying to use a custom reporter from the command line but can't get it to work.  I installed my own reporter, 'ownreporter' to node_modules, but it returns an error:

Usage: lab [options] [path]
(all options listed)
Invalid value for option: reporter

I have tried all of the following:
lab testfile.js -r ownreporter
lab testfile.js -r 'ownreporter'
lab testfile.js -r "ownreporter"
lab testfile.js -r ./node_modules/ownreporter
lab testfile.js -r './node_modules/ownreporter'
lab testfile.js -r "./node_modules/ownreporter"

Any help is much appreciated, thanks!

**Comment by geek** [comment]
Can you share the structure of the project... is it like this:

```
/project
/project/node_modules/ownreporter
/project/node_modules/lab
/project/test
```

?

**Comment by georgeflugq** [comment]
Yes that's it, I made a blank project for this so the structure is exactly:

    /lab-custom-reporter
    /lab-custom-reporter/node_modules/ownreporter
    /lab-custom-reporter/node_modules/ownreporter/index.js
    /lab-custom-reporter/node_modules/lab/**/*
    /lab-custom-reporter/testfile.js

ownreporter's index.js file contains the json reporter code from:
https://github.com/hapijs/lab/blob/master/lib/reporters/json.js

Thanks again!

**Comment by bapti** [comment]
I've been looking into this - looks to me that the `Bossy` definition [here](https://github.com/hapijs/lab/blob/master/lib/cli.js#L236)

```
        reporter: {
            alias: 'r',
            type: 'string',
            description: 'reporter type [console, html, json, tap, lcov, clover, junit]',
            default: 'console',
            valid: ['console', 'html', 'json', 'tap', 'lcov', 'clover', 'junit']
        },
```

Blows up [here](https://github.com/hapijs/lab/blob/master/lib/cli.js#L275) when you pass an argument like this `./my-reporter` which the docs state [here](https://github.com/hapijs/lab#custom-reporters)

**Comment by bapti** [comment]
Hopefully this will fix

https://github.com/hapijs/lab/pull/396

**Comment by georgeflugq** [comment]
bapti, thanks for the update! I tried the change locally and it works now!  Looking forward to the merge
