### ISSUE TITLE
Exit code always 0 with multiple reporters

### ISSUE THREAD

**Issue by walling** [hapijs/lab#393]
Running with a single or just the default reporter `lab` returns exit code 1 for failed tests. It seems not to be the case, when running with multiple reporters. To reproduce:

1. Create failing test case `test.js`:

    ```js
    var lab = exports.lab = require("lab").script();

    lab.test('fail', function(done) {
        done(new Error('fail'));
    });
    ```

2. Run with default reporter (exit code is 1):

    ```bash
    lab test.js; echo $?
    ```

3. Run with multiple reporters (exit code is 0):

    ```bash
    lab -r console -o stdout -r html -o cov.html test.js; echo $?
    ```

It could be nice to get this fixed, so you can run your continues integration build with multiple reporters. I don't have time for a pull request right now, but I might look into it later.

**Comment by bapti** [comment]
Hopefully this will fix

https://github.com/hapijs/lab/pull/396

**Comment by hofan41** [comment]
@bapti I don't think that will fix it, since the bug exists in multiple.js not doing process.exit.

**Comment by walling** [comment]
Is it possible to replicate [the finalize logic from reporters/index.js](https://github.com/hapijs/lab/blob/master/lib/reporters/index.js#L86-L102) in `multiple.js`?

**Comment by hofan41** [comment]
I have a fix for this will submit a PR shortly.

**Comment by lloydbenson** [comment]
I get an error when using multiple reporters that I believe this does fix.  Instead of what you describe in io.js  I see something like:
../node_modules/lab/lib/reporters/multiple.js:95
            callback(self._results.err, self._results.code, self._results.outp
            ^
TypeError: callback is not a function

I see indeed that callback is undefined for the reporters.  When I put in the code block you have however, when its doing an if callback clause this error seems to go away.  Thanks for getting this fixed but just an FYI in case others run into multiple reporter issues with different symptoms.

**Comment by lloydbenson** [comment]
@geek any updates with this one and if it looks good can we get it merged and published?

**Comment by geek** [comment]
@hofan41 you are my hero, thanks for fixing this issue.

**Comment by hofan41** [comment]
Hello!

 

Important message, visit http://bizsurvivor.com/offered.php?99ii

 

Ho-Fan Kang

**Comment by hofan41** [comment]
Hey!

 

Important message, please visit <http://crs.choszczno.pl/also.php?y>

 

Ho-Fan Kang

**Comment by hofan41** [comment]
Hello!

 

New message, please read <http://corymclark.com/eight.php?vqc>

 

Ho-Fan Kang

**Comment by hofan41** [comment]
hi,
I think this story is really awesome, you're gonna love it, please read it here <http://dufriticra.solvesystems.com/aearcpim>

Best regards, Ho-Fan Kang

**Comment by Marsup** [comment]
@hofan41 can you please do something to secure your account ? Thanks...

![Screenshot of posts I deleted](https://cloud.githubusercontent.com/assets/796194/15642533/4441d7e2-2648-11e6-986b-c3fbe9b9fa48.png)

**Comment by hofan41** [comment]
Apologies, I have added additional protections DKIM/DMARC/SPF to my email domain in hopes that this will prevent these spoofed messages from being received.
