### ISSUE TITLE
Proxy with record feature

### ISSUE THREAD

**Issue by zerkalica** [hapijs/lab#398]
Are there hapi-based api mock solutions with proxy/record feature? Like this:

https://github.com/gandi/mockify
https://github.com/seglo/connect-prism

**Comment by geek** [comment]
You can ask questions like this in https://github.com/hapijs/discuss/issues

Here is a thread that may relate to what you want: https://github.com/hapijs/discuss/issues/107

Here is a mock API using hapi: https://github.com/eferte/json-mock-hapi

Here is another mocking solution with hapi: https://github.com/walmartlabs/ridicule
