### ISSUE TITLE
What is --assert for?

### ISSUE THREAD

**Issue by Aluxian** [hapijs/lab#400]
I found this in the README:

    `-a`, `--assert` - name of assert library to use.

What does it do? I couldn't find any more description than what it's said there. I tried to repo search for `--assert` but nothing...

**Comment by AdriVanHoudt** [comment]
https://github.com/hapijs/lab/blob/master/lib/runner.js#L90 ?

**Comment by Aluxian** [comment]
Ah, I see! Thanks!

**Comment by AdriVanHoudt** [comment]
np, btw Lab works well with https://github.com/hapijs/code

**Comment by Aluxian** [comment]
That's what I'm using :)

**Comment by AdriVanHoudt** [comment]
:+1:
