### ISSUE TITLE
Test fail with 500 when using JWT

### ISSUE THREAD

**Issue by Jaraxal** [hapijs/lab#403]
I have a set of unit tests that work well.  I updated my hapi-based api to use JSON Web Tokens using hapi-auth-jwt2.  Now all of the tests that previously worked fail with a server 500 error.  I'm passing in a valid key as part of the tests.  I have debug output in the API itself that shows each one of the API calls the test submits are working properly.  Somewhere between the API responding with 200 http response and lab evaluating the results, it turns into a 500 error.  

I know the JWT portion itself is working because all tests related to invalid tokens pass with the appropriate 401 http responses.  All of the test cases work properly when submitted via curl or direct http calls using Wreck.

Is this a known issue?  Is there something I'm missing?  Here is one of the tests:
```javascript
var Lab = require("lab");
var lab = exports.lab = Lab.script();
var code = require("code");

var expect = code.expect;
var before = lab.before;
var after = lab.after;

var describe = lab.describe;
var it = lab.it;

var server = require("../server.js");

var valid_token = '<valid token goes here>';

var expired_token = '<expired token goes here>';

var invalid_token = 'abc123';
```

# The call using Lab fails
```javascript
  it('should return an array of collections for a valid request', {timeout : 45000}, function(done) {
    var options = {
      method : "GET",
      url : "/collections",
      headers : {
        "Authorization" : valid_token,
        "Content-Type" : "application/json; charset=utf-8"
      }
    };
   
    server.inject(options, function(response) {
      var payload = JSON.parse(response.payload);

      expect(response.statusCode).to.equal(200);
      expect(payload.collections).to.be.an.array();

      done();
    });
});
```
# The call using Wreck passes
```javascript
 it('should return an array of collections for a valid request', {timeout : 45000}, function(done) {
    // Define headers
    var options = {
      headers : {
        "Authorization" : valid_token,
        "Content-Type" : "application/json; charset=utf-8"
      }
    };

    // Submit request to server
    Wreck.get('http://<ipaddress>:<port>/collections', options, function(err, res, payload) {
      var response = JSON.parse(payload);

      expect(response.statusCode).to.equal(200);
      expect(response.collections).to.be.an.array();

      done();
    });
});
```

**Comment by geek** [comment]
What does the stack of the 500 look like?  You can also use the `result` property from shot instead of parsing the payload:
```js
server.inject(options, function(response) {

      expect(response.statusCode).to.equal(200);
      expect(response.result.collections).to.be.an.array();

      done();
});
```

**Comment by Jaraxal** [comment]
That is what is so puzzling; there doesn't seem to be a stack that I can see.  In the API itself, I have a console.log before each of my "throw error;" lines so that I can see what the errors are.  Right before each of the "reply" calls, I also have a console.log to see what the reply content will look like.

When the test runs, the API doesn't log any errors and only logs the valid response that I expect.  

However Lab shows the following:
## This is the output of the good-console module which shows the API responding with 500.
150716/140248.810, [response], http://<hostname>:<port>: get /batch/api/collections {"version":1} 500 (35188ms) 

## This is the output of console.log(response.result); within the test itself
{ statusCode: 500,
  error: 'Internal Server Error',
  message: 'An internal server error occurred' }

 ## Test output 
  x

Failed tests:

  1) Collections should return an array of collections for a valid request:

      actual expected

      500200

      Expected 500 to equal specified value

      at ./f3search-batch-api/test/collections.js:76:38


1 of 1 tests failed
Test duration: 35201 ms
The following leaks were detected:originalDefaultAttributes, originalDefaultReferrals

npm ERR! Test failed.  See above for more details.

**Comment by geek** [comment]
@Jaraxal is this still outstanding?  If so, please reopon.
