### ISSUE TITLE
code coverage fails when using class keyword or object literal shorthand properties

### ISSUE THREAD

**Issue by tmacie** [hapijs/lab#405]
When attempting to execute lab tests with code coverage turned on, espree throws with parsing errors. I've submitted PR #404 to fix this.

On a side note, is there a reason that all es6 features are not turned on?

**Comment by mshick** [comment]
I've encountered the same in a small project using es6 classes. Even the simplest test fails on coverage.

**Comment by tmacie** [comment]
@mshick The PR referenced in my comment has been merged, so this issue should be resolved in the next release (5.13.1 I believe)

**Comment by geek** [comment]
@tmacie no reason why they aren't turned on
