### ISSUE TITLE
No verbose or code coverage output

### ISSUE THREAD

**Issue by wgormley** [hapijs/lab#408]
I am using lab 5.13.0 and when i set my flags to -t 90 and -v the test runs fine but i am not getting any of the output printed to my screen. is there something i am missing?

**Comment by geek** [comment]
What is the command you run?

```
lab -t 90 -v
```

How do you know the tests are being executed?

**Comment by wgormley** [comment]
yep thats what i run, i still get this after the tests have ran

8 tests complete
Test duration: 4139 ms
No global variable leaks detected

but no code coverage or verbose output. i can manually go into cli.js and insert this which allows me to get code coverage

`options.coverage = true;
options.threshold = 90;`

**Comment by geek** [comment]
@wgormley please reopen if this is still an issue.
