### ISSUE TITLE
problems on windows?

### ISSUE THREAD

**Issue by Pomax** [hapijs/lab#410]
We're seeing an api server for which we're using Lab for testing fail on the lab tasks on windows, while they work just fine on OSX and Linux - has Lab been tested on Windows, or if not, is there a test suite that we can run to see if this utility will actually work in our cross-platform projects?

**Comment by geek** [comment]
@Pomax what version of node are you running?  I really don't test it much on windows, but am happy to take a look at your issue.

**Comment by Pomax** [comment]
node 0.12.7 (npm 2.11.3) on windows 7 (x64)

**Comment by AdriVanHoudt** [comment]
Windows always had issues running the tests https://github.com/hapijs/lab/issues/296

**Comment by Pomax** [comment]
Sounds like test running should always have been fixed, then =)

**Comment by geek** [comment]
I just tested on node v4 and Windows 10... no issues!

**Comment by Pomax** [comment]
nice!
