### ISSUE TITLE
Not possible to ignore files from coverage

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/lab#417]
I want to have 100% coverage on the files that are in the `lib` directory. However I have files outside this directory too (server, configuration, etc.) that shouldn't have full coverage. I put together an example here: https://github.com/gergoerdosi/lab-coverage-example

When I run tests I get this output:

```
$ node ./node_modules/.bin/lab -a code -t 100 -L -v
Hello Route
  #hello
    ✔ 1) succeeds (26 ms)


1 tests complete
Test duration: 30 ms
Assertions count: 1 (verbosity: 1.00)
No global variable leaks detected
Coverage: 94.74% (1/19)
index.js missing coverage on line(s): 10
Code coverage below threshold: 94.74 < 100
```

Is there a way to tell lab to only check coverage on the content of the `lib` directory? I checked the `-g` and `-P` options, but looks like those are only for running tests. It is also possible to ignore files from linting using `. eslintignore`, but there doesn't seem to be anything for coverage.

I could add `// $lab:coverage:off$` and `// $lab:coverage:on$` to all the files outside `lib`, but there should be a better way.

**Comment by geek** [comment]
@gergoerdosi good point, right now we are hard coding `test` and `node_modules` (https://github.com/hapijs/lab/blob/master/lib/cli.js#L22) into the coverage exclusion.  We can enhance the CLI to include exclusions... or maybe go the route of an npmrc file that specifies the exclusions

**Comment by gergoerdosi** [comment]
@geek Now looking at the source code, I think I would be more interested in the `coveragePath` setting. Instead of specifying all files to exclude (`test`, `node_modules`, `index.js`, `server.js`, `config/development.js`, `config/production.js`, etc), it would be easier to just set `coveragePath` to `lib/`. At least in my case. Or is `coveragePath` for something else?

**Comment by geek** [comment]
@gergoerdosi makes more sense :)

I am happy to accept a PR for this.
