### ISSUE TITLE
Mongoose timeout issue

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/lab#422]
I have a test which uses Mongoose and it times out when an expectation fails. It passes the first `expect()`, but then timeouts on the second one. Here is a sample code to reproduce it (run `npm install mongoose lab code` to set it up):

```
var Code = require('code');
var Lab = require('lab');
var Mongoose = require('mongoose');

var lab = exports.lab = Lab.script();
var expect = Code.expect;

lab.before(function (done) {
  var dsn = 'mongodb://127.0.0.1:27017/test';
  Mongoose.connect(dsn, done);
});

lab.describe('Test', function () {
  lab.it('does not timeout', function (done) {
    var UserSchema = new Mongoose.Schema({
      name: String
    });

    var User = Mongoose.model('User', UserSchema);

    User.create({ name: 'Test User' }, function (err, user) {
      console.log('BEFORE');                   // PASSES
      expect(true).to.equal(true);             // PASSES
      console.log('BETWEEN');                  // PASSES
      expect(true).to.equal(false);            // STOPS HERE
      console.log('AFTER');

      done();
    });
  });
});
```

The output is:

```
$ node ./node_modules/.bin/lab -a code -v
BEFORE
BETWEEN
Test
  ✖1) does not timeout


Failed tests:

  1) Test does not timeout:

      Timed out (2000ms) - Test does not timeout
```

For some reason I'm able to reproduce this only with Mongoose. If I use a simple async function, then `expect()` works. Does anybody have an idea what causes this issue?

```
$ node -v
v0.12.7
$ npm -v
2.11.3
```

**Comment by geek** [comment]
Does it still timeout if you extend the timeout period with the `-m` argument?

**Comment by gergoerdosi** [comment]
Yes, it does. I added `{ timeout: 10000 }` to the test but it still timed out. Also, please note that it's not the callback which times out because the first `expect()` call is reached immediately, see `console.log()`s.

**Comment by gergoerdosi** [comment]
This looks like an issue with Mongoose. The code above works with Mongoose 3, but not with Mongoose 4. My guess is that the second `expect()` throws, but Mongoose somehow catches that error, so Lab receives nothing.

Probably related to https://github.com/Automattic/mongoose/issues/3222.

**Comment by geek** [comment]
@gergoerdosi thanks for identifying the issue, glad it wasn't in lab :)
