### ISSUE TITLE
Alienating language in README

### ISSUE THREAD

**Issue by anandthakker** [hapijs/lab#426]
> Change or remove this option if you just cannot be bothered with producing quality code.

Even though I actually agree with (some version of) the underlying idea about the value of test coverage, I think this sentence is pretty alienating.

**Comment by jaw187** [comment]
Who is alienated by this statement?

**Comment by geek** [comment]
@anandthakker any suggestions for alternate phrasing?

**Comment by hueniverse** [comment]
I don't remember if I wrote it or not, but it is clearly meant as a joke.

**Comment by anandthakker** [comment]
@hueninverse Ah--somehow it really didn't scan that way to me--maybe because the rest of the documentation is pretty matter of fact; or maybe because there are enough people hanging around on GitHub who *actually* behave so superior and obnoxious, so that it's hard to distinguish a joke like this from real live snobbery. That said, I'm sorry that I didn't offer the benefit of the doubt in my initial comment. 

> any suggestions for alternative phrasing?

@geek I guess the simplest would be to remove it?
