### ISSUE TITLE
How to launch tests programmatically?

### ISSUE THREAD

**Issue by Wenzil** [hapijs/lab#430]
I want to debug my tests using the debugger in Visual Studio Code, but to do so I need my tests to be ran from a node script, i.e. I can't run them via the `lab` cli.

I tried to simply `require` my test scripts but that doesn't behave well. Anyone has a solution?

**Comment by geek** [comment]
You can run the tests using `node node_modules/.bin/lab`

**Comment by Wenzil** [comment]
Cool, I'll try that and let you know how it goes

**Comment by Wenzil** [comment]
Nice, it works flawlessly. Thanks a bunch :)

**Comment by jtlapp** [comment]
This no longer works in VSC 1.6. I was able to get the following configuration to work:

```javascript
{
    "type": "node",
    "request": "launch",
    "name": "Debug a lab test",
    "cwd": "${workspaceRoot}",
    "program": "${workspaceRoot}/node_modules/.bin/lab",
    "args": [
        "./tests/apis", // for example
        "--timeout", "0",
        "--id", "12" // for example
    ]
}
```
