### ISSUE TITLE
Rule for empty for loop inc is wrong

### ISSUE THREAD

**Issue by hueniverse** [hapijs/lab#435]
```
Linting results:
    lib/index.js:
        Line 47: semi-spacing - Missing whitespace after semicolon.
        Line 84: semi-spacing - Missing whitespace after semicolon.
```

Current code in nigel is correct.

**Comment by danielb2** [comment]
Looks like issue there is the trailing `;` before the closing parenthesis. 

Compare with line [68] for example

[68]: https://github.com/hapijs/nigel/blob/master/lib/index.js#L68

**Comment by AdriVanHoudt** [comment]
Either add a space behind the `;` (imo the best option, makes it clear that the iteration progress is done inside the loop not by a standard `i++`).
Or disable the 'there should be a space behind `;` rule' (by doing `"semi-spacing": [2, {"before": false, "after": false}]`.
Removing the `;` would result in a syntax error so that is not an option.

**Comment by danielb2** [comment]
> Removing the ; would result in a syntax error so that is not an option.

missed the number of arguments. 

The added space would look odd imo

**Comment by AdriVanHoudt** [comment]
it does look a little bit odd but it makes it instant clear that there is "i++" being done by the loof definition.
Maybe @cjihrig can add a custom rule to `eslint-plugin-hapi` that allows this in for loops?

**Comment by cjihrig** [comment]
I'll look into this.

**Comment by cjihrig** [comment]
This is purely an issue with the ESLint rule doing what we're telling it to do. We are using:

`'semi-spacing': [2, { 'before': false, 'after': true }],`

Meaning that we are enforcing a space after a semicolon when it is not at the end of a line. We should either disable the rule completely or add the extra spaces in the few places that it is required. I don't think this warrants its own rule.

**Comment by AdriVanHoudt** [comment]
unless you want to have it everywhere except this case...

**Comment by hueniverse** [comment]
This is a special case where `)` comes after the last `;`.

**Comment by cjihrig** [comment]
If it's a rare case, you can turn off the rule for that specific line, or just add the extra space. Short of that, we'll either have to disable the rule or write a custom one. Someone could also try opening an issue upstream to see if ESLint is interested in supporting that.
