### ISSUE TITLE
Document html coverage report source markup

### ISSUE THREAD

**Issue by skeggse** [hapijs/lab#439]
I'm new to lab, having spent some time with [istanbul](https://github.com/gotwarlost/istanbul). Istanbul's html coverage reporter annotates what branches and conditions have been visited, and includes tooltips that indicate things like "branch not covered" and "statement not covered." The colors that istanbul uses make it easy to understand what the tests aren't covering.

I'm not finding the same to be true for lab. Different parts of [isemail](https://github.com/hapijs/isemail) are being highlighted in grey-green and light-green, and don't include any explanatory text. They appear in seemingly the same contexts, but I can't get them to go away by adding what I think is the appropriate tests.

Could we document what the colors mean/add explanatory text in perhaps the form of a tooltip (title attribute) to make this clearer?

**Comment by geek** [comment]
@skeggse very good point.  Here is where the colors are determined at the moment: https://github.com/hapijs/lab/blob/master/lib/reporters/html/report.html#L314

**Comment by skeggse** [comment]
I found that, but I'm not sure what the different classes mean - what is a `.miss.false` vs a `.miss.true`?

**Comment by Marsup** [comment]
This means the condition was always either true or false, need both to have proper coverage.

**Comment by Marsup** [comment]
Not to waste anyone's time, I'm working on it currently with other features I'd want in.

**Comment by Marsup** [comment]
Closed by above PR.
