### ISSUE TITLE
Lint warning for unused variables except internals

### ISSUE THREAD

**Issue by hueniverse** [hapijs/lab#453]

**Comment by cjihrig** [comment]
I published v3.0.0 of `eslint-config-hapi`. I was about to make a PR to lab, but there are a lot of warnings. Most of them refer to unused function arguments, for example - https://github.com/hapijs/lab/blob/master/lib/reporters/lcov.js#L23

**Comment by geek** [comment]
I think unused function arguments should be excluded from the check.  While an unused argument can be removed, they also help document the expected arguments.

**Comment by hueniverse** [comment]
I agree. Unused function arguments are not a problem but the right way to write code. If you implement a callback you should include all the arguments expected as a way to document the interface.
