### ISSUE TITLE
Add "Pending Tests"

### ISSUE THREAD

**Issue by gajjargaurav** [hapijs/lab#458]
Mocha provides Pending Tests which are really good for start defining acceptance criteria as tests and implement them later on. https://mochajs.org/#pending-tests

It would be great to have such a feature in lab as currently in lab we will have to skip those tests.

**Comment by danielb2** [comment]
This is already provided via the following syntax
``` javascript
it('has a pending test');
```
or 

``` 
it('has a pending test', { skip: true }, function (done) {
   done();
});
```
