### ISSUE TITLE
`/* `$lab:coverage:(off|on)$` */` disables coverage for a whole module

### ISSUE THREAD

**Issue by eriktrom** [hapijs/lab#459]
Howdy folks - when using the following:

```js
/* $lab:coverage:off$ */
import Path from 'path'
import Something from './somewhere'
/* $lab:coverage:on$ */


// do lots of things that currently have poor test coverage
```

I get 100% coverage for the entire module(in both console and html output). When I remove the `$lab:coverage:(off|on)$` comments, I get what I expect. 

**This seems to indicate that `/* $lab:coverage:on$ */` does not turn coverage back on for the remaining lines.**

(Ancillary note: `import Blah from 'blah'` causes the babel compiled output to fail coverage for the ternary statement it does for imports , that's a separate issue(but it does exist, fyi). Putting off/on comments around the imports seemed like a way forward for now, but then I hit this wall.)

I am using the following tools/versions:

node/v4.1.1
babel/5.8.23 (babel-core 5.8.25)
lab/6.1.0

Note: issue also occurred on lab 5.x.x, I just upgraded to 6.x before making this issue(w/ same result)
Note: I have not tried on older versions of node

My babel transform function (is mostly copied from the README with some slight alterations):

```js
let Babel = require('babel-core');

module.exports = [{
  ext: '.js',
  transform: function(content, filename) {

    let isNodeModules = filename.split('/').indexOf('node_modules') === 0;
    let isTest = filename.split('/').indexOf('test') === 0;
    let isLib = filename.split('/').indexOf('lib') === 0;

    // Make sure to only transform your code or the dependencies you want
    if (isTest || isLib) {
      let result = Babel.transform(content, {
        sourceMap: 'inline',
        filename: filename,
        sourceFileName: filename
      });
      return result.code;
    } else if (isNodeModules) {
      return content;
    }

    throw Error('babel transform has had some issues, content %o, filename %s', content, filename);
  }
}];
```

The lab cli command I run is:

```
./node_modules/lab/bin/lab --sourcemaps --debug --transform ./test/babel-transform.js -a code -t 100 -Lv -r console -o stdout -r html -o coverage.html ./test/unit
```

Word of warning: Babel and Lab are both new toolz I am playing with, forgive me if there is user fault involved, although I tried to make sure this was actually an issue before submitting one.

Let me know if more information is needed. Tell me where to look and I'll help fix it :)

Thanks and cheers!

**Comment by Marsup** [comment]
Can we see the transpiled code ?

**Comment by eriktrom** [comment]
Sure here's the html reporter output: http://eriktrom.s3.amazonaws.com/coverage.html

Let me know if you'd like to see anything else, like a fresh git init of the source code for public consumption.

**Comment by eriktrom** [comment]
Also, here's the html coverage output with the coverage off/on blocks in use(for comparison): http://eriktrom.s3.amazonaws.com/coverage-with-on-off-comments.html

**Comment by Marsup** [comment]
Would help to have the full code to debug on our side yes.

**Comment by eriktrom** [comment]
Np - I'll make a repo by the morning - went a little buck wild with log stash one day. Have no idea what keys went into git. Will wipe and share. Thanks BTW. Really dig ur guys frameworks.

**Comment by eriktrom** [comment]
@Marsup - https://github.com/eriktrom/xyz

I've committed the `dist` directory so hopefully you won't have to run the app but if you do, it should just work (or actually give you instructions). Let me know of any problems.

**Comment by PhilWaldmann** [comment]
are there any updates for that issue?

**Comment by Marsup** [comment]
Sorry, forgot that one. Transpilation seems to remove comments, of course that won't work. Never had any issue with pure node so my guess is the problem will always be in your build tools.

**Comment by willin** [comment]
![qq20160415-0 2x](https://cloud.githubusercontent.com/assets/1890238/14554807/ce88bfe6-0321-11e6-85fd-cd2ddb864eac.png)

v1.1.1

coverage always 100%

**Comment by jedireza** [comment]
I think I found out why this may be happening. Checkout PR #620 for more details.

**Comment by jedireza** [comment]
@eriktrom `lab@11.x` was released that included #622, which I think resolves this. Would you be willing to try it out and see?

**Comment by eriktrom** [comment]
@jedireza - from a different project, but exact same setup:

```
./node_modules/.bin/lab --version
11.0.0
```

![image](https://cloud.githubusercontent.com/assets/830120/17692606/7658bfa4-634f-11e6-8f71-e1129b38afdf.png)

For reference, the top of the file looks like:

```js
/* $lab:coverage:off$ */
import Model from './';
import _ from 'lodash';
import Promise from 'bluebird';
/* $lab:coverage:on$ */

export default class Listing extends Model {
  constructor() {
    super(...arguments);
  }
  // ...snip
```

Note that this output is the same with and without the `/* $lab:coverage:off$ */` - aka, the 'off' part is still missing from the top of the coverage file, but the 'on' part is there.

If there is good reason too, I can test the old project linked above, but I'm pretty sure everything related to this issue is the same. (except the new version of lab of course)

Thanks a bunch @jedireza and everyone who put some time into debugging this.

Let me know if there's anything more I can do that would help.

**Comment by jedireza** [comment]
@eriktrom I'm using `babel-core@6.13.2` and defining [auxiliary comments](https://babeljs.io/docs/usage/options/) to wrap non user generated code.

Try updating your transform to something like:

```js
let result = Babel.transform(content, {
    sourceMap: 'inline',
    filename: filename,
    sourceFileName: filename,
    auxiliaryCommentBefore: '$lab:coverage:off$', // the magic sauce
    auxiliaryCommentAfter: '$lab:coverage:on$' // ;)
});
```

Using the auxiliary comment options, I tried the same thing you described above locally and it seems to be working as expected.

 - My demo branch: https://github.com/jedireza/lab-es6/tree/lab-459

![screenshot from 2016-08-16 08-57-45](https://cloud.githubusercontent.com/assets/979929/17706098/8cb5c07c-638f-11e6-9a26-5c0ed920a036.png)

**Comment by eriktrom** [comment]
@jedireza - that is some very sweet magic sauce - works even without the coverage on/off comments now for me - just straight es6 - your the man, thanks for all the work - i saw your project a while back and was hoping u figure it out :)  Sweet!
