### ISSUE TITLE
File Name Coverage Issue

### ISSUE THREAD

**Issue by arb** [hapijs/lab#461]
If you try to `require` a file that has the word "test" in the file, coverage will not be run on that file. 

```
|> project
|--index.js
|--test-server.js
|>  test
|------index.js
```

I think the problem is [here](https://github.com/hapijs/lab/blob/master/lib/coverage.js#L51). I *think* the end of that regex should read `(?!test\/|node_modules\/)` by default.

**Comment by Marsup** [comment]
Are you sure just a $ at the end wouldn't be enough ?

**Comment by arb** [comment]
Perhaps. You know what they say about regular expressions; if you solve a problem with a regular expression, now you've got two problems.
