### ISSUE TITLE
Coverage identifies babel transformed react code as uncovered

### ISSUE THREAD

**Issue by davidhouweling** [hapijs/lab#464]
Given a react component written in ES2015, i've added a babel transformer. But once i run the code coverage, the parts that babel injects to allow the react component to work causes the coverage runner to report on these lines (5 of them) as not being covered.

**Comment by Marsup** [comment]
Not enough information, no code, no way to reproduce.

**Comment by ldesplat** [comment]
This is when you need to ask yourself the question, should these lines actually be covered? After all, this is how the final code looks like.

If you decide that it is not necessary or just can't find a way to cover those lines see [nlf/lab-babel](https://github.com/nlf/lab-babel) repository and nlf/lab-babel#4 . This will use some of babel's features to insert comments in between the auxiliary code inserted by babel and tell lab to turn coverage off for those lines.

**Comment by davidhouweling** [comment]
@Marsup sorry for not including a code sample. Just thought that someone would have come across this already and so thought I'd chance it first.

@ldesplat You are indeed correct, that I don't think those lines need coverage. And what is in that pull request definitely seems like what I was looking for. I haven't yet tried it but it looks promising. I'll let you know if it is successful later in the week.

**Comment by davidhouweling** [comment]
@ldesplat your solution did fix the code coverage. Thanks.
