### ISSUE TITLE
es6 does weird things

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/lab#472]
see https://github.com/hapijs/hoek/pull/165
github reports ok, build on 0.10 failed and the one on 4 reports ok but actually crashed.
The crash on 4 is reproducible by just running the tests locally if that helps anyone

**Comment by geek** [comment]
@AdriVanHoudt is this still an issue?

**Comment by AdriVanHoudt** [comment]
@hueniverse merged it and the latests builds seem ok and local also ok so nope
