### ISSUE TITLE
consider testing arg passed to done is an error object

### ISSUE THREAD

**Issue by nlf** [hapijs/lab#475]
currently as the documentation states

> The test passes if done() is called once before the timeout, no exception thrown, and no arguments are passed to done()

I feel like this should be slightly more restrictive and also require that an argument passed to `done()` be an instance of Error.

As it is currently, if you pass a non-Error object to done, the reporter prints nothing. For example:

```js
var lab = exports.lab = require('lab').script();

lab.test('shows garbage', function (done) {

  done('this isn\'t an error');
});
```

displays the following:

![error](https://cldup.com/NAVDklIStD-2000x2000.png)

which is completely unhelpful. we should either print whatever was passed, or only error if the argument is an error object.

**Comment by devinivy** [comment]
Perhaps it could error if the argument is not an error object in a way that insists that an error object be passed.

**Comment by AdriVanHoudt** [comment]
To not suddenly let builds pass that use this I would like @devinivy said, error with a message to use an error and maybe also print what was passed

**Comment by geek** [comment]
@AdriVanHoudt and @devinivy sounds like a good plan to me

**Comment by geek** [comment]
Fixed by https://github.com/hapijs/lab/commit/35cf424c65bade6e40f221716a33b886292235dc
