### ISSUE TITLE
ES6 linting rules

### ISSUE THREAD

**Issue by cjihrig** [hapijs/lab#476]
@geek I'm in the process of putting together a linting update, per https://github.com/hapijs/contrib/issues/58. You can track the progress [here](https://github.com/continuationlabs/eslint-config-hapi/milestones/5.0.0). Some of the work requires custom rules, which are not done yet. The transition has already started in hapi, and I know you **just** bumped the major of lab. My question is, how do you want to handle the incorporation these updates into lab?

cc: @hueniverse

**Comment by hueniverse** [comment]
This should happen today if possible so that as people upgrade to new lab they get help with some of the new style changes.

**Comment by geek** [comment]
@cjihrig as @hueniverse stated, I will bump the minor for 7 to get these changes in for people upgrading to 7.
