### ISSUE TITLE
Update hapijs/items to 2.0.0 from 1.1.1

### ISSUE THREAD

**Issue by hueniverse** [hapijs/lab#479]

**Comment by AdriVanHoudt** [comment]
missed a space in the title ;)

**Comment by geek** [comment]
@hueniverse thoughts on switching to https://www.npmjs.com/package/fastparallel  which is faster than items and also a v2 ?

**Comment by hueniverse** [comment]
Hmm. For lab I really don't care. This module already comes with a gigantic pile of crap. For hapi I need to study it closer. When we first wrote items it was equal in performance to async. Looks like it got slower now (or others got faster). If the code looks good, I'll see if we should borrow the code we need or just switch over.

**Comment by devinivy** [comment]
Would we continue to use items for serial calls, or move to fastserial?  I personally really like the simplicity of the implementation/API of items, and would prefer to adapt it slightly if we could get _comparable_ speed.
