### ISSUE TITLE
eslint incorrectly extends higher level configs

### ISSUE THREAD

**Issue by nlf** [hapijs/lab#488]
see https://github.com/hapijs/qs/issues/136 for details

**Comment by cjihrig** [comment]
Lab passes the `useEslintrc` option to ESLint. This allows users to use something other than the hapi rules. A side effect of that is that ESLint traverses all the way to the root of the file system, creating a cascaded config (see http://eslint.org/docs/user-guide/configuring.html). This seems like an expected consequence of that. Setting `useEslintrc` to `false` in `lib/linters/eslint/index.js` prevents this behavior.

**Comment by geek** [comment]
Its going to work like Colin describes.  I don't see a way around that behavior in lab itself that won't break things...
