### ISSUE TITLE
Exception dumped on console when testing for error conditions

### ISSUE THREAD

**Issue by toamitkumar** [hapijs/lab#489]
Hi,

Is there a way to suppress the the errors shown on console for testing exceptions in code.
For eg: when I run this [test](https://gist.github.com/toamitkumar/d48f6526a5ce16f2b0c0), although the test passes, I see an exception dumped to console. 
Makes me wonder if the tests passed, however it has passed

suggestion ?

**Comment by Marsup** [comment]
What exception? More details please.

**Comment by AdriVanHoudt** [comment]
I have test that I expect to throw, I just ignore them, not sure if it is possible to not print throws in console

**Comment by toamitkumar** [comment]
Something like:

```
Debug: internal, implementation, error 
    Error: Internal Server Error
```

this is thrown from the code for errors which is being tested in the app

**Comment by toamitkumar** [comment]
Went through Hapi `server` module implementation and found `debug` flag that has to set to `false`.

```
var server = new Hapi.Server({ debug: false });
```

this doesn't dump 500 exceptions captured by `domain` object.
Thanks for your response guys.

**Comment by AdriVanHoudt** [comment]
oh nice :+1:
