### ISSUE TITLE
Coverage reporting does not support parsing ES6 objectLiteralComputedProperties

### ISSUE THREAD

**Issue by alobodig** [hapijs/lab#491]
The configuration options object passed to espree (in [lib/coverage.js](https://github.com/hapijs/lab/blob/master/lib/coverage.js#L213)) does not have `objectLiteralComputedProperties` set to true, but does have some other ES6 parsing options set. Would it be possible to provide a way to set other parsing options from outside of lab?

**Comment by geek** [comment]
I am open to the change to pass options in, for now, feel free to create a PR to enable `objectLiteralComputedProperties`

**Comment by jedireza** [comment]
This can be closed right?

**Comment by alobodig** [comment]
Yes, it can. Thanks.
