### ISSUE TITLE
Diff colors render diff text unreadable

### ISSUE THREAD

**Issue by ravinggenius** [hapijs/lab#493]
When displaying a diff, the background colors are set. On my system (I'm using Solarized Light), the text color is already a not dark grey, so the text in the diff (arguably the most important part) is very difficult to read. Please explicitly set the foreground color anytime the background color is set. I've included a screenshot to demonstrate:

<img width="275" alt="screen shot 2015-11-17 at 21 10 52" src="https://cloud.githubusercontent.com/assets/21517/11383275/1ec4e646-92d5-11e5-8a5f-1a797149dbb7.png">

**Comment by Marsup** [comment]
This looks like an easy one to fix, maybe a contributor could do it ?

**Comment by alobodig** [comment]
For what it's worth, I use a dark color scheme and it's also difficult to read. I think setting the text to bright white whenever the background is set would fix readability in both situations.
![screen shot 2015-11-30 at 1 58 44 pm](https://cloud.githubusercontent.com/assets/1733093/11481720/16e20d86-976d-11e5-876a-9bb70fb74e9f.png)

**Comment by thephilip** [comment]
What text color would everyone prefer?  Is black okay?  I'm new to contributing in general, but I would like to take a stab at this if that's okay with everyone else.  Might take me a couple of days because of work being busy.

**Comment by alobodig** [comment]
Black is okay with me.

**Comment by thephilip** [comment]
Working on it now...

**Comment by thephilip** [comment]
Does this look okay?
![actual-expected](https://cloud.githubusercontent.com/assets/13875805/11634346/e0c10998-9cdd-11e5-81f8-dab8051fb64a.PNG)

I was able to test the colors by passing two new color codes into internals.colors.  Only problems are that the colors module is a bit finicky with multiple colors (specifically, I've had issues trying to implement the new colors with the built-in 'setTheme' method.  Also, I had to pass the new colors as a string but can re-factor internals.colors to accept and array of more than one value, but I would like to know what you all think.  I know passing a string in there is kinda hacky, but [again] I'm pretty new to this (sorry!).

```
    const codes = {
        'black': 0,
        'gray': 90,
        'red': 31,
        'green': 32,
        'yellow': 33,
        'magenta': 35,
        'redBg': 41,
        'greenBg': 42,
        'redBlack': '30;41',
        'greenBlack': '30;42'
    };
```

**Comment by ravinggenius** [comment]
I think it's better, but the `actual` is still difficult to read. `expected` is okay though.

**Comment by thephilip** [comment]
@ravinggenius, you're right.  I think white looks better on the red...what do you think?
![fail](https://cloud.githubusercontent.com/assets/13875805/11641348/d81a41b0-9d05-11e5-801a-415ee1cdc689.PNG)

**Comment by ravinggenius** [comment]
White on red is better. Can you test this with a light-colored terminal theme. I'm using Solarized Light in the screenshot above.

**Comment by thephilip** [comment]
This is what it looks like on a white background:
![lightbg](https://cloud.githubusercontent.com/assets/13875805/11673870/14fc3f2c-9dea-11e5-8d0b-7d1f5f07ad68.png)

**Comment by thephilip** [comment]
I guess using ANSI escape code 37 (30+7) in place of 255 works for xterm, cmd, & cygwin.  I'll update the pull request with the commit either tonight or tomorrow.  Hopefully it works in Terminal.app, but I have no way to test.

**Comment by alobodig** [comment]
Looks great in Terminal.app. 

<img width="172" alt="screen shot 2015-12-09 at 10 14 45 am" src="https://cloud.githubusercontent.com/assets/1733093/11689018/da5c6436-9e5d-11e5-9a6a-4a0c180187a6.png">

**Comment by thephilip** [comment]
Thanks for testing, @alobodig .
