### ISSUE TITLE
Coverage analysis not catching some files.

### ISSUE THREAD

**Issue by rutaihwa** [hapijs/lab#494]
Im experiencing something strange in some of my repos, when i run tests on them in the local env I get 100% coverage even though there is some files not included. But when I push them up, travis catches the lack of coverage in the repo. Here is [ travis build log ](https://travis-ci.org/rutaihwa/babu-barebones/jobs/93738841).

**Comment by geek** [comment]
Are you running the same node version and same dependency versions as travis?

**Comment by rutaihwa** [comment]
Mhh, not quite Im running `npm` local - 2.14.7  and travis - 2.14.2, `nvm` - local 0.26.0 and travis - 0.23.3, `node` local - 4.2.2 and travis - 4.0.0. Could these make be the issue?

**Comment by geek** [comment]
@rutaihwa is this still an issue?
