### ISSUE TITLE
ESLint version doesn't like template strings

### ISSUE THREAD

**Issue by lokenx** [hapijs/lab#497]
Using Lab 7.3.0 and simple `.eslintrc` file below:
```
{
    "extends": "./node_modules/lab/lib/linters/eslint/.eslintrc"
}
```

It freaks out when using Template Strings (part of ES6 features on by [default](https://nodejs.org/en/docs/es6/)) with following error:
```
current = candidates.length;
                    ^
TypeError: Cannot read property 'length' of undefined
    at Controller.traverse (/Users/mdelport/Development/hapijs/fez/node_modules/estraverse/estraverse.js:406:37)
```

Found reference to it in [this](https://github.com/eslint/eslint/issues/4259#issuecomment-152802636) issue. Manually changing the ESLint dependency in the Lab `package.json` to `"eslint": "1.10.x",` fixed error and linting/testing continued as normal.

Not sure if you want to upgrade the ESLint version or if there's a better way to handle it (new to Hapi/Lab/ESLint).

**Comment by cjihrig** [comment]
Please open a PR. We should aim to stay up to date with ESLint when possible.

**Comment by lokenx** [comment]
OK this makes no sense to me. @geek updated the ESLint to `1.10.x` a few days ago in 4e21e911. However when installing from NPM I'm getting `1.8.x` even though I'm on Lab `7.3.0`.

I did a `npm clean cache` to be sure I didn't have an old copy lying around or anything. I'm guessing changes have been made to GitHub repo but not published to NPM, even though version number's the same?

**Comment by cjihrig** [comment]
Ah, yea it looks like the ESLint update was 10 days ago, but the last npm publish was 3 weeks ago. So hopefully the next version will fix your problem.

**Comment by lokenx** [comment]
Yeah once it's pushed to NPM I'd get the new updates, I've manually made changes until it gets pushed to NPM.
