### ISSUE TITLE
Opening a wiki page

### ISSUE THREAD

**Issue by AdrieanKhisbe** [hapijs/lab#501]
Suggestion to open a wiki on the repo.

The main idea, would be to have a page that point to the release note, 
so that there are easy to reach for :)

cf: https://github.com/hapijs/hapi/wiki

**Comment by Marsup** [comment]
What's wrong with the issues and milestones way ?

**Comment by AdrieanKhisbe** [comment]
Nothing is wrong.
I'm just suggestion to add a pointer to them so that you don't have to research them would be more than helpful.

again, cf: https://github.com/hapijs/hapi/wiki

**Comment by Marsup** [comment]
It's one more thing to maintain, and one that cannot be automated, not sure it brings much value compared to [that](https://github.com/hapijs/lab/issues?q=is%3Aissue+is%3Aclosed+label%3A%22release+notes%22).

**Comment by AdrieanKhisbe** [comment]
come on, adding one line per major version *c'est pas la mort...*

But indeed the dynamic like is a good alternative has long you don't have to type it.
Then it could be simply added to the README instead.

what do you thing?

**Comment by Marsup** [comment]
My thoughts exactly, I was thinking about a whole section with a few links for other things I had in mind. But this probably concerns all the org repos so this should be debated in hapijs/contrib.

**Comment by AdrieanKhisbe** [comment]
Indeed.
Should we move the discussion there? :)

**Comment by Marsup** [comment]
Probably yes.

**Comment by geek** [comment]
I really want to add a page under hapijs for lab to provide lengthier documentation

**Comment by AdrieanKhisbe** [comment]
@geek : I concour ! :+1: 
(and think would be usefull to do it for *Joi* too (It's implied for *Code* *Lab*'s little brother)

**Comment by Marsup** [comment]
Whatever but no wiki please.
