### ISSUE TITLE
Add mention on README to go for 6.2.0 for node 0.10

### ISSUE THREAD

**Issue by AdrieanKhisbe** [hapijs/lab#502]
New user of lab that have to support 0.10.0, 
might not know to use 6.2.0.

`npm install --save-dev lab`, wont say anything.

Then it should be usefull to appear on the README.

(If there is an agreement, I can take care of the Fork&PR)

**Comment by Marsup** [comment]
Dunno what your versions are but you should enable at least some logging level.
```
npm WARN engine lab@8.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.41","npm":"1.4.29"})
npm WARN engine hoek@3.0.4: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.41","npm":"1.4.29"})
npm WARN engine items@2.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.41","npm":"1.4.29"})
```

**Comment by AdrieanKhisbe** [comment]
You do not get then it if you work on you dev environment with node 4.

It just appeared to me after the travis build:
cf
https://github.com/rjrodger/jsonic/pull/9
https://travis-ci.org/rjrodger/jsonic/builds/98336819

**Comment by Marsup** [comment]
I don't even know what to say to that. Devs are notorious for not reading the docs anyway, you wouldn't even have noticed, and your CI picked it up so everything is fine. If you're using a local environment that's different from your tests you'll have troubles anyway.

**Comment by AdrieanKhisbe** [comment]
some hapi plugin does for a similar need: https://github.com/toymachiner62/hapi-authorization.
and it's more than welcome :)

I might be dev, I read the doc ;)
Also, it's not suprising that they don't read doc, if they do not convey useful information :p
 :trollface: 

more seriously, for me a readme should contains all the information needed to start using a library without any fuss

I let you decide, I won't insist. :smiley:

**Comment by Marsup** [comment]
I think this should be solved elsewhere (ie. https://github.com/npm/npm/issues/3662). I'm not against documenting it but as @cjihrig said, that's something we'll drag with us until the end of times.

**Comment by AdrieanKhisbe** [comment]
nevermind
