### ISSUE TITLE
--coverage-exclude should support multiple paths

### ISSUE THREAD

**Issue by geek** [hapijs/lab#508]
Currently, the cli option only supports a single path, this is a bug and it should support multiple paths passed in as an array

**Comment by Marsup** [comment]
@geek I think it is, you just have to repeat the switch for each additional path.

**Comment by geek** [comment]
@Marsup ! you are correct, I will make the documentation clearer

**Comment by JimSangwine** [comment]
@geek Is this flag supported in .labrc? I have tried the following with no success:

`module.exports = {
  coverage: true,
  threshold: 69,
  'coverage-exclude': [
    'models',
    'config',
    'enums'
  ]
}`

`module.exports = {
  coverage: true,
  threshold: 69,
  coverageExclude: [
    'models',
    'config',
    'enums'
  ]
}`

**Comment by geek** [comment]
@JimSangwine `coverage-exclude` is supported in the rc file. Are `models, config, enums` all folders that you want excluded? 

At the moment the coverage test regex will look something like the following given your config:

```
^\/Users\/jim\/project\/(?!node_modules\/|test\/|models\/|config\/|enums\/)
```

so `'/Users/jim/project/models/index.js'` will be excluded but `'/Users/jim/project/models.js'` won't

**Comment by JimSangwine** [comment]
Ah, thanks @geek - I didn't realise it would take a regex.

**Comment by geek** [comment]
@JimSangwine here is the code that generates the regex: https://github.com/hapijs/lab/blob/master/lib/coverage.js#L50-L57

**Comment by JimSangwine** [comment]
Ah! So I don't pass my own regex, it does accept an array of strings.

I tested again and found that the 'coverage-exclude' form works but 'coverageExclude' does not. I must have had a typo or something when I was testing originally.

For other anyone else with this question, this works:

**.labrc.js**
```
module.exports = {
  coverage: true,
  threshold: 69,
  'coverage-exclude': [
    'models',
    'config',
    'enums'
  ]
}
```

Thanks for the clarification @geek
