### ISSUE TITLE
lab 8.2.0 not playing nice with node 0.12

### ISSUE THREAD

**Issue by rjrodger** [hapijs/lab#517]
https://travis-ci.org/senecajs/gate-executor/jobs/104418467

**Comment by gergoerdosi** [comment]
https://github.com/hapijs/lab/blob/v8.2.0/package.json#L11

**Comment by cjihrig** [comment]
Across the hapi ecosystem, a major version bump was made, which dropped support for Node < 4. In lab's case, I believe that was the jump from 6 to 7.
