### ISSUE TITLE
Support for glob patterns

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/lab#518]
I have tests in different folders and they are all in `test` folders but do not have suffixes or anything so currently I cannot macht them. And `-P` only allows for file name matching.
Am I missing something? Otherwise glob patters would solve the problem.

**Comment by geek** [comment]
Why not add a suffix, or do a `blah.test.js` to make it able to be recognized with the `-P` option?

**Comment by AdriVanHoudt** [comment]
yeah was thinking of that, but if it is not to hard to implement it would be a nice to have

**Comment by thebergamo** [comment]
I can't using different folders in my tests, lab just load files in `test` folder? I try figure the -P, but looking the source code, the -P only looks for `test` path. :/

**Comment by geek** [comment]
@thebergamo you can use a different folder, just pass it in to lab:

`lab my_test_folder`

You can also use -P to search for certain files in that folder:

`lab my_test_folder -P spec`
