### ISSUE TITLE
Support promises in tests and setup / teardown

### ISSUE THREAD

**Issue by rluba** [hapijs/lab#536]
I know that this had been done in #342 and undone in #419 due to the complexity and overhead — but I believe that it can be implemented far simpler than #342 and without a performance penalty for those that don’t want to use promises.

It would remove a lot of error-prone boilerplate code for those of us that _do_ want to use promises.

Currently, I have to write:

```JavaScript

it('some test', (done) => {

    someAsyncCode()
        .then(() => {
             someAssertion();
             done();
        })
        .catch(done);
});
```

instead of just

```JavaScript

it('some test', () => {

    return someAsyncCode()
        .then(() => {
             someAssertion();
        });
});
```

If you are open to supporting the latter, I can provide a PR that will add this feature.

**Comment by Marsup** [comment]
:+1: I also think this doesn't need to be that complex but since I don't have time to pick it up, you should, @geek seems open to that.

**Comment by rluba** [comment]
Here you go!
