### ISSUE TITLE
Unable to run multiple test files after upgrading to v10.0.0

### ISSUE THREAD

**Issue by alnjxn** [hapijs/lab#539]
It appears that this commit ac20bdaee8b2bda5b0c7c208ee2d24f715037fb1 introduced a bug that is preventing me from running multiple tests from the test folder. Runs as expected on v9.1.0. I encounter the bug as early as v10.0.0, and the lab command fails with the following error:

```
/Users/a.jackson/.nodenv/versions/4.3.1/lib/node_modules/lab/lib/runner.js:139
            if (onlyNode.test) {
                        ^

TypeError: Cannot read property 'test' of undefined
    at /Users/a.jackson/.nodenv/versions/4.3.1/lib/node_modules/lab/lib/runner.js:139:25
    at Array.map (native)
    at Object.exports.report.exports.execute.onlyNodes [as execute] (/Users/a.jackson/.nodenv/versions/4.3.1/lib/node_modules/lab/lib/runner.js:137:33)
    at Object.next [as notebook] (/Users/a.jackson/.nodenv/versions/4.3.1/lib/node_modules/lab/lib/runner.js:67:17)
    at Function.exports.parallel.execute (/Users/a.jackson/.nodenv/versions/4.3.1/lib/node_modules/lab/node_modules/items/lib/index.js:113:23)
    at Object.exports.report.executeScripts [as report] (/Users/a.jackson/.nodenv/versions/4.3.1/lib/node_modules/lab/lib/runner.js:97:20)
    at Object.exports.run (/Users/a.jackson/.nodenv/versions/4.3.1/lib/node_modules/lab/lib/cli.js:52:19)
    at Object.<anonymous> (/Users/a.jackson/.nodenv/versions/4.3.1/lib/node_modules/lab/bin/lab:5:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
```

The scenario occurs when running more than one test from the /test folder. I am using the Code assertion library in my tests. Here are the two tests in the folder. When only one test is in the folder the test runs. Adding the second test file causes the command to fail. 

**test/index.js**
```js
'use strict';

const Hapi = require('hapi');
const Code = require('code');
const Lab = require('lab');
const App = require('../src/server');
const Composer = require('./manifest');

const lab = exports.lab = Lab.script();
const before = lab.before;
const after = lab.after;
const describe = lab.describe;
const it = lab.it;
const expect = Code.expect;

let Server = {};

describe('/index', () => {

  before((done) => {

    App.init(Composer.manifest, { relativeTo: __dirname + '../../src/' }, (err, server) => {

      expect(err).to.not.exist();
      expect(server).to.be.instanceOf(Hapi.Server);

      Server = server;
      done();
    });
  });

  it('should return api version', (done) => {

    Server.inject({
      method: 'GET',
      url: '/'
    }, (response) => {

      expect(response.statusCode).to.equal(200);
      expect(response.result.api.version).to.equal(1);
      done();
    });
  });

  after((done) => {

    Server.stop(done);
  });
});
```

**test/user.js**
```js
'use strict';

const Hapi = require('hapi');
const Code = require('code');
const Lab = require('lab');
const App = require('../src/server');
const Composer = require('./manifest');

const lab = exports.lab = Lab.script();
const before = lab.before;
const after = lab.after;
const describe = lab.describe;
const it = lab.it;
const expect = Code.expect;

let Server = {};

describe('/users', () => {

  before((done) => {

    App.init(Composer.manifest, { relativeTo: __dirname + '../../src/' }, (err, server) => {

      expect(err).to.not.exist();
      expect(server).to.be.instanceOf(Hapi.Server);

      Server = server;
      done();
    });
  });

  it('should return a list of users', (done) => {

    Server.inject({
      method: 'GET',
      url: '/api/v1/users'
    }, (response) => {

      expect(response.statusCode).to.equal(200);
      expect(response.result.users).to.be.an.array();
      expect(response.result.users.length).to.be.above(1);
      done();
    });
  });

  after((done) => {

    Server.stop(done);
  });
});
```

**Comment by geek** [comment]
@alnjxn I added a test to try and reproduce the issue, see https://github.com/hapijs/lab/commit/d6e3b959adb6e38b2641b8dd0938e634a9d4ad7f

How are you executing the tests, whats the command you are using?

**Comment by alnjxn** [comment]
@geek I am running `lab -l -v`. does the assertion library have to be specified explicitly at runtime?

**Comment by geek** [comment]
@alnjxn you don't have to, but there are extra benefits from doing it, like detecting when an assertion isn't written fully, missing `()`:

```sh
lab -lv -a code
```

Can you try simplifying the code so that its not doing the `App.init` in the before and after.  You may want to cut those completely and do the setup and teardown in the test itself, and not have the `Server` available outside of your test.

**Comment by Marsup** [comment]
Aside from the tests styling, this seems to be going into code that should only happen if you're using `only`, are you ?

**Comment by alnjxn** [comment]
@geek thanks for the tip. I will try both using both suggestions and report back. I was trying to avoid having to write the server initialization code in every test.

@Marsup I am not using only. In fact I don't even call lab.test so I don't know why I am going into this section of the lab code, as you indicated.

Just to be clear though on two things.
1) The code in my tests is not being reached. I am fairly certain from the command line output that it fails before ever reaching my code
2) These tests do run on v9.1.0

Thanks for all the help. This is all a bit new to me.

**Comment by Marsup** [comment]
`it` is an alias to `lab.test`. Could you log `onlyNodes` just after it's created ?

**Comment by franciscogouveia** [comment]
@alnjxn Any updates? I'm having exactly the same case (including: not using `only` in any test, code not being reached and tests running well on older version of lab).

Running `lab -lv -a code` doesn't fix it.

**Comment by franciscogouveia** [comment]
@alnjxn Check if your installed `lab` package is really the latest. I had exactly the same issue as you described and I didn't realise that it wasn't using the latest major version of `lab`. Updating fixed the issue.

**Comment by wesleycho** [comment]
FWIW, I am seeing this issue upon upgrading from 9.1.0 to any version higher. `onlyNodes` seems to appear as an array of `undefined`s.

**Comment by geek** [comment]
@wesleycho thanks. Any examples on how to reproduce the issue?

**Comment by wesleycho** [comment]
Ah, nevermind, I figured out what happened with the work codebase - our "microservices" had some unexpected version mismatching with lab that was the culprit, nothing to see :)
