### ISSUE TITLE
shows “actual” “expected” (red, green) but doesn't show a red or green point of failure. 

### ISSUE THREAD

**Issue by fourq** [hapijs/lab#546]
original issue at `code` https://github.com/hapijs/code/issues/59 

seems to have a bug where a test fails and shows “actual” “expected” (red, green) but doesn't show a red or green point of failure

I see this mainly on large JSON `expect(…).to.deep.equal(…);`

```js
server.inject(options, (res) => {
    expect(res.result).to.deep.equal(fakeMappedForms);
    done();
});
```

`res.result` an `fakeMappedForms` can be found [here](https://gist.github.com/fourq/68dded1e9218f1dd83b3)

**Comment by fourq** [comment]
hmm, I do however see that it works if I use `JSON.stringify()`

```js
server.inject(options, (res) => {
    expect(res.statusCode).to.equal(200);
    expect(JSON.stringify(res.result)).to.deep.equal(JSON.stringify(fakeMappedForms));
    done();
});
```

**Comment by arb** [comment]
Do they have different prototypes? That'll cause `deep.equal` to be `false.

**Comment by geek** [comment]
@fourq is this still an issue?  Were you able to confirm if they have different prototypes?

**Comment by geek** [comment]
@fourq please reopen if this continues to be a problem.
