### ISSUE TITLE
Tests in nested experiment marked as successful when before handler in outer experiment fails

### ISSUE THREAD

**Issue by mbargiel** [hapijs/lab#549]
According to the conclusion of https://github.com/hapijs/lab/issues/103, tests should be marked as failed when the `before` function fails. I found a specific case where that isn't entirely true: tests are skipped, but they are reported as successful.

The specific case is the following:

outer experiment
-> before (fails)
-> test (marked as error, as expected)
-> nested experiment
--> test (incorrectly marked as successful; not run, as expected)

This only affects the `before` handler. Everything works as expected if `beforeEach` fails.

See attached test case showing the problematic behaviour. Faulty behaviour is made evident by running `lab test.txt -l -v`.

(Confirmed with lab versions: 8.2, 10.3)
[test.txt](https://github.com/hapijs/lab/files/186590/test.txt)

**Comment by mbargiel** [comment]
For convenience, see result output of lab test.txt -c -l -v attached in this file.
[results.txt](https://github.com/hapijs/lab/files/186596/results.txt)

**Comment by geek** [comment]
This was fixed, marking as resolved.
