### ISSUE TITLE
Threshold value

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/lab#550]
The documentation says "defaults to 100%", however it's not possible to use this option without a value:

> Invalid option: threshold missing value

If it is required to specify a value, then I don't see the point in mentioning that it defaults to 100% as it will be overwritten by the specified value anyway. Or am I missing something?

**Comment by geek** [comment]
It may be referring to the `-c` option, which does enforce 100% code coverage.

**Comment by cjihrig** [comment]
> -t, --threshold - minimum code test coverage percentage (sets -c), defaults to 100%.

Might be worth having a default for -t in the bossy setup.

**Comment by gergoerdosi** [comment]
Yes, we should either set a default, or remove the statement from the documentation. @geek: What do you think?

**Comment by gergoerdosi** [comment]
> sets the minimum code test coverage percentage to 100%

@geek: Thanks for looking into it, but not sure it got any clearer. `-t` alone doesn't set the minimum code coverage to 100%, but throws an error. And it also reads like this option doesn't accept a value.
