### ISSUE TITLE
Runtime errors silenced inside callback?

### ISSUE THREAD

**Issue by mikl** [hapijs/lab#553]
I might be doing something wrong, but I'm having problems with runtime errors getting squelched when inside a callback, like in this example:

    lab.experiment('basic zone with default options', () => {
      lab.test('zone without name property', (done) => {
        const zone = require('./fixtures/zone_no_name');

        validate(zone).then((result) => {
          console.log('rrr', result.errors.zone);
          result.app.not.existing += 1;
          Code.expect(result.errors.zone).to.be.array();
          Code.expect(result.errors.zone).to.have.length(1);
          done();
        });
      });
    });

The `console.log('rrr, […]);` does get called, but after that it just seems to freeze until timeout occurs:

~~~
Failed tests:

  3) basic zone with default options zone without name property:

      Timed out (2000ms) - basic zone with default options zone without name property
~~~

`result.app.not.existing += 1;` should throw a runtime error for trying to treat undefined as an object (result.app is undefined), but for some reason, this get lost.

Is this expected behaviour? If so, how do you handle things that use promises properly?

**Comment by gergoerdosi** [comment]
I think it's the expected behavior when you use `done`. Lab expects `done` to be called, but it is never called, because the promise swallows the thrown error and you don't have a catch block. There are two options:

- Catch the error:

```javascript
lab.experiment('basic zone with default options', () => {
  lab.test('zone without name property', (done) => {
    const zone = require('./fixtures/zone_no_name');

    validate(zone).then((result) => {
      console.log('rrr', result.errors.zone);
      result.app.not.existing += 1;
      Code.expect(result.errors.zone).to.be.array();
      Code.expect(result.errors.zone).to.have.length(1);
      done();
    }).catch((err) => {
      done(err);
    });
  });
});
```

- Return the promise instead of using `done` (requires at least lab 10.1.0):

```javascript
lab.experiment('basic zone with default options', () => {
  lab.test('zone without name property', { plan: 2 }, () => {
    const zone = require('./fixtures/zone_no_name');

    return validate(zone).then((result) => {
      console.log('rrr', result.errors.zone);
      result.app.not.existing += 1;
      Code.expect(result.errors.zone).to.be.array();
      Code.expect(result.errors.zone).to.have.length(1);
    })
  });
});
```

**Comment by mikl** [comment]
@gergoerdosi ok, returning the promise seems to be just what the doctor ordered, thanks. At least my problem is solved :)
