### ISSUE TITLE
Code coverage for conditional operator with comma operator isn't handled correctly

### ISSUE THREAD

**Issue by HCanber** [hapijs/lab#555]
__Version:__ Lab 10.3.0 with code coverage turned on, `-c`

### Problem
This expression is not correctly annotated so when the code is run it produces invalid result

```js
true ? ('no', 'yes') : 'nope'
```

__Expected value:__ 'yes'
__Actual value:__ 'no'

### Why
The reason is it's being annotated like this:

``` js
(global.__$$labCov._statement('/Users/2921/code/_3rd/lab/test/coverage/conditional2.js',1,1,true)
  ? global.__$$labCov._statement('/Users/2921/code/_3rd/lab/test/coverage/conditional2.js',2,1,'no', 'yes')
  : global.__$$labCov._statement('/Users/2921/code/_3rd/lab/test/coverage/conditional2.js',3,1,'nope'))
```

This excerpt shows that _consequent_ expression is missing it's parentheses:

``` js
global.__$$labCov._statement('file.js',2,1,'no', 'yes')
```

It should have been annotated as:

``` js
global.__$$labCov._statement('file.js',2,1,('no', 'yes'))
```

The _consequent_ code is rendered using `node.consequent.source()` on https://github.com/hapijs/lab/blob/b122ae64f2a257d118834cb7a73276b089a8377a/lib/coverage.js#L203

``` js
node.set('(' + node.test.source() + '? global.__$$labCov._statement(\'' + filename + '\',' + consequent + ',' + line + ',' + node.consequent.source() + ') : global.__$$labCov._statement(\'' + filename + '\',' + alternate + ',' + line + ',' + node.alternate.source() + '))');
```

The problem with missing parentheses comes from [acorn](https://github.com/ternjs/acorn) (used by [espree](https://github.com/eslint/espree)) that sets start and end position for _SequenceExpression_ to not include parentheses.

### Solution
I see three possible solutions:

1. Test if _consequent_ node is a _SequenceExpression_. If it is, add parentheses around it. Do the same for _alternate_ node.
2. Always surround _consequent_ and _alternate_ nodes with parentheses, i.e:

   ``` js
node.set('(' + node.test.source() + '? global.__$$labCov._statement(\'' + filename + '\',' + consequent + ',' + line + ',(' + node.consequent.source() + ')) : global.__$$labCov._statement(\'' + filename + '\',' + alternate + ',' + line + ',(' + node.alternate.source() + ')))');
```

3. [acorn](https://github.com/ternjs/acorn) has an option `preserveParens` that could be switched on
  >If this option is `true`, parenthesized expressions
  are represented by (non-standard) `ParenthesizedExpression` nodes
  that have a single `expression` property containing the expression
  inside parentheses."
  
I think the easiest and safest is alternative 2. There shouldn't be any problems with adding extra parentheses around the _consequent_ and _alternate_ nodes. It's already being done around the entire ternary expression.

If you're ok with alternative 2 I can submit a PR with the fix and a test.

**Comment by geek** [comment]
@HCanber thanks for the write-up.  Solution 2 sounds like the best approach.

**Comment by Marsup** [comment]
We should instrument each element individually, such statements might not be completely covered if one of them throws.
