### ISSUE TITLE
Error thrown when I use --coverage-exclude

### ISSUE THREAD

**Issue by JCarran0** [hapijs/lab#557]
lab -c --coverage-exclude demos is throwing the following error:

```
/Users/jcarrano/nv-student-api/node_modules/moment/moment.js:8
    global.__$$labCov._statement('/Users/jcarrano/nv-student-api/node_modules/moment/moment.js', 9, 8, true); ((global.__$$labCov._statement('/Users/jcarrano/nv-student-api/node_modules/moment/moment.js',1,8,typeof exports === 'object')&&global.__$$labCov._statement('/Users/jcarrano/nv-student-api/node_modules/moment/moment.js',2,8,typeof module !== 'undefined'))? global.__$$labCov._statement('/Users/jcarrano/nv-student-api/node_modules/moment/moment.js',7,8,module.exports = factory()) : global.__$$labCov._statement('/Users/jcarrano/nv-student-api/node_modules/moment/moment.js',8,8,((global.__$$labCov._statement('/Users/jcarrano/nv-student-api/node_modules/moment/moment.js',3,9,typeof define === 'function')&&global.__$$labCov._statement('/Users/jcarrano/nv-student-api/node_modules/moment/moment.js',4,9,define.amd))? global.__$$labCov._statement('/Users/jcarrano/nv-student-api/node_modules/moment/moment.js',5,9,define(factory)) : global.__$$labCo

TypeError: Cannot read property '_statement' of undefined
```

Where demos is a top level directory in my project.  I've tried to exclude other folders with the same issue.

npm  v3.3.12
node v5.3.0
moment ~2.12.0

**Comment by geek** [comment]
When `--coverage-exclude` is passed in, it overwrites the defaults that we have: `['test', 'node_modules']`

This is forcing the node_modules to not be excluded any longer.  I do think we should change this to merge in `node_modules` and to never allow that to be covered.

Back to your issue, if you run lab with the following, you should resolve the issue:

`lab -c --coverage-exclude demos --coverage-exclude node_modules --coverage-exclude test`

**Comment by JCarran0** [comment]
Great, that solved it.  Agree that node_modules should never be tested.  Thanks!
