### ISSUE TITLE
Run linting only

### ISSUE THREAD

**Issue by adrianblynch** [hapijs/lab#559]
Is there a way to run linting only?

So far I have an npm script:

```
"lint": "node node_modules/lab/node_modules/eslint/bin/eslint.js ./",
```

Which I don't like the look of!

**Comment by cjihrig** [comment]
I'm not sure if this is the "official" way, but you can do `lab -d -L`. The `-d` does a dry run, and doesn't actually execute the tests.

**Comment by geek** [comment]
We can document the `-dL` pattern, its what I prefer to use to only run linting
