### ISSUE TITLE
es6 coverage not support

### ISSUE THREAD

**Issue by willin** [hapijs/lab#561]
```
./node_modules/.bin/lab -r console -o stdout -r json -o coverage.json -t 100 -S --coverage-exclude node_modules -T node_modules/lab-babel -I __core-js_shared__
```

```
Server started at:  http://127.0.0.1:5000
node_redis: Warning: Redis server does not require a password, but a password was supplied.


  ..

2 tests complete
Test duration: 45 ms
No global variable leaks detected
Coverage: 100.00%
```

Always 100%

**Comment by Marsup** [comment]
I see no bug nor any way to reproduce your problem.

**Comment by willin** [comment]
![qq20160415-0 2x](https://cloud.githubusercontent.com/assets/1890238/14554753/70cb91f8-0321-11e6-8ba7-64e88f36a128.png)

**Comment by geek** [comment]
@willin can you provide code to reproduce this issue.

**Comment by willin** [comment]
try es7 async/await

**Comment by geek** [comment]
I was unable to reproduce: https://github.com/geek/lab-babel-coverage

**Comment by framerate** [comment]
My first time setting up using this to test my ES6 code for coverage I see the same thing.

With only a single test I see `Coverage: 100.00%`

I too am using `lab-babel` so I assume it's related?

`"test": "lab -C -t 99 -S -T ./node_modules/lab-babel -I __core-js_shared__ ./test-new/game.js --leaks --reporter console --verbose"`

@willin did you figure out what you were doing wrong?

**Comment by geek** [comment]
@framerate is this with the latest versions of everything?

**Comment by framerate** [comment]
Looks that way, yeah.
