### ISSUE TITLE
Lab and JSX transpiling?

### ISSUE THREAD

**Issue by antoniogiordano** [hapijs/lab#562]
Hi guys how can i handle jsx code in my scripts with lab?
I have "unexpected token <" error with lab, whilst i have no error running the app
Thanks

**Comment by vdeturckheim** [comment]
Hi @antoniogiordano ,
Can you provide an example ?
Do you transpile your code to javascript before testing ?

**Comment by geek** [comment]
@antoniogiordano please reopen if you can provide more details on how we can reproduce the issue.
