### ISSUE TITLE
--silence not working

### ISSUE THREAD

**Issue by jamesdixon** [hapijs/lab#565]
When running lab (v. 10.3.1) with `-s` or `--silence` , I'm still seeing lots of request logging. Is this intended and I'm just misunderstanding the point of `--silence` or does this sound like a bug?

Here's an example of what I'm seeing:

```
> node --use-strict ./node_modules/.bin/lab -s

160421/030249.869, [log,info,hapi-ioredis], data: connected to redis
160421/030250.705, [response], http://baldr.local:3001: post /businesses {} 201 (158ms)
Debug: handler, error
    {"msec":7.297729000449181,"error":"The specified 'subdomain' value is already in use for: candido","data":{"args":{"0":"subdomain","1":"candido"},"entity_name":"subdomain","arg1":"candido","name":"AlreadyInUseError","message":"The specified 'subdomain' value is already in use for: candido","isBoom":true,"isServer":true,"data":null,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}}}}
160421/030252.411, [response], http://baldr.local:3001: post /businesses {} 409 (15ms)
```

Thanks!

**Comment by geek** [comment]
@jamesdixon silence will quiet down the output of lab, but it won't silence stdout entirely... so logs from other places will still exist.

**Comment by jamesdixon** [comment]
Thanks, @geek !

**Comment by geek** [comment]
Sorry for the long delay in responding :( yikes.

**Comment by jamesdixon** [comment]
No worries -- wasn't super important

**Comment by fourq** [comment]
@jamesdixon where is "160421/030250.705, [response], http://baldr.local:3001: post /businesses {} 201 (158ms)" coming from if lab isn't silencing it, hapi server.inject? Did you ever figure out how to silence it?

**Comment by mtharrison** [comment]
@fourq that's response logging from Good

**Comment by fourq** [comment]
@mtharrison ahh, thank you!
