### ISSUE TITLE
Test coverage for one directory not being evaluated

### ISSUE THREAD

**Issue by JCarran0** [hapijs/lab#566]
I have 12 top level directories in my project, some of which I am excluding via --coverage-exclude.  My npm task is:

```
"test-cov-html": "env $(cat .env | xargs) lab -v -L -c -r html -o coverage.html --coverage-exclude demos --coverage-exclude node_modules --coverage-exclude misc --coverage-exclude test --coverage-exclude documentation",
```
I am NOT excluding a directory named /tasks, but for some reason the files in it are not being caught in my coverage report.  Any ideas why or how I should troubleshoot?

**Comment by Marsup** [comment]
Are they `require`d?

**Comment by JCarran0** [comment]
No.  These are tasks that I only ever run from the command line, so they aren't attached to module.exports or required in any other files currently.  I'm realizing as I type this that it means I won't be able to write tests for these scripts as is anyway.

So does lab recognize a file once it's required into a file in the /test directory?

**Comment by Marsup** [comment]
Lab doesn't try to look for files node doesn't handle, one could argue that it's a mistake but it's the current state. I think we should fix this or document it but that's a behavior many people don't realize.

**Comment by JCarran0** [comment]
I see.  OK, thanks for the explanation!  I agree that better documentation would be helpful here.

**Comment by geek** [comment]
The usage section describes this behavior as needing to pass in the individual files: https://github.com/hapijs/lab/blob/master/README.md#usage
