### ISSUE TITLE
Lab should return a 0 exit code upon test failure

### ISSUE THREAD

**Issue by FuzzySockets** [hapijs/lab#567]
This was making it difficult to setup a watch script for lab because the npm process would error out before getting to the watch portion. Technically a failed test or error within a test script doesn't mean lab itself has failed, so in my opinion the program should exit gracefully in this case.  To give some more context, the test was failing due to an undefined function on my behalf.  Mocha handles this by simply stating a test has failed with some descriptive output:

>   131 passing (67ms)
>   1 failing
> 
>   1) List constructs a list of objects:
>      ReferenceError: helloAll is not defined
>       at Context.<anonymous> (immutableListSpec.js:16:5)

Refer to my original post about the issue here:

https://github.com/npm/npm/issues/5452

> I can't get the --silent flag to work at all when running npm (version 3.7.2) scripts from my package.json. The script runs fine, but when any tests fail, npm exits the process.
> 
> My scripts are setup as follows...
> 
> ...
> "test": "NODE_ENV=test lab ./build --silent --pattern spec",
> "test:watch": "npm run --silent test && chokidar --silent './build/**/*.js' -c 'npm run --silent test'"
> 
> I've tried just about every combination of adding the --silent (-s) flag, but I still get this nasty output when running lab through either of the above npm scripts:
> 
> npm ERR! Darwin 15.3.0
> npm ERR! argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "run" "test:orig"
> npm ERR! node v5.6.0
> npm ERR! npm v3.7.2
> npm ERR! code ELIFECYCLE
> npm ERR! cl-api@0.1.0 test:orig: NODE_ENV=test lab ./build -s --pattern spec
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the cl-api@0.1.0 test:orig script 'NODE_ENV=test lab ./build -s --pattern spec'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the cl-api package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! NODE_ENV=test lab ./build -s --pattern spec
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR! npm bugs cl-api
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! npm owner ls cl-api
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! ./npm-debug.log
> When I run lab directly, I do not get the same logging naturally.
> 
> Workaround I've managed to work around this issue by revising my test script to contain || true as mentioned by @ngryman above. My revised test scripts look like this:
> 
> ...
> "test": "NODE_ENV=test lab ./build -P spec || true,
> "test:watch": "npm run test && chokidar './build/**/*.js' --silent -c 'npm run test'"
> ...
> 
> I guess maybe lab is just too extreme with their exit codes.

**Comment by mtharrison** [comment]
Travis, Jenkins etc all rely on your exit code to know if your build passed so you want lab to exit with non-zero if anything goes wrong (a test failed, lint failed, non 100% coverage) in pretty much all occasions. `|| true` is a pretty standard pattern if you don't care about exit code.

**Comment by FuzzySockets** [comment]
@mtharrison Hmm -- good point... I wonder why npm isn't affected by the -1 exit with mocha vs lab.

**Comment by arb** [comment]
Watch does not have a concept of a watch flag.

**Comment by geek** [comment]
@FuzzySockets is there anything that needs to be done to lab?
