### ISSUE TITLE
leaks detected:Reflect using node v6.0.0

### ISSUE THREAD

**Issue by cpilsworth** [hapijs/lab#568]
When running a lab test with v6.0.0 with the latest Lab (v10.3.1), I get the following message:
```
$ node --version
v6.0.0
$ npm --version
3.8.6
$ nvm --version
0.31.0

The following leaks were detected:Reflect
(node:2983) DeprecationWarning: 'root' is deprecated, use 'global'
npm ERR! Test failed.  See above for more details.
```
Works with all 4.x.x, 5.x.x versions of Node.

The failing build can be found here:
https://travis-ci.org/cpilsworth/aws-s3-signurl/jobs/126106138
and a working build here:
https://travis-ci.org/cpilsworth/aws-s3-signurl/jobs/126106139

**Comment by cpilsworth** [comment]
Updated dependencies to `"lab": "hapijs/lab#master"` and the problem persists

**Comment by AdriVanHoudt** [comment]
Master is the published version on this repo.

The hapi modules have not been updated to work with v6 (hapi modules officially supports 0.12 in LTS mode and 4 I think) and this could take some time. In the meanwhile if you want to speed this up I'm sure they will appreciate any help/PR!

**Comment by geek** [comment]
@cpilsworth this is now published and everything is working in node v6 with version 10.3.2 of lab.  Thanks for the PR and issue!

**Comment by cpilsworth** [comment]
np.  @gergoerdosi did the good work on the PR.  Thanks for merging so quickly!
