### ISSUE TITLE
Detecting errors in `lab.after` [feature-request]

### ISSUE THREAD

**Issue by ilyaigpetrov** [hapijs/lab#571]
I use this hack to detect errors in `lab.after`:

``` javascript
lab.after( (done) => {

    if ( process.env.IF_DUMP_CACHE ) {
        const ifNoErrors = lab._root.experiments.every( (ex) =>
            ex.tests.every( (test) => !test.err )
        );
        if ( ifNoErrors ) {
            persistCache( cache );
        }
    }
    return done();
});
```
# Why

My code interacts with remote APIs which answers may change over time.
So I cache answers during the first test run and reuse the cache on subsequent runs.
I want to persist cache inside `lab.after` if all tests pass.
Using reporter via CLI is cumbersome and you can't pass it via `Lab.script(...)`.

**Comment by geek** [comment]
@ilyaigpetrov what change are you asking for?

**Comment by ilyaigpetrov** [comment]
@geek I would be happy with using `lab._root` but it is private, so I offer exposing any public way of accessing results of `Lab.script` inside `lab.after`. E.g.:
```javascript
lab.after( (done, notebook) => {...} );
// or
lab.after( (done) => { const experiments = lab.experiments; ... } );
```
How actually to make script results public is a design decision (not for my teeth).
Another approach to cache dumping would be to use reporters, but then I need a way to pass a cache recorded during test execution inside a custom reporter.

**Comment by geek** [comment]
@ilyaigpetrov is this a feature you are interested in implemented?

**Comment by ilyaigpetrov** [comment]
@geek Sorry, I haven't used hapijs/lab infrastructure for so long I can't tell if the feature desired was implemented or not.

**Comment by geek** [comment]
@ilyaigpetrov closing for now, feel free to reopen if you still need it
