### ISSUE TITLE
Lab versions failing on Node 6.1.0

### ISSUE THREAD

**Issue by mihaidma** [hapijs/lab#581]
On Node 6.1.0 test failures are caused by **Lab 6.2.0, 7.3, 8.4, 9.1**:

```sh
# reported by test run
The following leaks were detected:Reflect
npm ERR! Test failed.  See above for more details.

# reported by linter
(node:14438) DeprecationWarning: 'root' is deprecated, use 'global'
```

**How to reproduce**

Put in package.json:
```js
"scripts": {
    "test": "lab index.js -v -L"
  },
"devDependencies": {
    "lab": "6.x.x"
  }
}
```
and in the js file:
```js
var Lab = require('lab')
var lab = exports.lab = Lab.script()
```

Tests:
- on Node 6.1.0, Lab 6.2.0 gives the error and warning described above,
- on Node 0.10.44 with Lab 6.2.0 it gives no errors or warnings,
- Lab 7.3.0 requires from Node 4 up but gives the same issues on Node 6,
- Same issues with Lab 8.4, Lab 9.1.0
- **Lab 10.5.1 works ok**

**Comment by AdriVanHoudt** [comment]
Lab only supports node 6 from 10.3.2 (or more specifically this commit https://github.com/hapijs/lab/commit/c7dd9744c08c45d93231381d5964c76bfb181c85)

Is there a question or?

**Comment by mihaidma** [comment]
Thank you for the quick confirmation. In our project we need to support Node down to 0.10 and had issues with Lab 6.

Do you know any workarounds for this?
Else from my point of view thread can be closed.

**Comment by geek** [comment]
@mihaidma please disable leak checking (`--leaks`) and try again.

**Comment by mihaidma** [comment]
Indeed the --leaks solved the issue. I could run successfully tests with Lab 6.x and Node 6.
Thank you.
