### ISSUE TITLE
Test - Leaks detected

### ISSUE THREAD

**Issue by vmendiratta** [hapijs/lab#582]
Hi

I've configured my package.json to run hapijs lab tests when I run 'npm test'.

The relevant portion of package.json:
```
  "scripts": {
    "prestart": "npm install",
    "pretest": "npm install",
    "test": "lab -c"
  },
```

I get a 'leaks detected' message when I run my tests using 'npm test' but no such message when I run them by using just 'lab'.
The leak is 'Reflect' (I suspect it belongs to lodash but I could be wrong).

Any reason why I would see such behaviour?

Thanks.

**Comment by gergoerdosi** [comment]
You use node v6 with a lab version that is not compatible with it. Update lab to the latest version and the error will go away.

**Comment by vmendiratta** [comment]
Thanks. This worked.
