### ISSUE TITLE
Update lab to handle node version 6 using old syntax

### ISSUE THREAD

**Issue by danielb2** [hapijs/lab#590]
Use-case:  I want to make sure my library is compatible with releases 0.10, 0.12, 4.x and 6.x

Right now lab v6.x is the last version that handles the old syntax (no `const` or `let`), but if I use lab v6.x to test to make sure my code is compatible, I get a leak for `Reflect`.

I made the [changes](https://github.com/hapijs/lab/search?utf8=%E2%9C%93&q=Reflect) using tags for v6.2.0 but couldn't get the tests to run.

**Comment by geek** [comment]
Disable leak checking with the --leaks flag.

**Comment by gergoerdosi** [comment]
You can also just add `Reflect` to the ignored list of globals: `--ignore 'Reflect'`.

**Comment by danielb2** [comment]
@gergoerdosi thank you 👍
