### ISSUE TITLE
Unreadable text using solarized dark theme

### ISSUE THREAD

**Issue by tribou** [hapijs/lab#592]
It looks like lab's colored output is affected by the infamous altercation/solarized#220 issue.

![screen shot 2016-05-23 at 9 57 22 pm](https://cloud.githubusercontent.com/assets/1641390/15491008/1cf4c340-2132-11e6-8a87-7e156a5fe21c.png)

Is there a way to disable colors?

I tried `lab --colors false`, `lab --colors null`, and `lab --colors=false`.

`lab@10.6.1`

**Comment by geek** [comment]
@tribou I am open to any fixes
