### ISSUE TITLE
require path errors are ignored and no warning is presented

### ISSUE THREAD

**Issue by tjsail33** [hapijs/lab#605]
When you `require` a file in a Lab test suite that does not exist, there is no error thrown and tests in other files continue to run. When the `require` fails in the head of a file (before the `describe`), none of the tests will run and no error will be shown.

**Comment by Marsup** [comment]
Works for me : `Error: Cannot find module './foobar'`. Provide a way to reproduce please.

**Comment by geek** [comment]
@tjsail33 make sure your code isn't swallowing `process.on('uncaughtException'`
