### ISSUE TITLE
NODE_ENV is no longer defaulting to 'test'

### ISSUE THREAD

**Issue by nlf** [hapijs/lab#606]
[this commit](https://github.com/hapijs/lab/commit/4d228729a352a532be29c0a268c21a854610a53d#diff-f8849ae9f0614ba9464fdd14c2d98dc0L180) removed the default for the environment setting erroneously causing NODE_ENV to be set to `undefined` if none is passed

**Comment by nlf** [comment]
the bigger concern here is that there's a test to verify the default that's passing despite this

**Comment by geek** [comment]
@nlf the test is correct, there is a default environment value set in the runner.  It looks like issue is in the merging of the cli config and these runner defaults.

**Comment by nlf** [comment]
ah ok, that makes more sense

**Comment by geek** [comment]
@nlf I actually can't reproduce.  Can you provide more information: the node version and if you have a `.labrc.js` set?  I tried with hapi and it shows that the NODE_ENV is set to "test" when I run using the latest version of lab.

**Comment by nlf** [comment]
using latest lab, node 6.2.1, no `.labrc.js` exists

if you create an empty directory, install lab, and insert the boilerplate below as `test/index.js` it reproduces it for me

```
'use strict';

const lab = exports.lab = require('lab').script();
console.log(process.env.NODE_ENV);
```

**Comment by geek** [comment]
@nlf this is now published
