### ISSUE TITLE
some options can't be configured with .labrc.js 

### ISSUE THREAD

**Issue by feugy** [hapijs/lab#609]
First of all, thank you for that configuration file !

Right now, some options can't be overridden.
It's because cli settings [overrides file options](https://github.com/hapijs/lab/blob/master/lib/cli.js#L401), and because unspecified cli options have default values (like [`linter`](https://github.com/hapijs/lab/blob/master/lib/cli.js#L229), [`lint-errors-threshold`](https://github.com/hapijs/lab/blob/master/lib/cli.js#L244)...).

Maybe the merge should take cli options (without default), then file options, then defaults ?

**Comment by geek** [comment]
@feugy, thanks.  We will need to move the merge operation to happen earlier in the cli options function and to merge in cli defaults after the file/argv options... as you are suggesting :)

**Comment by feugy** [comment]
FYI the current way of handling transformers in option file is tricky but really powerfull.
In my case, I need to apply two transformers to .js files, which was not possible with the cli options:

```javascript
const babelTransform = require('lab-babel').find(t => t.ext === 'js').transform
const assertTransform = require('lab-espower-transformer')[0].transform

module.exports = {
  coverage: true,
  lint: false,
  transform: [{
    ext: 'js',
    // combines both transformations
    transform: (content, filename) => assertTransform(babelTransform(content, filename), filename)
  }],
  // equivalent of verbose
  progress: 2
}
```
