### ISSUE TITLE
Upgrade to eslint@2.13.x

### ISSUE THREAD

**Issue by feugy** [hapijs/lab#610]
Currently lab uses eslint@2.10.x, and it took 27s to process my sources.
With eslint@2.13.x, it took only 3s

This is due to [2.12 improvement](https://github.com/eslint/eslint/commit/fca067938fcd54c98945356b41c8c9a7dc404c04) that do not walk into ignored folders (like huge `node_modules`)

Please, save our lives :grinning:

**Comment by cjihrig** [comment]
Nevermind. @lloydbenson is a life saver!

**Comment by feugy** [comment]
You guys are awesome ! Thanks a million
(It was late yesterday, and I wasn't brave enought to fork and send a PR).
