### ISSUE TITLE
Test coverage shows untransformed output

### ISSUE THREAD

**Issue by garthk** [hapijs/lab#614]
`lab -T test/lib/transform-tsc.js test -v -S -c -r html -o cov.html` produces a coverage file with:
- Correct test results
- Correct pre-transform filenames, e.g. `index.ts` in the navigation bar and code coverage report headers
- Correct coverage information, e.g. reporting "condition always false"
- The post-transform file contents, _not_ the expected pre-transform file contents

`lab -T test/lib/transform-tsc.js test -v -S` with a failing test produces correct line numbers for pre-transformed code.

Reproduction repository: [`garthk/lab-coverage-vs-sourcemaps-typescript-edition`](https://github.com/garthk/lab-coverage-vs-sourcemaps-typescript-edition)

See also: hapijs/lab#338

I'm hoping this is a configuration problem, in which case I'm happy to have pitched in with typings for `code` and `lab` and a skeleton project for anyone trying to drive them from TypeScript and Visual Studio Code.

**Comment by feugy** [comment]
I encounter exactly the same problem with babel transformer.
It seems to be the way that html reporter [is written](https://github.com/hapijs/lab/blob/85d252f1164f16cc427bf8a54625a2389164e9b6/lib/reporters/html/partials/line.html#L7):

It output the post-transform code, and just add information on original line and filename as a tooltip.

That is said, it's not really the behaviour a user expect from that kind of report. @geek, do you already have plan in mind ? I'll be glad to do a PR to improve that.

**Comment by geek** [comment]
@feugy no plan in mind from me, please do fix with a PR if you have the time. Thanks!

**Comment by mmc41** [comment]
Also interested in a fix for this.

**Comment by d3viant0ne** [comment]
I'll see if I can work this out with @garthk / @feugy in the next few weeks as all of our new server side Node work is Hapi / TypeScript and proper pre-transform coverage is optimal.

**Comment by danielo515** [comment]
Dear @garthk ,

How did you ended using to that configuration? I looked through the entire internet to find how to test typescript code with lab and I didn't find any information. Thank god you have opened this issue.

Regarding the coverage report, I'm getting coverage information of the compilled code. Using es6 as target instead of es5 would definitely help to get a closer view of the source.

Have you noticed that the issue you referenced Microsoft/TypeScript#7980 has been closed?

**Comment by garthk** [comment]
Yep! [`lab-transform-typescript`](https://github.com/garthk/lab-transform-typescript) now loads your `tsconfig.json` using TypeScript's own machinery. It also forces inline source maps so line numbers in tracebacks are OK with `lab -S`. The source code is still hard to read. As you point out, using an `es6` target helps; I'm looking forward to Node 8 so I can safely set `target` to `es2017` in [TypeScript 2.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#support-for---target-es2016---target-es2017-and---target-esnext); see also [`node.green`](http://node.green).

**Comment by danielo515** [comment]
Why have you closed this issue? is it resolved ?

**Comment by Marsup** [comment]
It's written on the close event.

**Comment by AdriVanHoudt** [comment]
The close event being -> `@geek geek closed this in #648 3 days ago`

**Comment by feugy** [comment]
@danielo515 I'll be glad to have someone else testing this, so if you can run it against your codebase, any feedback will be appreciated.

**Comment by danielo515** [comment]
Sure @feugy ,
The version that has the fix is the `13.0.0` right?

**Comment by Marsup** [comment]
Version 13 is not released yet, you'll have to test it from master.

**Comment by geek** [comment]
v13.0.0 is now published! Here are the release notes: https://github.com/hapijs/lab/issues/684
