### ISSUE TITLE
Coverage with while (true)

### ISSUE THREAD

**Issue by tschaub** [hapijs/lab#616]
I'm curious if it is possible to get 100% test coverage with `while (true)`.  For example, given this test below:
```js
const expect = require('code').expect;
const lab = exports.lab = require('lab').script();
const mod = require('./mod');

lab.experiment('while', () => {
  lab.test('code coverage', done => {
    expect(mod.works()).to.be.true();
    done();
  });
});
```

The `mod.js` below has ~95% coverage (missing on line 3):
```js
exports.works = function() {
  let i = 0;
  while (true) { // missing coverage?
    ++i;
    if (i > 10) {
      break;
    }
  }
  return i > 0;
}
```

**Comment by Marsup** [comment]
It checks truthy and falsy branches, the 1st one is never ever false.

**Comment by tschaub** [comment]
Thanks @Marsup.  The second example was not well thought out.  I've updated the description.  Would it be of interest to anyone else to make it so while statements with a literal `true` weren't annotated with an alternate branch for testing coverage?

**Comment by geek** [comment]
@tschaub if there is a valid reason or need to have `while (true)` I am open to the change.  However, the example would be clearer if the condition is in the while itself.

```
exports.works = function() {
  let i = 0;
  while (i <= 10) {
    ++i;
  }

  return i > 0;
};
```

**Comment by fabiob** [comment]
@geek, I think I have a valid use for `while (true)` on my app: a `cycle` function, which I use on functional programming:

```
function* cycle(a) {
  while (true)
    yield* a;
}
```

Here's some inspiration: https://clojuredocs.org/clojure.core/cycle
