### ISSUE TITLE
"Multiple callbacks or thrown errors received in test" if I use `done` in a catch of a promise

### ISSUE THREAD

**Issue by jcollum** [hapijs/lab#626]
Related #580 (same? close this if so please, I'm not sure)

#490 appears to be unrelated

Test: 

```
var Bluebird, sinonAsPromised;

Bluebird = require('bluebird');

sinonAsPromised = require('sinon-as-promised')(Bluebird);

...

  it('should reject a promise when SQL execution fails', function(done) {
    var library, req;
    library = sinon.stub();
    req = sinon.stub();
    req.input = function() {};
    req.execute = sinon.stub();
    req.execute.callsArgWith(1, "he's dead Jim!", null, null, null);
    library.Request = function() {
      return req;
    };
    router.logger.ignoreErrors = true;
    return router.executeSql('SELECT * FROM yadayada', library, null).then(function(results) {
      console.log('then path taken?');
      return console.log(arguments);
    })["catch"](function(err) {
      console.log("promise catch");
      console.dir(err);
      err.message.should.match(/Jim/, "Error message incorrect");
      return done();
    });
  });
```

For some reason the test fails with `Multiple callbacks or thrown errors received in test` when run. It's going down the correct path (console output is correct, err.message test passes, "then path taken?" is not logged. 

The problem is that the test will pass with no issues *if* I remove the `done()` call in the catch function. I can't explain this. I was hoping for an explanation or comment. I'm putting this here so others will see it -- remove the done call in this sort of test.

**Comment by geek** [comment]
@jcollum since you don't want lab to evaluate the promise, you should not return it. This will force lab to wait for the done callback to be called instead of lab evaluating the promise.
