### ISSUE TITLE
"No coverage information was collected, exit without writing coverage information" even though 11 tests ran

### ISSUE THREAD

**Issue by jcollum** [hapijs/lab#627]
I'm trying to get Istanbul and Lab working together. It does work, sometimes. Then other times, I get "No coverage information was collected, exit without writing coverage information" if I force it to write out an `lcov` report. But the tests all ran and passed! This is confusing. 

```
$ ./node_modules/.bin/istanbul cover ./node_modules/.bin/lab -- -l -e development ./dist/test/unit.js 

    ...........

11 tests complete
Test duration: 267 ms
```

with `-r lcov`:

```
TN:
SF:/Users/collumj/work/crdb/api/dist/router.js
DA:1,1
DA:2,1
DA:3,1
...
DA:794,1
DA:795,1
LF:762
LH:726
end_of_record
No coverage information was collected, exit without writing coverage information
```

What do I do with this? The tests are running, I was getting coverage a few hours ago (37.2%, ugh) and now I get none. If I had to guess I'd say that Istanbul can't do anything here because Lab isn't emitting proper code coverage data. Do I need to provide some hints to Lab or something?

**Comment by Marsup** [comment]
Why would you even try to do that ? Isn't lab enough in itself ?

**Comment by jcollum** [comment]
We have Istanbul already wired in to Sonar. I'd rather not have to make a different Sonar profile for projects that use Lab. It seems like Lab is the part that's failing here. Istanbul has been fine.

**Comment by Marsup** [comment]
Why don't you feed lcov directly to jenkins, I really don't understand the need for istanbul at all.

**Comment by jcollum** [comment]
Jenkins? What? 

The more I look at this the more it looks like Lab isn't writing Lcov correctly. 

``` 
$ ./node_modules/.bin/lab  -l -e development ./dist/test/unit.js  
  ...........

11 tests complete
```

OK, good, let's try with Lab coverage:  

```
./node_modules/.bin/lab -t 80 -e development ./dist/test/unit.js   
...
11 tests complete
Test duration: 283 ms
No global variable leaks detected
Coverage: 80.67% (360/1862)
dist/router.js missing coverage on line(s): 114, 115, 116, 118, 119, 120, 
```

Looks good right? Well, let's try outputting to an lcov file and feeding that to Istanbul:  

```
$ ./node_modules/.bin/lab -r lcov -l -e development ./dist/test/unit.js > coverage/coverage.info
$ istanbul report html
Done
```
Looks good right? Well, when I open the report it says that the coverage is 100% and there's no no functions/code in there. 

FYI we have Istanbul working and integrated with another project with no issues. Maybe it's Istanbul's issue but I think it's Lab, based on what I'm seeing.

**Comment by jcollum** [comment]
I did save a copy of a working coverage file from this morning. In there, there are 244 BRDA lines. In the non-working coverage file from this afternoon, there are none. Same for FNDA. That seems suspicious doesn't it?

**Comment by Marsup** [comment]
Why are you omitting the parameters that are enabling the coverage in the last command ?

**Comment by jcollum** [comment]
Because I'm feeding the coverage symbols to Istanbul, which is generating the report.

**Comment by Marsup** [comment]
I don't think you're feeding anything to istanbul if you don't enable coverage.

**Comment by jcollum** [comment]
with `-c` : 

```
11 tests complete
Test duration: 309 ms
Coverage: 80.67% (360/1862)
dist/router.js missing coverage on line(s): 114, 115, 116, 118, 119, 120, 121, 122, 200, 203, 224, 225, 230, 231, 232, 237, 260, 263, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 317, 327, 356, 357, 363, 364, 365, 382, 395, 396, 398, 399, 408, 409, 410, 412, 415, 425, 426, 431, 432, 436, 437, 439, 440, 441, 447, 448, 449, 450, 452, 453, 454, 455, 465, 468, 
```

Without -c: 

```
11 tests complete
Test duration: 183 ms
```

Neither of those are a coverage file. 


With `-r lcov`: 

```
...
DA:789,1
DA:790,1
DA:791,1
DA:792,1
DA:793,1
DA:794,1
DA:795,1
LF:762
LH:726
end_of_record
```

**That's a coverage file.**

**Comment by jcollum** [comment]
I tried the full command (note `-r lcov -c`): 

`./node_modules/.bin/istanbul cover ./node_modules/.bin/lab --  -l -e development -m 2000 -c -r lcov ./dist/test/unit.js ` 

Result: 

```
DA:792,1
DA:793,1
DA:794,1
DA:795,1
LF:762
LH:726
end_of_record
No coverage information was collected, exit without writing coverage information
```

**Comment by geek** [comment]
@jcollum can you pipe in a lcov file to istanbul?

**Comment by geek** [comment]
@jcollum any updates? Please reopen if so, closing for now.

**Comment by jcollum** [comment]
Nah, in the meantime Lab's coverage tools improved enough to be equivalent to the other tool I was using so I just use Lab.
