### ISSUE TITLE
lab it not  support es6 javascript syntax???

### ISSUE THREAD

**Issue by syzh** [hapijs/lab#632]
the error message:
% /usr/local/node-v4.4.7/bin/npm test                                                             130 ↵ ✖ ✹ ✭

> node@1.0.0 test /var/node
> lab ./tests

/var/node/app.js:3
import hapi from 'hapi';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)

test.js file content:
const Lab = require('lab');
const lab = exports.lab = Lab.script();
const server = require('../app');

lab.test('cleanups after test', (done, onCleanup) => {
  done();
});

**Comment by cjihrig** [comment]
`import` is not supported natively by Node yet.

**Comment by geek** [comment]
@syzh you will need to use babel if you want to use `import`, then use the transforms feature of lab.

**Comment by jedireza** [comment]
If you'd like a simple reference I have a demo repo up here: [jedireza/lab-es6](https://github.com/jedireza/lab-es6).

The demo uses [`lab-babel`](https://github.com/nlf/lab-babel), but you may want to roll your own transform script.
