### ISSUE TITLE
Coverage no longer reported properly

### ISSUE THREAD

**Issue by gelliott181** [hapijs/lab#633]
I came up on a very, very weird issue. I was writing up some tests for my hapi server, getting all green with 100% code coverage. I then switched to a new command line window (Windows 10 64-bit CMD) and while all my tests passed, code coverage reports 0%. Going back to the original window, tests came back with 100% coverage, again. Below is the resulting output for both, and both were run on a clean git clone of the master branch.

![Comparison of two Terminals](http://i.imgur.com/BXqJyYl.png)

Clearly something has gone horribly, horribly wrong, but I don't even have information from Lab as to what happened to my coverage, and as such can't provide context because there is none. No terminal other than the one on the right provides code coverage, which means now that I've closed it I have zero coverage reporting available. Any thoughts where to go from here trying to pin this down?

**Comment by Marsup** [comment]
Can you provide a repo where it's easily reproducible ?

**Comment by gelliott181** [comment]
My Jenkins build server still builds and reports 100% coverage with the same repo these came from. 

This is a relatively new internal project for my org so let me go through the hackier parts and make sure I don't leak anything before I make it available.

**Comment by gelliott181** [comment]
@Marsup I provided you access to the repo through my [BitBucket](https://bitbucket.org/gelliott181/locomotive/).

**Comment by Marsup** [comment]
Made several runs, coverage is always 100%, you'll have to debug lab on your own machine I guess...

**Comment by gelliott181** [comment]
Thanks for checking it out, time to nuke my dev machine and get a nice clean Node install again.

**Comment by Marsup** [comment]
I'm on linux so maybe it's a windows specific issue, don't throw it just yet :)

**Comment by gelliott181** [comment]
Just wiped out Node v6.3.1 and did a fresh install of v6.5.0. 100% coverage is back!
