### ISSUE TITLE
coverage includes test file

### ISSUE THREAD

**Issue by jcollum** [hapijs/lab#635]
`$ ./node_modules/.bin/lab -l -e development -t 80 -v -r html  ./dist/test/unit.js > coverage/coverage.html`

The coverage report includes `./dist/test/unit.js`. Why would I care about coverage in my test file? I'd like to ignore it for coverage but there's nothing about that in the docs.

**Comment by Marsup** [comment]
You should really work on your search skills 😄 See `--coverage-exclude`.

**Comment by jcollum** [comment]
Ah, I was searching for ignore, not exclude.

**Comment by jcollum** [comment]
But doesn't it seem strange that a tool would report coverage on a file that contains tests? I assume that file would be automatically excluded, I can't think of any situation where I'd want to see coverage for a test file.

**Comment by jcollum** [comment]
For anyone who comes along later, that argument expects a directory and it can't be relative: 

`$ ./node_modules/.bin/lab -l -e development -t 80 -v -r console --coverage-exclude dist/test ./dist/test/unit.js ` -- works 

`$ ./node_modules/.bin/lab -l -e development -t 80 -v -r console --coverage-exclude ./dist/test   ./dist/test/unit.js ` -- does not work

`$ ./node_modules/.bin/lab -l -e development -t 80 -v -r console --coverage-exclude dist/test/unit.js   ./dist/test/unit.js ` -- does not work

**Comment by Marsup** [comment]
How would lab even know that a test file is a test file ? And why wouldn't you occasionally want to cover your test files ? If you're running tests but not testing what you expect, this is also a problem.

**Comment by jcollum** [comment]
> How would lab even know that a test file is a test file ? 

The other nodejs coverage tool (istanbul) that I've used managed this. The file/dir that I'm passing that I say "this one contains tests" (i.e. the last argument in the code above) -- don't cover that file. 

> And why wouldn't you occasionally want to cover your test files ?

I've never heard of anyone doing this. It seems like a "turtles all the way down" situation -- how do you know the test that tests the test is testing what you expect?
