### ISSUE TITLE
Snapshot testing & its implementation

### ISSUE THREAD

**Issue by ldesplat** [hapijs/lab#637]
I was looking into implementing snapshot testing much like it is implemented in Jest - https://facebook.github.io/jest/blog/2016/07/27/jest-14.html 

I am not interested in the React part here, more than I am interested in the behavior of it. In a few projects, I do something very similar to what snapshots fixes. 
The APIs respond with complex JSON objects and I verify them using Code `expect(res.result).to.equal(require('../myResult.json'))`. So whenever I add a new field, I then run a regex in my editor to change those lines to write back to the file to update those and do a git diff making sure everything is ok.

Snapshots basically makes this automated in the following way:
- `expect(res.result).toMatchSnapshot()` would look in `__dirname/__snapshots__/{Name of test[i]}.snap` to see if a snapshot exists.
- If there is no snapshot, it serializes the object there and passes the test. It is up to you to verify the results.
- If there is a snapshot it would do some similar to `.to.equal` with the file contents and if it does not matches then fail the test.
- You can then update your snapshots running lab with some sort of command flag (yet another one).

The problems implementing this in lab & code are the following:
1) I cannot get the test name from `this.lab` in a test. I looked in there, and I can list the tests and the experiments but title is always `script`. I am guessing this is a bug or I am not looking correctly.
2) I would need to add a matcher to Code that I guess forces it to be dependent upon Lab for it to work. People I guess could implement mocha and such on top of it but still.
3) Passing the command line from Lab to Code (I guess populate a bit more in `this.lab`).

When I do fix 1 or find the right way to grab the test name, would people be open to this functionality and coupling of Code/Lab? @cjihrig

**Comment by geek** [comment]
For 1 we pass `null` for the `thisArg` https://github.com/geek/lab/blob/master/lib/runner.js#L647

We don't have to couple lab and code together, do we? This could even be a generic snapshot utility outside of lab and code

```js
const Code = require('code');
const Lab = require('lab');
const Snapshot = require('snapshot');

// shortcut stuff


it('does some work', function (done) {
  const result = doSomeWork();
  const snapshot = Snapshot('does some work', result);
  expect(result).to.equal(snapshot);
  done();
});
```

In Snapshot you can look for an environment variable to `SNAPSHOT_UPDATE` or similar... otherwise you save/return the saved snapshot result.

**Comment by geek** [comment]
@ldesplat see the response above

**Comment by ldesplat** [comment]
Thank you @geek . It's not exactly as easy to use due to the extra setup that needs to happen but it's a great place to start. Definitely does not need to be linked to Lab for now. I'll look into an integration once I get to make the snapshot module!

My confusion with `this` was that Lab.script() puts stuff in `this` and when you use arrow notation, it leaked to the tests :)

**Comment by lokoArt** [comment]
Support it, having a snapshot testing out of the box would be helpful
