### ISSUE TITLE
feature request: exclude blocks from coverage

### ISSUE THREAD

**Issue by jcollum** [hapijs/lab#638]
I have a function in my code that is only used on my dev machine to troubleshoot memory issues: 

```
/*
    istanbul ignore next -- this is only used in dev memory troubleshooting code
   */

  formatBytes = function(bytes, decimals) {
    var dm, i, k, sizes;
    if (bytes === 0) {
      return '0 Byte';
    }
    k = 1000;
    dm = decimals + 1 || 3;
    sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
    i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
  };

```

Istanbul (coverage tool I was using before) is able to ignore functions by adding a comment before it: `istanbul ignore next`. It would be nice if Lab had this ability as well. I don't want to remove this code but I don't see the point in writing a test for it either and it's reducing my coverage numbers.

**Comment by jedireza** [comment]
From the README:

> Sometimes you want to disable code coverage for specific lines, and have the coverage report omit them entirely. To do so, use the $lab:coverage:(off|on)$ comments. For example:

```js
// There is no way to cover this in node 0.10
/* $lab:coverage:off$ */
if (typeof value === 'symbol') {
    return '[' + value.toString() + ']';
}
/* $lab:coverage:on$ */
```

**Comment by jcollum** [comment]
Man i swear yall use different terms for everything. Ignore? No, disable.

**Comment by jcollum** [comment]
I'm saying that's why it didn't show up when I searched for it.

**Comment by jedireza** [comment]
The word _disable_ is actually in the content I quoted. 😉

**Comment by Marsup** [comment]
Why do you keep on searching for adjectives when you can just search for coverage...

**Comment by mtharrison** [comment]
It's not a very sustainable approach to search for 1 word, not find it, then open an issue and others have to help. I normally exhaust all other avenues, including reading the full readme for what I'm looking for before opening an issue on something.

**Comment by jcollum** [comment]
Sure. I was working on 5 hours of sleep. Sorry.
