### ISSUE TITLE
ignore setting not supported in .labrc.js

### ISSUE THREAD

**Issue by reverentgeek** [hapijs/lab#641]
Based on the README, I tried putting an `ignore` setting in my `.labrc.js`, but it was being... _ignored_. After digging around, I discovered that the `--ignore` cli parameter is an alias for `--globals`, which is not in the README. I changed the `ignore` property to `globals`, and now it works.

**Comment by jtlapp** [comment]
Thank you. This fixed my problem too. Cost me 10-15 minutes.
