### ISSUE TITLE
Unclear if this runs tests in multiple Node.js processes

### ISSUE THREAD

**Issue by ORESoftware** [hapijs/lab#650]
Question for you - unless I missed something in the docs, it's unclear whether Lab runs tests in separate Node.js processes. It's not necessarily a bad thing if Lab does not, but I am just curious. Thanks!

**Comment by geek** [comment]
Only the linting is done in a separate process, in order to speed up the overall execution time: https://github.com/hapijs/lab/search?utf8=%E2%9C%93&q=child_process

**Comment by ORESoftware** [comment]
thanks!
