### ISSUE TITLE
disable lab before timeout

### ISSUE THREAD

**Issue by danielo515** [hapijs/lab#652]
According to the documentation, lab.before accepts an option object with arguments, one of them can be timeout

> timeout - set a specific timeout in milliseconds. Disabled by default or the value of -M.

According to documentation it is disabled by default, but if I do not set certain timeout it is failing after 2k milliseconds. I tried to set it to 0 with the same result. Could someone teach me a valid way?

Thanks and regards

**Comment by geek** [comment]
It looks like a bug where 0 isn't allowed: https://github.com/hapijs/lab/blob/master/lib/runner.js#L338

I will fix this later tonight, or if you want to submit a PR, I am happy to merge and publish.

**Comment by kgraves** [comment]
I'm happy to submit a PR for this, if you guys haven't already done the work. However, I have a couple questions:

* On the above quote of the documentation, I'm confused as to what the `-` in `-M` represents.
* What, if any, constraints do we put on `timeout`? (i.e. positive number, integer, etc)

**Comment by geek** [comment]
@kgraves 
`-M` represents the command argument for the timeout for each test
It needs to be anything that `setTimeout` will accept

**Comment by danielo515** [comment]
I think this issue can be closed

**Comment by danielo515** [comment]
Sorry for issue respawn, but The documentation is still wrong about this feature.

What documentation says.

> Timeout - set a specific timeout in milliseconds. Disabled by default or the value of -M.

But my experience demonstrates that it is **not** Disabled by default, if you do not provide a value, and relies to the default behavior it fails after 2k milliseconds. I suggest to update the documentation or to update the code to match the documentation.

**Comment by geek** [comment]
@danielo515 please open a PR to fix the docs, I'll merge.
