### ISSUE TITLE
Feature request: Exclude file types from code coverage

### ISSUE THREAD

**Issue by sfabriece** [hapijs/lab#663]
As I'm including my test files besides the code that they are testing, I would like a way to exclude a pattern of files from code coverage tests.

I use `.spec.js` for my test files. Something like:

```js
lab --assert code --colors --coverage --threshold 100 --coverage-exclude-pattern spec
```
or something like

```js
lab --assert code --colors --coverage --threshold 100  --coverage-exclude-pattern **/*spec.js
```

 Thanks.

**Comment by geek** [comment]
@sfabriece with `--coverage-exclude` you can exclude using a pattern (https://github.com/hapijs/lab/blob/master/lib/coverage.js#L52-L54)

**Comment by sfabriece** [comment]
Thanks, I didn't know this 👍

**Comment by fabiomartins87** [comment]
Did you manage to make that **/*spec.js pattern work? I had the modify the internals.escape function in order not escape "." and "*" to make this work.
