### ISSUE TITLE
How can I inspect the result of the test that just ran?

### ISSUE THREAD

**Issue by maxbeatty** [hapijs/lab#667]
I'm trying to report to Sauce Labs whether an individual test passed. Is there some way I can tell if the test that just executed passed?

[This example mocha](https://github.com/ndmanvar/JS-Mocha-WebdriverJS/blob/c4b1185e5124031038fe2b81e5d8e1cd2dafb95a/tests/sample-spec.js#L41-L51) is where I got the idea. You can see [here](https://github.com/jsperf/jsperf.com/pull/317/files#diff-3bfe485fc29950b1fe0a67bbed2694adR23) where I have a similar setup with Lab.

**Comment by devinivy** [comment]
You can use the `-r` reporter flag to output the tests results in various formats.  You could also run a specific test on its own using the `-i` id flag, then check the command's exit code.

**Comment by maxbeatty** [comment]
I tried to use `Lab.report` on the current script in `afterEach` sorta like [here](https://github.com/hapijs/lab/blob/7c18c69f3be4a088b89839b4e3e0f9f8a88a3cc7/test/runner.js#L1251) but it seemed to infinite loop.

What may work for now is just flipping a boolean in each test:

```js
lab.experiment('asdf', () => {
  let passed;
  lab.beforeEach((done) => {
    passed = false;
    done();
  });

  lab.afterEach((done) => {
    console.dir('afterEach: ' + passed);
    done();
  });

  lab.test('1', (done) => {
    Code.expect(passed).to.be.false();
    Code.expect(1).to.equal(2);
    passed = true;
    done();
  });

  lab.test('2', (done) => {
    Code.expect(passed).to.be.false();
    Code.expect(1).to.equal(1);
    passed = true;
    done();
  });
});
```

**Comment by geek** [comment]
At the moment the report is only exposed to the reporters. This looks like a good candidate for a custom reporter for saucelabs. We support running tests with multiple reporters so you can output results in different ways.

Another approach may be to decorate the done function with the report state, but I am not sure if this is a good idea or not, thoughts?
