### ISSUE TITLE
How to lint transpiled typescript files

### ISSUE THREAD

**Issue by danielo515** [hapijs/lab#675]
Hello,

I was wondering if anyone here has experience with lab and typescript.
I can run the tests against the compiled code (both the tests and the source-code) but I the linter is failing. This is because the compiled code does not follow the hapi-linter rules. How can I run the linter against the original source or use an specific typescript linter on the sources?

Thanks in advance.

**Comment by corbinu** [comment]
You can either use https://github.com/palantir/tslint separately or I am some others are working on eslint support for typescript here: https://github.com/eslint/typescript-eslint-parser

Though it is still a work in progress.

**Comment by Horaddrim** [comment]
Is this still open? And if it is, What do you guys think about build a hapi-linter for TS, I can do it for sure!

**Comment by geek** [comment]
@Horaddrim I'm not a TypeScript developer so can't speak to the usefulness of a linter like that, but I say go for it! I won't directly integrate it into lab, but you can always run linting alongside your tests.

**Comment by Horaddrim** [comment]
Thank you man!
