### ISSUE TITLE
Do test files execute in the order in which they are specified on the command line?

### ISSUE THREAD

**Issue by thebinarypenguin** [hapijs/lab#678]
... and can a test abort the execution of further tests?

Consider the following example...
```
lab alpha.js bravo.js charlie.js
```

1. Will the files be executed left to right?
2. Can a test in alpha.js cause the whole chain to abort causing bravo.js and charlie.js to never get executed?

**Comment by geek** [comment]
@thebinarypenguin the order you specify the test scripts controls the order the scripts are loaded. To demonstrate the order you can do a dry-run with visual output: `-dv`... this outputs the index of each test case. By default, if a test fails in bravo it won't abort the test run, and the tests in charlie will execute. If you want the tests to abort/bail on the first failure you can pass the `--bail` command line argument.

**Comment by thebinarypenguin** [comment]
Can I use something like `process.exit(1)` in a test to abort/bail?

What I want is a test that always runs first and checks to see if it's running in a production-like environment and if it is then it should abort. because tests shouldn't be run in a production environment.

**Comment by geek** [comment]
@thebinarypenguin yep
