### ISSUE TITLE
Unable to override global require

### ISSUE THREAD

**Issue by danielo515** [hapijs/lab#679]
Hello,

I need to override global `require` function. I'm using `mockery` but I also tried to manually override it with any luck. Seems that lab executes all the code on a sandboxed environment where a special `require` function is provided. Known that, how can I properly override the global require function?

Thanks in advance.

**Comment by Marsup** [comment]
I'm guessing this is because of the coverage hook we add. See https://github.com/hapijs/lab/blob/master/lib/coverage.js#L27-L37, it should help you know what to override.

**Comment by danielo515** [comment]
Dear @Marsup ,

Thanks for your response, but it leaves me at the same exact point I was. I already inferred from the compiled code that the problem is the coverage hook, and I already took a look at the code snippet you provide. However, I don't know what to do with it: seems there is no way to access, intercept or modify the behavior of that function. Could you please help me a bit more?

**Comment by Marsup** [comment]
It would be easier if you provided sample code of what you're trying to achieve and precisely where it's failing.

**Comment by danielo515** [comment]
Sure, it is a quite simple and quite common mockup operation:

```js

const NodemailerMock = require('nodemailer-mock');

const _require = global.require;

global.require = (module) => {

    if ( module === 'nodemailer') {
        return NodemailerMock;
    }
    return _require(module);
};

```

**Comment by Marsup** [comment]
Looking at nodejs's code, I don't think you can override require this way. Have a look at [proxyquire](https://www.npmjs.com/package/proxyquire) instead.

**Comment by danielo515** [comment]
What do you mean with `looking at nodejs's code` ? This kind of override works perfectly outside the lab framework. If I just execute the test file with node testfile.js it works as expected. What does proxyquire differently ?

**Comment by danielo515** [comment]
Seems that proxyquire also encapsulates the modules being required. I'll give it a try and report back.

**Comment by danielo515** [comment]
Proxyquire worked perfectly.
You (I mean lab dev team) should consider including it as a recommendation for mock ups on the documentation.
