### ISSUE TITLE
TypeError: Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by tschaub** [hapijs/lab#685]
I just tried upgrading from 12.1 to 13.0 and ran into this issue.  See also https://github.com/hapijs/lab/commit/324c9ecbc87058fb5d8347287b9afa73bca08fe9#commitcomment-21272280

I didn't debug further, but it looks like the `reduce((a, b) => a + b)` call [in coverage.js](https://github.com/hapijs/lab/blob/37605456c5fb45279d4c1805b4423d5a55175dbe/lib/coverage.js#L337-L355) will fail if `tree.comments` is an empty array.

**Comment by geek** [comment]
@tschaub thanks for reporting... this is now fixed and published in v13.0.1
