### ISSUE TITLE
[Request] Can I add xit?

### ISSUE THREAD

**Issue by WesTyler** [hapijs/lab#687]
Sorry to necro-bump #458 , but I wanted to ask this question with as much context as possible.

Would you be open to me extending Lab with an equivalent of Mocha's `xit` for marking tests as pending quickly and easily? This contrived example is overly simplified for clarity, but we run into cases where we are adding some tests and would like to mark 10-12 or more as `pending` to circle back around to later. Adding the `x` is just a super simple muscle memory I have from working with Mocha previously. 

```js
const it = Lab.it;
const xit = Lab.xit;

describe('SUT', () => {
    it('should do something', (done) => { /*test*/});
    it('should do something else', (done) => { /*test*/});
    xit('should do something I am also working on, but not yet', (done) => { /*test*/});
});
```
```
..-

2 tests complete (1 skipped)
```

I'm guessing the answer is no:
> Our goal with lab is to keep the execution engine as simple as possible, and not try to build an extensible framework.

but you never know if you don't ask. :)

**Comment by Marsup** [comment]
That's the skip feature, already there.

**Comment by geek** [comment]
@WesTyler we offer `.skip` on the tests.

```
const it = Lab.it;

describe('SUT', () => {
    it('should do something', (done) => { /*test*/});
    it('should do something else', (done) => { /*test*/});
    it.skip('should do something I am also working on, but not yet', (done) => { /*test*/});
});
```

**Comment by WesTyler** [comment]
Ah, cool. I didn't see the `.skip` part. That's better than the `{skip: true}` param I was seeing in the other issue. I was willing to be lazy enough to replace a param in the tests with a single letter, but since `.skip` is there I don't feel the need to be _*that*_ lazy. :)

Thanks guys. I'll close this out and use the existing feature.

**Comment by WesTyler** [comment]
Oh, and for anyone (*cough cough* me) looking for this in the future, this totally works:

```js
const it = Lab.it;
const xit = it.skip;

describe('SUT', () => {
    it('should do something', (done) => { /*test*/});
    it('should do something else', (done) => { /*test*/});
    xit('should do something I am also working on, but not yet', (done) => { /*test*/});
}); 
```
