### ISSUE TITLE
plan and Lab.assertions not working

### ISSUE THREAD

**Issue by skaterdav85** [hapijs/lab#693]
I'm trying to use the "plan" feature but I get an error. Here is my test:

```js
const Code = require('code');
const Lab = require('lab');
const lab = exports.lab = Lab.script();

lab.experiment('math', () => {
  lab.test('returns true when 1 + 1 equals 2', { plan: 1 }, (done) => {
    Code.expect(1 + 1).to.equal(2);
    done();
  });
});
```

and then I run "lab". I get this:

```
Test script errors:

Expected 1 assertions, but no assertion library found
      at lab.test (/Users/david/Sites/testing-with-lab/test/example-test.js:17:5)
      at runCallback (timers.js:651:20)
      at tryOnImmediate (timers.js:624:5)
      at processImmediate [as _immediateCallback] (timers.js:596:5)
```

Do I need to tell the `lab` variable about which assertion library I am using?

I also noticed `Lab.assertions.expect` doesn't work either.

```js
const Code = require('code');
const Lab = require('lab');
const lab = exports.lab = Lab.script();
const expect = Lab.assertions.expect;

lab.experiment('math', () => {
  lab.test('returns true when 1 + 1 equals 2', (done) => {
    Code.expect(1 + 1).to.equal(2);
    done();
  });
});
```

I get `TypeError: Cannot read property 'expect' of null`. Clearly I am missing something. I'm just not sure what it is. Thanks.

**Comment by cjihrig** [comment]
Are you passing `-a code` from the command line?

**Comment by skaterdav85** [comment]
@cjihrig yes I've tried that. I still get this error: `Expected 1 assertions, but no assertion library found`

**Comment by geek** [comment]
@skaterdav85 what version of lab are you running? I tried to reproduce on the latest version of lab and code and didn't encounter the issue with your code.

```
lab plan.js -a code


  .

1 tests complete
Test duration: 8 ms
Assertions count: 1 (verbosity: 1.00)
No global variable leaks detected
```

**Comment by skaterdav85** [comment]
@geek I am running the following:

```
lab: 13.0.1
node: 7.5.0
npm: 4.1.2
nvm: 0.31.0
```

**Comment by geek** [comment]
@skaterdav85 thanks for the update. What version of code are you using. I tried again and still no luck...

```
lab: 13.0.1
node: 7.5.0
code: 4.0.0
```

```
$ cat plan.js
const Code = require('code');
const Lab = require('lab');
const lab = exports.lab = Lab.script();

lab.experiment('math', () => {
  lab.test('returns true when 1 + 1 equals 2', { plan: 1 }, (done) => {
    Code.expect(1 + 1).to.equal(2);
    done();
  });
});

$ npm i lab@13.0.1

$ npm i code@4.0.0

$ ./node_modules/.bin/lab plan.js -a code


  .

1 tests complete
Test duration: 9 ms
Assertions count: 1 (verbosity: 1.00)
No global variable leaks detected
```

**Comment by skaterdav85** [comment]
Well I got it working after reinstalling a few weeks later, so I'm not sure what the problem was. Different error now though. When I run it with `./node_modules/.bin/lab plan.js`, it works. When I install lab globally like in the README and run `lab plan.js`, it says `Cannot find module 'code'`. Does that mean I have to install `code` globally too?

**Comment by Marsup** [comment]
You shouldn't install those things globally anyway :trollface:

**Comment by skaterdav85** [comment]
@Marsup Ah ok. Should the README be updated to remove that? :)

**Comment by Marsup** [comment]
I would say so yes, it's a very bad advice, and when you start with node you don't know any better.
