### ISSUE TITLE
domain support for native promises

### ISSUE THREAD

**Issue by ORESoftware** [hapijs/lab#695]
Hey all, I hear you use domains to trap test errors. That is a great use case for domains.
I am not sure if you already have support for domain propagation for ES6 promises.

Just came up with this yesterday and wanted to share in case this is something you might be looking for:

```js

// monkey-patch then()

const then = Promise.prototype.then;
Promise.prototype.then = function (fn1, fn2) {

  if (process.domain) {
    fn1 = fn1 && process.domain.bind(fn1);
    fn2 = fn2 && process.domain.bind(fn2);
  }

  return then.call(this, fn1, fn2);
};
```

you can test it like so:

```js

const then = Promise.prototype.then;
Promise.prototype.then = function (fn1, fn2) {

  if (process.domain) {
    fn1 = fn1 && process.domain.bind(fn1);
    fn2 = fn2 && process.domain.bind(fn2);
  }

  return then.call(this, fn1, fn2);
};

process.on('uncaughtException', function(err){
    console.log(' This is uncaught => ', err);
});


const domain = require('domain');

const d = domain.create();

d.on('error', function(err){
  console.error(' => Domain caught => ',err);
});


d.run(function(){

  Promise.resolve().then(function(){
     process.nextTick(function(){
       throw new Error('rah');    // gets caught by the domain! fantastic
     });
  });

});

```

pretty nice right? :)

**Comment by Marsup** [comment]
Pretty nice indeed, though it wouldn't work if people are using bluebird, would it ?

**Comment by ORESoftware** [comment]
Bluebird already has domain support :) and has had it for some time.

**Comment by Marsup** [comment]
How do you even detect that those are native promises ?

**Comment by ORESoftware** [comment]
Not sure about native promises but you can check if it's Bluebird with:
https://github.com/petkaantonov/bluebird/issues/1365

I am sure you can do something like that with native promises.

`global.Promise.isNative`

would be nice, if it existed.

**Comment by geek** [comment]
@ORESoftware node version 8 now has promise support in domains

**Comment by ORESoftware** [comment]
@geek  thanks, yeah not sure if it's the exact same functionality, I will have to experiment
