### ISSUE TITLE
Extending linting

### ISSUE THREAD

**Issue by rankida** [hapijs/lab#696]
Hi.

I have created a eslint plugin for lab https://www.npmjs.com/package/eslint-plugin-lab and I have been thwarted rolling it out because in the lab documentation it shows a global install (here)[https://github.com/hapijs/lab#usage] but if I add my plugin to my `.eslintrc` file, as described in the (lab documentation)[https://github.com/hapijs/lab#extending-the-linter] then when my colleagues use the global install it fails to look in the local collection of plugins, even though it is picking up the local `.eslintrc` file.

Is this by design? How is it recommended to extend the linter for global usages?

**Comment by Marsup** [comment]
It should be removed, it's not a good practice to use lab globally. Past that, loading of the plugins is left to eslint, so I guess the note in http://eslint.org/docs/user-guide/configuring#configuring-plugins applies.
