### ISSUE TITLE
Node 8 will add `WebAssembly` global

### ISSUE THREAD

**Issue by cjihrig** [hapijs/lab#697]
The leaks will need to be updated for this.

**Comment by danielo515** [comment]
This report is poor and does not help in any way. 
Which versions of hapi are affected ? From which version is it fixed ?
 Regards

**Comment by Marsup** [comment]
Nice necrobumping. The report is clear, so is the fix, who said it affected hapi, and the version is on the right.

**Comment by danielo515** [comment]
@Marsup I didn't saw the the milestone thing, my bad.

I said that affects hapi by mistake, I wanted to say joi

**Comment by Marsup** [comment]
Again, what does it have to do with joi ?

**Comment by danielo515** [comment]
Dam! I don't know what happens today with my connection between my brain and my hands, sorry. lab, lab, I mean lab. Sorry for the double confusion

**Comment by Marsup** [comment]
Lab is also not affected, node 8+ is, which the report says.

**Comment by danielo515** [comment]
Then I will re-say that the report is not clear. Is not clear if this is a new vulnerability which needs to be added to the list of vulnerabilities, or if its a bug that reports a fake vulnerability and it only happens on node 8, or if it is a vulnerability in node 8 itself. Maybe for people familiar with the project one line is enough to understand what is it about, but not for the rest of us.

**Comment by Marsup** [comment]
What makes you think it's a vulnerability?

**Comment by danielo515** [comment]
This sentence:

> The leaks will need to be updated for this.

Regards

**Comment by Marsup** [comment]
Lab contains leak detection, that's all there is to it.

**Comment by danielo515** [comment]
I think this will be easier if you explain me what is the intention of the issue, and I'll be very grateful

**Comment by Marsup** [comment]
I literally just did, lab contains leak detection, there's a new global in node 8, we add it to the list.
