### ISSUE TITLE
Unexpected failure: Multiple callbacks or thrown errors received in test "App it composes a server" (done)

### ISSUE THREAD

**Issue by millette** [hapijs/lab#702]
I had this test running perfectly with lab 13.0.2 and earlier:
```
const Lab = require('lab')
const Code = require('code')
const Composer = require('../index')

const lab = exports.lab = Lab.script()

lab.experiment('App', () => {
  lab.test('it composes a server', (done) => {
    Composer((err, composedServer) => {
      Code.expect(composedServer).to.be.an.object()
      done(err)
    })
  })
})
```

I upgraded to 13.04 and now that test is failing with:
> Multiple callbacks or thrown errors received in test "App it composes a server" (done)

I tried 13.0.3 and same problem, introduced by #699.

Am I using Lab wrong?

**Comment by geek** [comment]
I like to 
```
Code.expect(err).to.not.exist();
```

Does `err` exist in this example? Is Composer executing the callback twice?

**Comment by millette** [comment]
```err``` is null. I reached out to @jedireza the maintainer of the generator I used, he might have an idea.

**Comment by millette** [comment]
Source for Composer, basically it's calling Glue (../index.js):

```
const Glue = require('glue')
const Manifest = require('./manifest')
const composeOptions = { relativeTo: __dirname }
module.exports = Glue.compose.bind(Glue, Manifest.get('/'), composeOptions)
```

**Comment by Marsup** [comment]
Can't reproduce with only glue. Can you provide a repo that exhibits this error ?

**Comment by geek** [comment]
@millette please reopen when there is more information to reproduce
