### ISSUE TITLE
Validating exception behaviour for uncaught exceptions

### ISSUE THREAD

**Issue by rjrodger** [hapijs/lab#703]
Hi @geek 

I'm refining the error handling in http://senecajs.com and need to validate that an `uncaughtException` remains uncaught. Specifically, when a user supplied callback throws, I want that to bubble up all the way to the top, so I need to validate that the exception does not incorrectly get caught somewhere.

Here's the simplest case: if I have test case that contains:

```
    setImmediate(function() {
      throw new Error('foo')
    })
    // somehow validate that Error.message === 'foo'
```

Then how do I capture and validate that Error? It seems to end up directly in your execution Domain, looking at the lab code.

**Comment by rjrodger** [comment]
More context; this is the test I want to add to http://github.com/senecajs/gate-executor

```
  it('errors', function (done) {
    try {
      GateExecutor()
        .add({
          fn: function foo (done) {
            throw new Error('foo')
          }
        })
        .start()
    }
    catch(e) { // maybe?
     expect(e.message).to.equal('foo')
      done()
    }
  })
```

**Comment by Marsup** [comment]
Lab will always intercept the error, I would say your best chance is to run it in a separate child process and assert the exit code, stdout, stderr, ...

**Comment by geek** [comment]
@rjrodger here are some possible solutions:

```
'use strict';

const Code = require('code');
const Domain = require('domain');
const Lab = require('lab');

const lab = exports.lab = Lab.script();
const it = lab.it;
const expect = Code.expect;

it('can validate async thrown error', (done) => {
  const domain = Domain.create();
  domain.once('error', (err) => {
    expect(err.message).to.equal('foo');
    done();
  });

  domain.run(() => {
    setImmediate(() => {
      throw new Error('foo');
    });
  });
});

it('can validate thrown error', (done) => {
  try {
    throw new Error('foo');
  } catch(e) {
    expect(e.message).to.equal('foo');
    done();
  }
});
```
