### ISSUE TITLE
Error when doing code coverage: "ecmaVersion must be 3, 5, 6, or 7."

### ISSUE THREAD

**Issue by kbmmdwork** [hapijs/lab#705]
See my comment on this thread https://github.com/hapijs/lab/issues/676

Essentially, I resolved the issue by forcing npm to install the latest version of espree (3.4.3).  I believe the fix for lab will be for it to depend on 3.4.3 (or whatever minimum resolves this issue) because, although, 3.1.7 satisfies the dependency requirement (3.x.x) that isn't sufficient to do the code coverage without getting this error.

Also, I had to downgrade lab to 12.1.0 (13.x.x isn't generating any code coverage - clover.xml file is empty and html report is also empty)

**Comment by Marsup** [comment]
Then reinstall your dependencies, lab depends on whatever 3 (https://github.com/hapijs/lab/blob/master/package.json#L19).

**Comment by Marsup** [comment]
Sorry, missed something in your comment. You should go complain to jsdoc, this is not really lab's fault.

**Comment by kbmmdwork** [comment]
Thanks @Marsup - I used rm -rf node_modules and re-installed dependencies

**Comment by kbmmdwork** [comment]
@Marsup - right, but can't lab work around the problem by depending on a newer version of espree?

**Comment by Marsup** [comment]
That's not the policy of this organization, I don't know if @geek will make an exception. FWIW jsdoc seems pretty dead right now, isn't there an active fork somewhere ?

**Comment by kbmmdwork** [comment]
OK, I see what you're saying... I didn't realize that it was our project that was using jsdoc - so we're essentially downgrading the espree version by depending on it.  Still, I don't see why lab "allows" a version of espree that is lower than what it really requires to function correctly.

**Comment by Marsup** [comment]
Fair enough, espree seems to bump ecmaVersion on minors, so I guess we should pin on `3.4.x`, any opinion @geek ?

**Comment by geek** [comment]
I'm fine pinning to 3.4.x for espree.
