### ISSUE TITLE
setting coverage-path doesn't include all code in path

### ISSUE THREAD

**Issue by danielb2** [hapijs/lab#710]
I'm setting coverage-path to `--coverage-path lib`. As a result, I'm expecting ALL files in the `lib` dir to be part of the coverage report.

Actual behavior:
Files not required in the test files are not covered. 

https://github.com/danielb2/lab-example

It would also be useful to be able to specify multiple paths to include coverage for

**Comment by geek** [comment]
I think this a reasonable idea, any files under the coverage-path will be traversed and required. It will be breaking as coverage percentages might change and break existing builds. I wonder if we should add an option for opting-in or out of this auto-require behavior.

**Comment by jcollum-cambia** [comment]
My 2 cents: automatic with opt-out. We were just discussing why we have to manually exclude code in ./test path but the code in my ./src path isn't automatically included in coverage.

**Comment by joshrivers** [comment]
What if we added a `--coverage-all-path` flag, leaving `--coverage-path` with it's current behavior. Later iterations could deprecate --coverage-path and migrate users forward?
