### ISSUE TITLE
Include code assertion library

### ISSUE THREAD

**Issue by geek** [hapijs/lab#712]
Most users of lab use code, we should include it and export the expect function from lab. Additionally, we should default to code as the assertion library when running tests. People should be able to opt-out of code as the assertion library as they can today. This will be breaking as the default test behavior will change to enable assertion checks by default

**Comment by Marsup** [comment]
What is it trying to fix ? I haven't seen people complaining about this.

**Comment by geek** [comment]
@Marsup I was speaking with a couple of lab users and that was one of their biggest gripes, since most users of lab are also using code, it does make sense.

**Comment by Marsup** [comment]
OK, felt like 5.0 was coming back to haunt us :) (looking at the PR it's not quite that)
