### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by marcopiraccini** [hapijs/lab#714]
When running tests that must generate errors I have this annoying warning: 

`UnhandledPromiseRejectionWarning: Unhandled promise rejection`

The behaviour is correct, only this warning is printend out in output. There's a way to avoid this? 

(actually `process.removeAllListeners('warning')` works, but I'd like to have a better solution)

**Comment by cjihrig** [comment]
You can do it from the command line. Run `node --help | grep deprecation` to see the availabl options. You'll probably want to use `--no-deprecation`.

**Comment by geek** [comment]
@marcopiraccini you can also add `--trace-warnings` to get a stack trace (https://nodejs.org/api/cli.html#cli_trace_warnings). `node --trace-warnings node_modules/.bin/lab`

**Comment by marcopiraccini** [comment]
`node --no-warnings ./node_modules/.bin/lab` did the trick
