### ISSUE TITLE
Upgrade to ESLint v4

### ISSUE THREAD

**Issue by devinivy** [hapijs/lab#715]
That's right, eslint v4 is out! http://eslint.org/blog/2017/06/eslint-v4.0.0-released / http://eslint.org/docs/user-guide/migrating-to-4.0.0

I assume lab will want to follow suit.  The upgrade path doesn't look terrible– primarily some close reading to double-check nothing will break!  I'm open to helping with this as time allows, provided lab does actually plan to upgrade in the near-term.

**Comment by geek** [comment]
@devinivy good timing, I was updating lab last night, finishing it up now.
