### ISSUE TITLE
Support for module preloading?

### ISSUE THREAD

**Issue by itsachen** [hapijs/lab#723]
Hi,

I was wondering if there was a suggested pattern for preloading modules prior to testing. In my case I have a setup file that initializes libraries and sets globals that are necessary for tests to run. I would like to preload that module prior to running my test suite.

In other testing frameworks there is an option to preload a specific module before executing the main test suite (see [mocha](https://mochajs.org/#usage)). Is there a way to do something similarly in lab?

**Comment by ORESoftware** [comment]
You can probably use node --require 

https://nodejs.org/api/cli.html#cli_r_require_module

**Comment by itsachen** [comment]
Yeah...I guess one option is to call `lab` from node (ex. `node --require ./path/to/setup node_modules/lab/bin/lab`)

**Comment by ORESoftware** [comment]
Yeah, I am not very familiar with LabJS, but I thought you could run individual tests with node.js. But I guess if you want to run a group of tests you must use the lab executable. In that case, yeah, LabJS should probably give you the abilty to pre-load files. 

Maybe check the Lab docs, they might expose node exec flags, something like this:

`lab --exec-args="--require your-pre-load-module"  your-tests`

**Comment by cjihrig** [comment]
I don't think something like `--exec-args` makes the most sense since Node is already running by that point, and lab doesn't spawn child processes for all of the tests. I think a better solution would be to expose a flag in lab that would `require()` one or more modules prior to running the tests themselves. I don't think we'd be able to preload different modules on a per test/suite basis though.

**Comment by itsachen** [comment]
Yeah I was thinking more along the lines of a `--require` flag.

> I don't think we'd be able to preload different modules on a per test/suite basis though.

I think thats fine as well. It'd still be convenient to be able to preload modules before the entire suite.

**Comment by varshard** [comment]
What's the status of this request?

**Comment by geek** [comment]
@varshard I'm going to close this because you can use `node -r` to preload a module with lab:

```
node -r somemodule node_modules/.bin/lab
```
