### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by vforv** [hapijs/lab#731]
It would be good if we can changed default runner... Instad node to use ts-node... Is that possible?

**Comment by geek** [comment]
I don't want to make it the default. But we could possibly add ts-lab that uses ts-node...

**Comment by vforv** [comment]
That would be great. Currenly we need to compile typescript files, then to run lab and on the end to delete js files. And with lint command we don't access to ts files just to plain js...

Maybe also you can add it as a argument... Something like this lab --runner="ts-node", if that possible...

**Comment by geek** [comment]
Another option is to use `ts-node test/` to run your tests

**Comment by vforv** [comment]
I am able to perform test like this:
`ts-node server.test.ts`
But then I have problem with options from lab:
`lab -a code -t 100 -L -v -T`
I don't know how to add test coverage and linting?

**Comment by geek** [comment]
What issues do you run into with test coverage?

**Comment by vforv** [comment]
I cover with test some part of code but it still marked as not covered....

**Comment by geek** [comment]
@vforv can you provide more details to help me reproduce, some example code and more details on your setup (versions)

**Comment by vforv** [comment]
@geek I created github repo hapi-seneca-ts... It is starter for seneca, hapi and typescript. Here is repo:
https://github.com/vforv/hapi-seneca-ts

Check readme file how to run it and run tests. Also if there is something that I can imporve or add pls open tickets, I am glad to hear new suggestions...

**Comment by geek** [comment]
@vforv I ran the tests in api-gateway and see 96% coverage, what lines are showing they are missing coverage but are actually covered?

**Comment by vforv** [comment]
plugins/routes/index.ts missing coverage on line(s): 22, 23, 24

It is plugin function:
```

private _register(server: HapiServer, options: any) {
        // Register
        return 'register';
}
```
But I think I cover it with this test(test/routePlugin.ts): 
```

 L.test('Route plugin should work', (done) => {

        expect(plugin['_register']).to.be.a.function();
        expect((plugin as any)._register()).to.be.a.string();  //HERE
        done();
    });

```
