### ISSUE TITLE
Excluding files/folders from being loaded

### ISSUE THREAD

**Issue by irothschild** [hapijs/lab#736]
Is there a way to exclude js files from being loaded? I can exclude them from coverage but they still seem to be loaded in testFiles.forEach (/node_modules/lab/lib/cli.js:121)

I have some third-party website files that I'm serving (all inside a "public" folder) that include some js files that reference globals defined in other files. When I run my tests, I get:

```
ReferenceError: SomeGlobalVar is not defined
```
since it tries to load every *.js file.

**Comment by geek** [comment]
You can use `-P, --pattern - only load files with the given pattern in the name.`, which is a regex test that we run (https://github.com/hapijs/lab/blob/master/lib/cli.js#L90) when loading test files.

**Comment by irothschild** [comment]
I can't get this to work due to the fact that -P only works on the base filename and I can't get negative patterns to work since the pattern is modified as:

```
    options.pattern = options.pattern ? '.*' + options.pattern + '.*?' : '';
```

**Comment by geek** [comment]
@irothschild is the file that you don't want to load a test file or something that will be loaded from tests? The pattern would only apply to test files being loaded.

**Comment by irothschild** [comment]
The file is not a test file and is not loaded from any tests. It's just some website resources.
But when I call lab, it loads every js file.

My lab call is:
```
lab -c lib
```

**Comment by geek** [comment]
@irothschild ok, that makes sense. Are your tests in `lib` ? Typically we put test files in `test` and then lab will automatically pick them up: `lab -c`

**Comment by geek** [comment]
If that is the case, you will want to run with a pattern to only include those paths:

```
lab -c -P test
```

**Comment by irothschild** [comment]
Unfortunately that only works if the tests are all in files containing 'test' in the name since pattern only matches on the base filename and not the path.

**Comment by geek** [comment]
`lab lib/test lib/plugin*/test -c`

**Comment by irothschild** [comment]
Ah, that worked. 👍
