### ISSUE TITLE
Please add an explanation of verbosity; what does 'verbosity: 3.00' mean?

### ISSUE THREAD

**Issue by jcollum-cambia** [hapijs/lab#737]
I found it in the PR `notebook.assertions / totalTests`, so I'm doing 3 assertions per test on average. 

OK, but what does it mean? Is more verbosity good? Is there a number that's considered "good enough"? I'm just curious because I've never heard this term before. 

[Googling for it just brings up a ton of python pages.](https://www.google.com/search?q=what+is+unit+test+verbosity&oq=what+is+unit+test+verbosity+&aqs=chrome..69i57.5173j0j7&sourceid=chrome&ie=UTF-8)

**Comment by geek** [comment]
What is considered good is largely up to you and your preference. Some people prefer that a test is very specific and only testing one thing, which means the verbosity level should be very low. If a test has a large number of assertions then the reasons for a failure may be more complex to determine than a test with a single assertion. The verbosity number is a good indicator of tests becoming overly complex. Again, this is entirely up to you and what you prefer as well as what you are testing, some tests will naturally have a lot of asserts.

**Comment by jcollum-cambia** [comment]
I think it would be worth an addition to your docs. As I said, google isn't any help here. Still isn't, [even after adding this issue.](https://www.google.com/search?q=labjs+verbosity&spell=1&sa=X&ved=0ahUKEwjgzI-ZkuvVAhUG4GMKHRCsDVMQBQglKAA&biw=1008&bih=873)

**Comment by jcollum-cambia** [comment]
> geek added the documentation label a minute ago

Thanks 👍
