### ISSUE TITLE
Junit reporter ignore code coverage

### ISSUE THREAD

**Issue by vforv** [hapijs/lab#738]
I don't get any result for code coverage in juint reporter... In console works fine but not when use reporter.

**Comment by geek** [comment]
@vforv the JUnit format doesn't support code coverage: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

Do you have an updated JUnit format that includes coverage?

**Comment by vforv** [comment]
@geek my mistake, I tought it is covered by JUnit.

**Comment by geek** [comment]
@vforv I'm surprised they haven't extended it, doesn't seem like that much is involved to add. If you do find that it is supported please reopen and I can add support.
