### ISSUE TITLE
can guarantee the order of how tests are loaded/exec'd ?

### ISSUE THREAD

**Issue by miqui** [hapijs/lab#741]
use case:
i want to ensure test.js is loaded first, then i can load the remaining tests files in any order.

is this possible? ... thanks,

**Comment by geek** [comment]
@miqui yes, you can pass in the files/directories you want to test in the order you want them tested.

```
lab test/test.js test/
```

Another option is to use the node require feature (https://nodejs.org/api/cli.html#cli_r_require_module)
