### ISSUE TITLE
Remove domains in favor of try/catch on async/await

### ISSUE THREAD

**Issue by geek** [hapijs/lab#752]

**Comment by Marsup** [comment]
Is it really necessary that lab also follows that ? I know domains are a pain but this is forcing the style of tests you're allowed to do.

**Comment by geek** [comment]
I don't think we will want to remove the `done` callback style, but instead I am going to try to promisify these callbacks and use async/await with try/catch instead of domains. Thoughts?

**Comment by Marsup** [comment]
This is going to force a massive rewrite of all the tests under the hapi.js umbrella, we're probably going there anyway, but still. It will also force many people using lab outside of our own ecosystem to follow that style, this is ultimately a hard choice.

**Comment by geek** [comment]
The breaking change will be because we are dropping support for pre-node 8 engines. Everything else should stay functionally the same

**Comment by Marsup** [comment]
If you remove domains you can either say goodbye to callbacks or parallel, I don't see a way around that.

**Comment by geek** [comment]
@Marsup in v15 I will remove support for callbacks in the tests and expect a promise only. That said, I will keep supporting lab v14

**Comment by Marsup** [comment]
Where will any uncaught exception appear ?

**Comment by geek** [comment]
They will still appear in the console and will fail the test where they appeared from.

**Comment by Marsup** [comment]
Without domains? How can that be?

**Comment by geek** [comment]
...They fail the test executing when the exception occurs.

**Comment by Marsup** [comment]
The keyword in my sentence was "uncaught" :wink:

**Comment by geek** [comment]
@Marsup https://github.com/geek/lab/blob/3e82389b56fd762e0a9e32e32cc9e7307343b1d1/lib/runner.js#L564

**Comment by Marsup** [comment]
OK so no parallel anymore, got it.

**Comment by AdriVanHoudt** [comment]
Unless in multiple processes?
