### ISSUE TITLE
Async function with a child function

### ISSUE THREAD

**Issue by glennjones** [hapijs/lab#753]
Came across an interesting problem where a async function that has child function evaluate in the browser context cannot be tested without error. The first code block is based on a pattern suggested in docs [Puppeteer](https://github.com/GoogleChrome/puppeteer).  Both sets of code run fine from node, its only within a Lab/Code test I have an issue.

I could not get the test below run in Lab against without error
``` javascript
async function getPageDimensions (url){
   const browser = await Puppeteer.launch();
   const page = await browser.newPage();
   await page.goto(url);
   const dim = await page.evaluate( () => {
      return {
         width: document.documentElement.scrollWidth,
         height: document.documentElement.scrollHeight
      }
   });
   browser.close();
   return dim
}
```
The error I get running Lab against the above function is: 
```
rror: Evaluation failed: ReferenceError: global is not defined
    at <anonymous>:2:13
    at <anonymous>:6:11
    at Frame._rawEvaluate (/Users/gjones/Desktop/node/site-parser-fetch/node_modules/puppeteer/lib/FrameManager.js:250:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Works when I change the `page.evaluate` to a `string` this can be tested 
``` javascript
async function getPageDimensions (url){
   const browser = await Puppeteer.launch();
   const page = await browser.newPage();
   await page.goto(url);
   // This was rewritten to work with Lab 
   const dim: any = {};
   dim.width = await page.evaluate(`document.documentElement.scrollWidth`);
   dim.height = await page.evaluate(`document.documentElement.scrollHeight`);
   browser.close();
   return dim
}
```

I have a work around and this could be a obscure edge case cause by an issue with puppeteer, Wonder if anyone has an idea about whats going on

**Comment by geek** [comment]
@glennjones unless puppeteer adds properties to the node global this makes sense. The page evaluation function will happen outside of the page context in the first example.
