### ISSUE TITLE
null request query in Pre functions

### ISSUE THREAD

**Issue by hatimox** [hapijs/lab#756]
hello 

I'm using Lab to write some API tests and my routes have a Pre function , and i'm getting always a null req.query here is my pre function code : 

```
    const get_store_token = function (req, rep) {
        
        var store = req.query.shop_id || req.payload.shop_id; 

        if(store == 'undefined' ){
            rep(boom.create(400, "shop parameter is missing"));
        };

        model.get_store_token(store).then(
            data => {
                console.log(JSON.stringify(data));
                let item = data.Items[0];
                return rep(item.shop_token);
            }
        ).catch((err = new Error()) => {
            boom.create(400, err.message, err);;
        });
    };
```

my code for the Test : 

```
        it('return shopper object when user found', (done) => {

            let options = {
                method: 'GET',
                url: '/shopper',
                payload: {
                    uid: '5590099717',
                    shop_id : 'hh-delightme'
                }
            };

            server.inject(options, (response) => {
                expect(response).to.have.property('data');
                done();
            });

        });

    });
```

> { message: 'An internal server error occurred',
  statusCode: 500,
  error: 'Internal Server Error' }
Debug: internal, implementation, error 
    TypeError: Uncaught error: Cannot read property 'shop_id' of null
    at get_store_token (/home/hatim/delightme.io/services/shopper/index.js:16:53)

can anyone help me? 

thanks

**Comment by geek** [comment]
@hatimox your test code doesn't set a querystring value for shop_id

**Comment by hatimox** [comment]
thanks for your reply, but how I can set a query string on my test?

to be honest, I don't found a lot of documentation about lab and how to use it to test API 

thanks

**Comment by geek** [comment]
@hatimox the same way you would when making a request using your browser. `?`

**Comment by hatimox** [comment]
`describe('GET /shopper', () => {

        it('return shopper object when user found', (done) => {

            let options = {
                method: 'GET',
                url: '/shopper?uid=5590099717&shop_id=hh-delightme'
            };

            server.inject(options, (response) => {
                //console.log(response);
                expect(response).to.have.property('data');
                done();
            });

        });

    });`
