### ISSUE TITLE
Request to consolidate parsers

### ISSUE THREAD

**Issue by cjihrig** [hapijs/lab#762]
There is a parser configuration for the [linter](https://github.com/hapijs/lab/blob/97cea6085264bc37eac5deceaa8707da5e4ec426/lib/linter/.eslintrc.js#L5-L7), and another parser configuration for [coverage](https://github.com/hapijs/lab/blob/3d8b49e3b6c52aef817f01575b8ce3d831d9eb7c/lib/coverage.js#L254-L257).

Is it possible to consolidate the parsers, or at least the options, in one place so that they don't become out of sync?

**Comment by Marsup** [comment]
I second that one as I had this issue on object spreading being supported by coverage and not linting.
