### ISSUE TITLE
Can't get pretty output when inside mongoose callback

### ISSUE THREAD

**Issue by icetbr** [hapijs/lab#773]
```
    lab.test('mongoose', function (done) {
        require('mongoose').model('anyName', {}).find({}, function (err, result) {
            expect('1').to.equal('2');
            done();
        });
    });
```
Expected
```
      actual expected

      "12"
```
Actual
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Expected '1' to equal specified value
    at .<anonymous> (/home/me/projects/it/node_modules/code/lib/index.js:199:17)
```

lab@14.3.1
code@4.1.0
hoek@4.2.0
mongoose@4.11.12

**Comment by geek** [comment]
@icetbr are you passing any flags to lab when you run your tests?

**Comment by icetbr** [comment]
I was (timeout, globals, bail) + nodemon, disabled them all, same thing.

**Comment by Marsup** [comment]
This looks like it's uncaught, mongoose has quite a few issues related to error catching, I wouldn't be surprised if it was a bug on their side.

**Comment by icetbr** [comment]
Just out of curiosity, how does the flow works? Shouldn't lab catch the error and present it to the user? You're saying that mongoose should have caught the error and prevented it from being thrown? Could I somehow catch it and call lab's pretty printer?

**Comment by Marsup** [comment]
I'm not saying mongoose should have caught it, quite the opposite, I'm saying it does, probably by interfering with what lab uses, and I have no idea why it does what it does.
