### ISSUE TITLE
assertion library "code" is not set by default / documentation is wrong

### ISSUE THREAD

**Issue by MLKiiwy** [hapijs/lab#778]
The current documenation says :  "By default the assertion library code"

If you check the code : 
- https://github.com/hapijs/lab/blob/master/lib/cli.js#L172
- https://github.com/hapijs/lab/blob/master/lib/cli.js#L446 

The assert options is null by default, that mean no assertion lib is added by default. So all the examples in the readme fails because you need to specify the assertion lib with "lab -a code" (+ install it because code is a devDependency in this package).

Two options to fix it : change the doc, or change the code

**Comment by Marsup** [comment]
This is a breaking change in lab 15, documentation needs to be updated. If anyone wants to do it before Wyatt gets to it... ;)
