### ISSUE TITLE
server.inject doesn't response at all

### ISSUE THREAD

**Issue by panthercms-andy** [hapijs/lab#780]
I am using lab and code to write test, they work fine but somehow the server.inject function has no response at all. It didn't even show the 'hello' log. Could anyone help please? Thank you.

```
const Lab = require('lab')
const expect = require('code').expect
const { describe, it } = exports.lab = Lab.script()
it('/assets should list assets', (done) => {
        server.connection({ port: 3000 })
        server.register(ApiPlugin, err => {
            expect(err).to.not.exist
            const options = {
                method: 'GET',
                url: '/assets'
            }

            server.inject(options, (response) => {
                console.log('hello')
                expect(response.statusCode).to.equal(200)
                console.log(response)
                const result = response.result

                console.log(result)
                done()
            })
        })
    })
```

**Comment by geek** [comment]
@panthercms-andy what version of lab are you using?

**Comment by panthercms-andy** [comment]
"code": "^5.1.0",
"lab": "^15.1.0",

**Comment by geek** [comment]
@panthercms-andy in lab 15 we dropped support for the `done` function and instead expect a promise to be returned if you are performing asynchronous operations. You can install lab 14 and the above test will work. Also, lab 14 will still receive bug fixes for the nearterm if you want to continue to use it.
