### ISSUE TITLE
Test suite stops with no error when using --inspect (14.3.1)

### ISSUE THREAD

**Issue by jcollum** [hapijs/lab#781]
**14.3.1** (I know there is a new version but I can't upgrade at this point in my project)

Command with output: 

```sh
node_modules/.bin/lab -Rv --ignore __core-js_shared__ -e dev --timeout 60000 -r console --verbose --inspect ./test/unit ./src/listener-factory/test/unit "-g" "message with a member_id"
Debugger listening on port 9229.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/7d7c5481-d69d-437a-8fc4-cf16d52bdaca
Debugger attached.
```

I am popping over to the debugger window after the `To start debugging` line. Then I hit the "use strict" at the top of the lab file (`lab/bin/lab`). I then hit go and it processes a little and dies.

 And that's it -- then we're back to the command line. I've successfully debugged lab tests before. 

I've tried `Pause on Caught Exceptions` -- results in a lot of stops in Joi's `safeParse` function. No idea if that's normal. If I turn off the exception pausing and hit go the process dies. 

I'm not sure what's happening. I just see no errors. The tests run fine (but fail assertions) when run without `--inspect`. 

What can I do to figure out what is happening here?

**Comment by geek** [comment]
Please reopen if this is still an issue with the latest lab. Sorry for the _long_ delay in even responding :(

**Comment by jcollum** [comment]
That's ok I forgot about it and I don't work there anymore :)
