### ISSUE TITLE
Documentation on using --id

### ISSUE THREAD

**Issue by rapilabs** [hapijs/lab#788]
For someone who's quite new to the hapi ecosystem I can't seem to obtain any information on how to use the `--id` flag with `lab`.  It looks as though the help text assumes you know how to specify an id on a test.  An example may be helpful here :)

**Comment by geek** [comment]
@rapilabs I'll update the docs, but you can get the ID of a test by running lab in verbose mode. Then each test will display the ID that relates to it, next you can use the `-i` argument to run only that test or a range of tests:

`lab -v`
`lab -i 1-3,5`
