### ISSUE TITLE
How we add lab option programmatic

### ISSUE THREAD

**Issue by Akash0333** [hapijs/lab#791]
I have create a bootstrap file for run tests. But when test are executed its show only 2 option .

**1 tests complete
Test duration: 40 ms**

I want see more details without run npm test command . Like files name which have been executed and more details on output screen

**Comment by Marsup** [comment]
Use verbose mode.

**Comment by Akash0333** [comment]
But i didn't run any command like ("lab unit.js"). Bootstrap file byDEFAULT run my test code when i start my server.

**Comment by Akash0333** [comment]
Output Screen Shot
![screen shot 2017-11-28 at 9 46 48 am](https://user-images.githubusercontent.com/13021367/33302328-39204780-d421-11e7-8b90-1c45c2da3269.png)

**Comment by Marsup** [comment]
This is never how you should write tests. Don't mix tests and application code.
See lab's examples or own tests to get an idea how to do it. There are also plenty of articles on the internet to explain how tests in nodejs should be done.

**Comment by Akash0333** [comment]
But my system are plugin based so i can't export all file into test files
