### ISSUE TITLE
awaiting a rejected promise can still pass test

### ISSUE THREAD

**Issue by rankida** [hapijs/lab#812]
The following test "passes" in lab@15.2.2 when I would _not_ expect it to as it `awaits` a rejected promise
```JavaScript
it.only('lab should mark as fail, but doesn`t', async () => {

    let rejectP;
    const p = new Promise((resolve, reject) => {

        rejectP = reject;
    });
    setTimeout(rejectP, 5); // if I passed a param to rejectP the test would fail

    await p;

    console.log("never called - but test passes");
    throw new Error('This test should fail, but passes');
});
```
What happens is that `await p` results in an uncaught exception, but because `rejectP` was called with no parameter then all the checks like `if (err ` in the runner pass.

A quick hack for me would be to add the below `|| 'rejected'` to [lib/runner.js#L581](https://github.com/hapijs/lab/blob/master/lib/runner.js#L581)
```JavaScript
return finish(ex || 'rejected');
```

I am happy to prepare a PR if you are agreeable. Let me know.

**Comment by lerouxb** [comment]
Both of these pass too:

```
'use strict';

const { describe, it } = exports.lab = require('lab').script();

describe('throw', () => {

  it('should not pass (async)', async () => {

    throw null;
  });

  it('should not pass (sync)', () => {

    throw null;
  });
});
```

**Comment by rankida** [comment]
This has rather dangerous in my opinion because it gives a false sense of success and unless you are following strict TDD and watching it go red first then you can easily think a feature is working when it is not.

For this reason I have opened a PR - https://github.com/hapijs/lab/pull/813
