### ISSUE TITLE
Node v8.10.0 Leaking Errors detected: SharedArrayBuffer, Atomics

### ISSUE THREAD

**Issue by sebastianneb** [hapijs/lab#818]
Hello everyone,

since the release of Node version 8.10.0 today/yesterday our leaking tests in a simple Test Project are not working anymore, since there are leaking errors. With Node 8.9.4 everything worked fine and as expected. The error is: 

3 tests complete
Test duration: 23 ms
The following leaks were detected:SharedArrayBuffer, Atomics
Coverage: 100.00%

package.json (only necessary parts):
"dependencies": {
    "codacy-coverage": "^2.1.0",
    "express": "^4.16.2",
    "express-healthcheck": "^0.1.0"
  },
  "devDependencies": {
    "chai": "^4.1.2",
    "dockerfile_lint": "^0.3.0",
    "eslint": "^4.18.2",
    "lab": "^13.1.0",
    "nodemon": "^1.17.1",
    "ntl": "^1.2.0",
    "sinon": "^4.4.2",
    "coveralls": "3.0.0"
  },
  "scripts": {
    "test": "lab -r console -o stdout -r html -o build/report/coverage.html -r lcov -o build/report/lcov.info"
  }

Node Version: 8.10.0
NPM-version: 5.6.0

Has someone a idea what is wrong here or how to fix this error?

**Comment by Marsup** [comment]
You should bump to lab@14.

**Comment by sebastianneb** [comment]
Yep, that fixed the problem, Thanks!

**Comment by danielo515** [comment]
Any particular version of la 14.x ? I'm already using 14.3.1 an the problem persist
@sebastianneb which one are you using currently ?

**Comment by cjihrig** [comment]
It looks like you need v15.1.2, based on https://github.com/hapijs/lab/commit/1193a9a9343f3a4f4412c21c72ece11c4f9010ca.

**Comment by sebastianneb** [comment]
We are currently on 14.3.2 and it works.

**Comment by cjihrig** [comment]
Ah, I didn't see https://github.com/hapijs/lab/commit/ec2726c4b515141eea7e8da7f9b19fbb0f8963bb. I didn't realize 14.x.x was still being maintained. In that case, yes, 14.3.2 has the necessary change.

**Comment by danielo515** [comment]
I can confirm that 14.3.1 does not work, but 14.3.3 does. So for me the fix was to install 14.3.3

**Comment by shaunbruno** [comment]
Looks like out of the box example is failing:
```
const { expect } = require('code');
const lab = exports.lab = require('lab').script();

lab.test('returns true when 1 + 1 equals 2', () => {
    expect(1 + 1).to.equal(2);
});
```

on `node -v => v8.11.2` and `"lab": "^15.5.0"`

```
1 of 1 tests failed
Test duration: 8 ms
The following leaks were detected:SharedArrayBuffer, Atomics
```

**Comment by Marsup** [comment]
@shaunbruno can't reproduce. Check `lab --version`, you're likely not using the version you think you do.

**Comment by shaunbruno** [comment]
@Marsup sorry to randomize - you are correct. The global version was out of date.
