### ISSUE TITLE
linter issues

### ISSUE THREAD

**Issue by csrl** [hapijs/lab#835]
I have the following issues when attempting to use lab's linter capabilities.

1. Can not customize what files should be checked for linting.  For example, running eslint directly, I simply use:  `eslint ./bin ./lib ./test` However lab by default runs on the current directory [1](https://github.com/hapijs/lab/blob/7214ef406d28151dd0205c1004aed8b7f7bfc522/lib/linter/index.js#L36),[2](https://github.com/hapijs/lab/blob/d043fb0d7c41f5b55022b67a944ced030c060c26/lib/cli.js#L39) which includes things in my project that should not be linted.

2. Attempting to use a custom linter with the --linter option can not work, because of two reasons.
   a) --linter-options is forced to JSON object which is not compatible with anything but the built in linter module.
   b) --lint-fix is forced assigned to the parsed linterOptions [3](https://github.com/hapijs/lab/blob/7214ef406d28151dd0205c1004aed8b7f7bfc522/lib/lint.js#L31), which again is specific to using the builtin linter module.  If it wasn't for this, then at least --linter-options could have been given as a quoted string, allowing it to be JSON parsed as a string and passed to the specified linter.

**Comment by geek** [comment]
1. The linting feature in lab went from a general purpose tool for everyone, to a linting option designed for hapi projects. That being said, custom `.eslintrc` configurations are respected as well as `.eslintignore` files. You can use the ignore file to exclude certain paths, which allows you to run the lab linter today without the need for extra paths in the arguments.

2. You are right on the limitations of the `linter-options` and `lint-fix`. This goes back to our narrowing the scope of the built-in linter to fit the needs of hapi projects. What I usually do on non-hapi projects is to have a `lint` script in my `package.json` and to have a `pretest` script that is simply `npm run lint`. 

I hope this helps.

**Comment by csrl** [comment]
Thanks @geek for the explanation.  Perhaps some clarification in the documentation would be good.  As it stands, the lint related parameters make it seem like its extensible for other use cases.  If its specific to hapi, then I don't see why there are options to customize/replace the linter etc.  I'd even think it should move towards including 'hapi' in the linter parameter naming.

eg `-L, --lint-hapi - run hapi linting rules using linter. Disabled by default.`

And delete the `-n, --linter - specify linting program file path; default is eslint.` option all together - or is there a use case that hapi projects use different linters?
