### ISSUE TITLE
Node v10.2.1 leaks detected

### ISSUE THREAD

**Issue by danielo515** [hapijs/lab#839]
Hello, 

I'm using lab 14.3.3 and when I run my tests on node 10.2.1 I get the following errors/leaks

`The following leaks were detected:URL, URLSearchParams`

Is this a real leak or is it just some weird behavior related to the node version ? I'm not using any of those functions at any place.

Thanks and regards

**Comment by geek** [comment]
@danielo515 you'll need to update to the latest lab, which includes all of the node 10 globals in the leak detection. If you prefer to disable leak detection you can run lab with the `--leaks` argument

**Comment by danielo515** [comment]
So there is no way to back port them to the 13.x branch I guess...
Thanks

**Comment by Marsup** [comment]
13 ? You said 14 in the OP.

**Comment by danielo515** [comment]
Yes, 14,sorry mistyped

**Comment by Marsup** [comment]
There's a 14 branch, so as usual, if you want something to be done, do it. We consider people using node 8 and above should be on lab 15, so any "nice to have" (as opposed to security issues) is to be done by people needing it.

**Comment by danielo515** [comment]
> We consider people using node 8 and above should be on lab 15

I can understand that you are an open source project and you can not invest on maintaining all the versions. However I don't understand why just because you are using certain node version you should migrate all your tests to a new version of lab with breaking changes. My code works perfectly on any version of node starting at 8,so I don't see why the libraries I use could not. 

Regards

**Comment by Marsup** [comment]
Your argument doesn't stand, node takes many years to remove features, so of course your code is going to work for the foreseeable future, maybe decades, that doesn't mean we should support that with our limited resources. We only support the latest version except for security issues, if you want something, do it.

**Comment by danielo515** [comment]
Hello @Marsup, that was my first sentence, I understand that, as an open source project, you can not offer support for all the versions except the latest. I'm absolutely fine with that. My point is that I don't see how that should be related with the node version I'm using.
I'll try to make a pr to the 14.x branch

**Comment by Marsup** [comment]
Lab 15 is just a better fit for node 8 and above, it uses modern features of the platform, it's where all our investment goes, sticking to old versions just because you can isn't a rational decision.

**Comment by danielo515** [comment]
It's not because we can, it's because as you se have limited resources. We are a small company, with small team, but we have dozens of repositories, and all of them are using lab 14. We can't just update all our tests to the latter version as soon as we want. Of course is something I would love to do, but it takes time. Out templates needs to be updated too and everything should remain  consistent,not an easy task.

I just want to make clear that we really like lab, and we think you are making an terrific work. 

Regards

**Comment by Marsup** [comment]
Then if you're not ready to move, add exceptions, I know [I did](https://github.com/hapijs/joi-date-extensions/blob/master/package.json#L31) because I needed to stay backward compatible. It's not like you're out of options.

**Comment by danielo515** [comment]
That is exactly what I need! 
Thank you very much
