### ISSUE TITLE
Leaks detected with Node.js 10.5.0

### ISSUE THREAD

**Issue by JbIPS** [hapijs/lab#841]
Hi,

I recently upgraded my project to Node.js 10.5.0 and suddenly my lab results found some leaks:
```
The following leaks were detected:BigUint64Array, BigInt64Array, BigInt, URL, URLSearchParams
```
Those looks like internal classes and weren't detected as leaks with Node.js 9.4.0. I can ignore them for now but maybe there is a better way to clean this.

What should/could I do? Thanks

**Comment by cjihrig** [comment]
> What should/could I do?

Update your version of lab.
