### ISSUE TITLE
Coverage fails for multiple conditionals on same line (logical operators)

### ISSUE THREAD

**Issue by icetbr** [hapijs/lab#842]
Hi, I think this is a known issue. If so, it might me useful to leave this open or fix through a known issues doc.

![labcoverage](https://user-images.githubusercontent.com/1111617/42048887-d888f064-7ada-11e8-8218-98662c1a9bc8.png)

Related
https://github.com/gotwarlost/istanbul/issues/311
https://github.com/sc-forks/solidity-coverage/issues/175

**Comment by Marsup** [comment]
Coverage checks for truthy and falsy case, you're only covering the truthy case according to the color, it was written in the tooltip.

**Comment by icetbr** [comment]
I could have been more specific. My issue is that the same test reports differently for the two styles of code that represent the same thing.

`request.quey.c` should have been green.

This would give me 100% cover
a = true
b = true
c = true

a = true
b = false
c = true

a = false
b = false
c = true

**Comment by geek** [comment]
In the latest lab this case is now correctly detected: https://github.com/hapijs/lab/pull/878
