### ISSUE TITLE
Coverage being analized on the test file

### ISSUE THREAD

**Issue by danielo515** [hapijs/lab#853]
Hello,

I am getting problems with coverage analysis. I am using `.spec.js` files close to my files being tested. This is very convenient and lab was easy to configure for this setup. However today I have added a new file and lab is reporting that some lines at that file are missing coverage. 
This is weird not only because (IMO) test files should not be tested for coverage, but the reported lines are actually being executed, so I'm a bit puzzled here.

Here is the header of the file, it includes the lines that are being reported as uncovered:

```js

describe ('== CSV-paginator', () =>
{
    const fields = { page: 'page', pageSize:'pageSize', total: 'total' };
    describe ('=== Input validation', () =>
    {
        it ('Should throw when fields argument is incorrect', _ =>
            expect ( () => paginate ({})).to.throw (Error, /not a member of ‘\{ page/i) );
        it ('Should throw when second argument is missing',   _ =>
            expect (paginate (fields)).to.throw (Error, /applied to the wrong number of arguments/i));
        it ('Should throw when pageSize argument is not a number',   _ =>
            expect (() => paginate (fields) (i => i) ('blah')).to.throw (Error, /The value at position . is not a member of ‘Integer’/i));
        it ('Should throw when command argument is not an object',   _ =>
            expect (() => paginate (fields) (i => i) (10) ('blah')).to.throw (Error, /The value at position . is not a member of ‘Object’/i));
    });

```

This is how I execute lab:

```json
    "test": "lab --assert code --coverage --pattern spec --default-plan-threshold 1 -t 80 -v src",
```

I tried excluding the file without luck

```json
    "test": "lab --assert code --coverage --pattern spec --default-plan-threshold 1 --coverage-exclude paginator.spec.js -t 80 -v src",
```

I'm using

code@5.2.0
 lab@15.5.0

Thanks in advance
Regards

**Comment by danielo515** [comment]
I just generated a coverage report, and here are the lines that are not being covered

<img width="995" alt="captura de pantalla 2018-08-27 a las 17 16 23" src="https://user-images.githubusercontent.com/2270425/44668221-0e91a680-aa1d-11e8-84a9-0a72e04227a9.png">

As  I said, those lines are being executed because the assertion count is correct

```
  === Input validation
    ✔ 1) Should throw when fields argument is incorrect (44 ms and 1 assertions)
    ✔ 2) Should throw when second argument is missing (13 ms and 1 assertions)
    ✔ 3) Should throw when pageSize argument is not a number (13 ms and 1 assertions)
    ✔ 4) Should throw when command argument is not an object (24 ms and 1 assertions)
```

I just noticed that the other spec files are also being included, but they have 100% code coverage.
Can this be an issue on lab trying to cover lines that are modified by itself ?

**Comment by geek** [comment]
Fixed by https://github.com/hapijs/lab/pull/881
