### ISSUE TITLE
Unable to get the error while the payload is required

### ISSUE THREAD

**Issue by ashish1391agrawal** [hapijs/lab#859]
i am using the latest version of lab,code, shot with hapijs version 17.5.2. when i try to test the following code in which the value in payload field is required but after giving it to null or blank it's not giving the error  nor response 
![issue](https://user-images.githubusercontent.com/39453318/44981960-ced53c80-af91-11e8-8acd-cb144cac5aee.png)
and also getting verbosity and coverage =0.  

i am using following code:
const Lab = require('lab');
const Code = require('code');
const Shot = require('shot');

const lab = exports.lab = Lab.script();

lab.experiment('Search module', () => {
  lab.test('should search', (done) => {
    const options = {
      method: 'GET',
      url: '/api/challenges/search',
      payload: {
        q: null,
      },
    };

    Shot.inject(options, (response) => {
      console.log('testing the search api', response);
      Code.expect(response.statusCode).to.equal(200);
      done();
    });
  });

and the result  what i am getting in picture

**Comment by geek** [comment]
In the latest lab we've moved to `async`/`await`. What is happening in this code is that no promise is returned and therefore nothing is awaiting completion. You will need to rewrite it into something like: https://github.com/hapijs/shot/blob/master/test/index.js#L77
