### ISSUE TITLE
Lab Support on Jetbrains IDE

### ISSUE THREAD

**Issue by ronayumik** [hapijs/lab#862]
I've been using jetbrains ide for several projects, and most of them uses mocha as test runner, and I can run a particular block of test(s) easily by clicking this button:
![image](https://user-images.githubusercontent.com/11717652/47209951-daeb5100-d3bb-11e8-970d-df93bfe4581d.png)

However, if I open a project that uses Lab, the `run` button/icon is not found:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/11717652/47209845-9d86c380-d3bb-11e8-816d-5b1d077c9d19.png">

is there anyone that also encountered this kind of issue? And how do you fix it, or is it indeed lab is not supported by jetbrains ide?

Thank you

**Comment by geek** [comment]
I suspect that this is an integration that jetbrains worked on. With lab you can run individual tests by their index, but you'd likely need to pass that into jetbrains so that it will know what test number to run.
