### ISSUE TITLE
Assertions in rejection are always failing test

### ISSUE THREAD

**Issue by simranjeet2589** [hapijs/lab#887]
Hello,

We have recently migrated to lab v17.3.0 and are experiencing following behaviour:

When you have an assertion in catch block, the test are failing even if the assertion is passed. This was working in the lab v14.

```
it("assertion in catch", () => {
      return fun().catch(err => {
        expect(err.message).to.equal("foo bar");
      });
    });
  });
```

Could you please validate it or point to a documentation which can explain this behaviour?

Thanks and Regards

**Comment by montumodi** [comment]
We are also experiencing the same behavior when we migrate to lab 17.

**Comment by Marsup** [comment]
Works for me: https://runkit.com/embed/cvwmzovn7br6
This issue needs a better reproduction.

**Comment by simranjeet2589** [comment]
@Marsup Thanks for looking into it. Looks like we have another buggy code in our app causing the error.

Closing this issue now.
