### ISSUE TITLE
Stack trace shows node internals for Promises on node 10

### ISSUE THREAD

**Issue by dominykas** [hapijs/lab#896]
I haven't yet dug deeper, but opening an issue now so that I don't forget, just in case I find time for this... The stack trace on node 10 is pretty useless:

node `v10.13.0`:

```
  58) Definitions parse() validates cookie values:

      Expected [Promise] to reject with an error

      at internal/process/next_tick.js:68:7
```

node `v8.12.0`:

```
  58) Definitions parse() validates cookie values:

      Expected [Promise] to reject with an error

      at /Users/dominykas/devel/projects/hapijs/statehood/test/index.js:621:31
```

I _think_ this is the responsibility of lab, right?

**Comment by cjihrig** [comment]
@dominykas are you using `code` as your assertion library? If so, can you try making a one line change from https://github.com/hapijs/code/pull/131/files and let me know if it makes a difference?

**Comment by dominykas** [comment]
Indeed this works 👍
