### ISSUE TITLE
Make coverage pluggable

### ISSUE THREAD

**Issue by garthk** [hapijs/lab#902]
If we could replace `coverage.js` with an API-compatible module at runtime (cf: custom reporters and transform modules), we could experiment with [native v8 coverage without an extra transpile step](https://github.com/nodejs/node/pull/25157). In turn, that could plausibly fix #856 as a side-effect.

**Comment by geek** [comment]
@garthk I do want to add support to run coverage through the new v8 coverage, this should also make it easier to track coverage in child processes

**Comment by hueniverse** [comment]
I would love to use v8 native coverage. This will happen after we stop supporting node 8 in a few months. I do not want to make coverage pluggable as you can already do that by simply not using lab for coverage...
