### ISSUE TITLE
Add affordance for coverage flag stack

### ISSUE THREAD

**Issue by skeggse** [hapijs/lab#904]
If I configure a transform using `-T` with `babel`, I might want to have babel comment out portions of the code it generates with `auxiliaryCommentBefore` and `auxiliaryCommentAfter` so that `lab` doesn't try to lint the generated code. Separately, I might sometimes want to disable coverage for actual application code. If I put the two together, it's possible that a block of code that has linting disabled gets re-enabled by the generated code's comments:

```js
// input:
/* $lab:coverage:off$ */
const { types } = Util;
export const isSet = (types && types.isSet) || internals.isSet;
/* $lab:coverage:on$ */



// output:
/* $lab:coverage:off$ */
const {
  types
} =
/*$lab:coverage:off$*/
_util
/*$lab:coverage:on$*/
.
/*$lab:coverage:off$*/
default
/*$lab:coverage:on$*/
;
const isSet = types && types.isSet || internals.isSet;        // This line gets linted, even though it shouldn't have been.
/* $lab:coverage:on$ */
```

I'm curious whether there's an existing solution to this problem.

If not, would we be open to adding support for `/* $lab:coverage:push$ */` and `/* $lab:coverage:pop$ */` comments (name unimportant), which would create a running stack of flag states that auto-generated code could use to avoid mucking with the user's intended coverage state?

**Comment by geek** [comment]
@skeggse thanks for raising this. In the case of the above example how would you use the push and pop to solve the problem? It sounds like a good approach, I'd just like to see an example with it being used.

**Comment by skeggse** [comment]
I was imagining it looking something like this:

#### Input

```js
/* $lab:coverage:off$ */
const { types } = Util;
export const isSet = (types && types.isSet) || internals.isSet;
/* $lab:coverage:on$ */
```

#### Output

```js
/* $lab:coverage:off$ */
const {
  types
} =
/*$lab:coverage:push$/
/*$lab:coverage:off$*/
_util
/*$lab:coverage:pop$/
.
/*$lab:coverage:push$/
/*$lab:coverage:off$*/
default
/*$lab:coverage:pop$*/
;
const isSet = types && types.isSet || internals.isSet;
/* $lab:coverage:on$ */
```

All of the above occurrences of `$lab:coverage:pop$` would restore the state of the coverage flag from the corresponding `push$`, and set the state back to `off`. In more interesting cases, multiple tools might be manipulating the source and interleaving multiple operations where the coverage could turn on and off "inside" an existing pushed state.

This is kinda inspired by [`#pragma pack(push, xx)`](https://docs.microsoft.com/en-us/cpp/preprocessor/pack?view=vs-2017) (with corresponding `#pragma pack(pop, xx)`) but a little lighter-weight.

**Comment by geek** [comment]
@skeggse this looks like a fine approach to the problem. Thank you for explaining it with an example. I'm open to this solution and getting it merged in and released.

Thanks!

**Comment by skeggse** [comment]
Sure! I'm happy to take a stab at this - unless you've already started on it?

**Comment by geek** [comment]
@skeggse I haven't started yet :/ Thank you for being willing to take a stab at it!

**Comment by skeggse** [comment]
Cool, no problem! I was mostly trying to understand whether your previous comment was a commitment to implementing this yourself or just an expression of interest in this solution becoming part of `lab`.

**Comment by hueniverse** [comment]
Ping to make sure this is still something you want to work on.
