### ISSUE TITLE
Best way to handle CRUD testing?

### ISSUE THREAD

**Issue by emrealparslan93** [hapijs/lab#907]
Hello, I want to write a test for my CRUD endpoints. But I want to test 'UPDATE', 'DELETE' endpoints rely on created document in 'CREATE' endpoint. 

For example:

```
let createdAccount = null;
it("should create an account", async () => {
  const response = await Server.inject({
    method: "POST",
    url: "/v1/accounts",
    payload: JSON.stringify({
      name: "TEST",
      email: "test@test.com"
    })
  });
  expect(response.statusCode).to.equal(200);
  expect(response.result).to.a.object();
  expect(response.result._id).to.exists();
  createdAccount = response.result;
});

it("should delete an account", async () => {
  const deleteResponse = await Server.inject({
    method: "DELETE",
    url: `/v1/accounts/${createdAccount._id}`
  });
  expect(deleteResponse.statusCode).to.equal(200);
  expect(deleteResponse.result).to.a.object();
  expect(deleteResponse.result._id).to.exists();
});
```

What's the best way to handle this? Should I create a test case which is rely on another one's result?

**Comment by geek** [comment]
lab has the concept of a [context](https://github.com/hapijs/lab#context) object that you can attach values to in a `before` function and pass into tests. If you have a few tests that rely on some setup behavior and need access to variables from the setup, then try using `context`. Below is an example of how this could look:

```
it("should create an account", async () => {
  const response = await Server.inject({
    method: "POST",
    url: "/v1/accounts",
    payload: JSON.stringify({
      name: "TEST",
      email: "test@test.com"
    })
  });
  expect(response.statusCode).to.equal(200);
  expect(response.result).to.a.object();
  expect(response.result._id).to.exists();
});

describe('account deletion', () => {
	before(async ({ context }) => {
		const response = await Server.inject({
		    method: "POST",
		    url: "/v1/accounts",
		    payload: JSON.stringify({
		      name: "TEST",
		      email: "test@test.com"
		    })
		});
		context.account = response.result;
	});

  	it("should be supported", async ({ context }) => {
	  const deleteResponse = await Server.inject({
	    method: "DELETE",
	    url: `/v1/accounts/${context.account._id}`
	  });
	  expect(deleteResponse.statusCode).to.equal(200);
	  expect(deleteResponse.result).to.a.object();
	  expect(deleteResponse.result._id).to.exists();
	});
});
```

In general I try to make sure each test can be isolated and run alone, this also makes it possible to use lab to run individual tests and debug individual conditions more easily with `lab -i {some test number}`. If you only have this one test for deletion, you may consider doing the setup within the test itself. Similarly, on the creation, you may want to add an after for the deletion. If deletion is common, you could always create a utility method that you can execute. 

There really is a lot of personal preference in what I'm recommending. I think at the end of the day, I'd just pick whatever approach will be easier for you to support and use to identify issues.

**Comment by emrealparslan93** [comment]
@geek thank you for your suggestions. I guess `context` is what I'm looking for. I'm rewriting my CRUD test with `before()` & `context`. Thank you.
