### ISSUE TITLE
share hapi server in context

### ISSUE THREAD

**Issue by kuryaki** [hapijs/lab#908]
I'm trying to set a shared server to test requests but the inject is not available in the tests

```javascript

before(async ({ context }) => {

    const server = new Hapi.Server();
    await server.register([
        {
             plugin: SimpleGetRoute
        }
    ]);
    context.server = server;
});

it('fails', ({ context: server }) => {
    expect(server.inject).to.exist();
});
```

Is this the expected behavior?

**Comment by devinivy** [comment]
I think you just have a little typo in there!
```diff
- it('fails', ({ context: server }) => {
+ it('fails', ({ context: { server } }) => {
    expect(server.inject).to.exist();
});
```

**Comment by kuryaki** [comment]
🤦‍♂️

**Comment by kuryaki** [comment]
ty @devinivy

**Comment by kuryaki** [comment]
actually did this and now I am facing a different error, also asked [here](https://stackoverflow.com/questions/55082866/using-the-lab-context-helper-for-hapijs-causes-an-error)

**Comment by devinivy** [comment]
Yes, I see what you're talking about.  It does seem like lab is deep-cloning `context`, which is giving you a cloned hapi server rather than an actual hapi server.  This might be a bug, feature, or something else—I'm not sure.  I think we'll have to wait to hear from @geek.

In the meantime, I suggest using a closure for this.  Define `let server;` out side of your `before()`, set it inside `before()`, then share the `server` by keeping it in scope of the relevant tests.

**Comment by kuryaki** [comment]
yes thats what I am doing right now, using a `let server`, thanks to, will love to hear about this because that `let` added a `no-let` exception to the linting :P

**Comment by geek** [comment]
@kuryaki the motivation for doing the clone on context for each test was to prevent one test from interfering with the context of another test. lab is using `Hoek.clone` to perform the clone of context.

Another option is to use a helper function that runs once to create the server:

```js
let getServer = async () => {
  const server = new Hapi.Server();
  await server.register(SimpleGetRoute);

  getServer = () => {
    return server;
  }

  return server;
};


it('works', async () => {
  const server = await getServer();
  expect(server.inject).to.exist();
});

it('also works', async () => {
  const server = await getServer();
  expect(server.inject).to.exist();
});
```

**Comment by kuryaki** [comment]
thanks @geek
