### ISSUE TITLE
It's possible to run lab on vscode?

### ISSUE THREAD

**Issue by afucher** [hapijs/lab#909]
Hi, 

I use VSCode, but I'm not able to find a way to run/debug the tests inside the tool. It's possible to do that?
If no, there is a plan for that?

**Comment by biddster** [comment]
I was looking at the same thing yesterday. I've got it working using a launch.json config:
```json
{
      "type": "node",
       "request": "launch",
       "name": "lab test",
       "runtimeVersion": "8.10.0",
       "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/lab",
       "args": ["-a", "code", "-L", "-v"],
       "outputCapture": "std"
}
```
It's far from perfect as the stdout from the test doesn't appear in the vscode debug console.

**Comment by geek** [comment]
There are a few options. The first is to use the `Tasks: Run Test Task`:
![image](https://user-images.githubusercontent.com/441346/55093141-d4a38400-5081-11e9-9dd8-a096d655f1bb.png)
It uses the test script in your package.json:
![image](https://user-images.githubusercontent.com/441346/55093158-dec58280-5081-11e9-8d48-0b247f8e5093.png)

The second is to use the npm extension and run tests with it
![image](https://user-images.githubusercontent.com/441346/55093655-d0c43180-5082-11e9-8a57-575a82d1d980.png)

Another option is to use an extension like https://marketplace.visualstudio.com/items?itemName=prashaantt.node-tdd which has lab support. 

Let us know if you find any better solutions, I use VSCode so am curious as well.
