### ISSUE TITLE
How to include hapi plugin coverage-path as array ?

### ISSUE THREAD

**Issue by sisplatform-support** [hapijs/lab#925]
I wrote hapi plugin as node_module which is registered while server initialized.

I want include hapi plugin in code coverage path but whic is expecting a string as single path, I am expecting like below.

"coverage-include": [
      "node_modules/@hapi/module-a",
      "node_modules/@hapi/module-b",
      "node_modules/@hapi/module-c"
  ]

I would appreciate if someone help me out.

**Comment by geek** [comment]
@sisplatform-support you might be able to set a `--coverage-pattern` to match those module paths. https://github.com/hapijs/lab#command-line

**Comment by sisplatform-support** [comment]
@geek  : By default node_modules excluded for coverage, Since you mentioned to use --coverage-pattern, Kindly help me out. how to use --coverage-pattern for specific node_modules instead of all dependent node_modules.

**Comment by geek** [comment]
For example if I want to check to see how much the tests in hapi use hoek I can run the tests with the following options:

```
$ lab --coverage-pattern "lib\/.*\.(js)$" --coverage-all --coverage-path node_modules/hoek/
```

You can try something like:

```
$ lab --coverage-pattern "hapi\/module\-a\/.*\.(js)$" --coverage-all --coverage-path node_modules/
```
