### ISSUE TITLE
Lab report showing incorrect information

### ISSUE THREAD

**Issue by ferrao** [hapijs/lab#931]
Lab report tells me that a condition in my code will always evaluate to `true`, but I believe this is not correct, bellow some sample code to validate.

`lib/index.js`
```
module.exports = function(response, options = {}) {
    const { key } = options;

    if (!Array.isArray(response) && !key) {
        throw Error('missing key')
    }

    if (key && !response[key]) {
        throw Error('wrong key')
    }
    
    // if (key) {
    if (key && !Array.isArray(response)) {
        return 1;
    }

    return 0;
}
```
`test/test.js`
```
const test = require("../lib");

describe("Testing lab coverage", () => {
  it("1 - valid object and key", () => {
    expect(test({ someKey: "xpto" }, { key: "someKey" })).to.equal(1);
  });

  it("2 - valid object and no key", () => {
    expect(() => test({ someKey: "xpto" })).to.throw();
  });

  it("3 - array and no key", () => {
    expect(test([])).to.equal(0);
  });

  it("4 - array and key", () => {
    expect(() => test([], { key: "someKey" })).to.throw();
  });

  it('5 - array and numeric key', () => {
       expect(test([1,2], { key: 1 })).to.equal(0);
  });
});
```
If I run the following test code through lab with ` ./node_modules/.bin/lab test -v -t 100` I am getting a missing coverage on line `if (key && !Array.isArray(response)) {` and if I generate a report with ` ./node_modules/.bin/lab test -v -t 100 -r html` I get on the same line an indication regarding `!Array.isArray(response)` - *Condition always true*.

As is, I can in fact remove the right side of the boolean expression and all tests will still pass.

If I uncomment the last test in the suite I now get 100% coverage and no indication regarding the condition.

But with this last test, I can not remove the right side of the boolean expression, as this last test will now fail, making my point that such condition is NOT always true.

**Comment by Marsup** [comment]
??

**Comment by ferrao** [comment]
> ??

Sorry, somehow I ended up submitting the issue with an empty body, but I have just edited everything.

**Comment by ferrao** [comment]
This old case #401 is probably related?

**Comment by Marsup** [comment]
I'm not sure I follow you, without your last test of course it's missing coverage. Either your function or your tests logic is flawed, but everything seems normal to me.

**Comment by ferrao** [comment]
What I am claiming is that without the last test, lab reports *Condition always true* which is wrong. If condition was always true as lab claims, I could remove it from my code. But I can not, because it will make that last test fail.

**Comment by Marsup** [comment]
But it is always true. There is never a case where you reach that if with a key and an array. Your test 3 has an array but no key.

**Comment by ferrao** [comment]
Forget about it... I was trying to come up with a more simple example that the actual code to explain what was happening, but I failed miserably at my example and I believe you are right that lab is doing the right thing (with my actual code and not the example I mean)....

**Comment by Marsup** [comment]
To explain further, lab checks logical coverage.
So with `if (a && b)` the possible scenarios are:

| a | b |
|-|-|
|true|true|
|true|false|
|false|not important|

You have case 1 and 3 but you're clearly missing the 2nd.

**Comment by ferrao** [comment]
Yes, I understand and it is how I expected coverage to work. 

What seemed wrong to me was not the coverage at all, but the _Condition always true_ message I was getting on the coverage report.

**Comment by Marsup** [comment]
Well, when it is reached, it's always true, when it's not the value has no point since it virtually doesn't exist. In terms of coverage, I think it's harder to differentiate between a value that's reached and false, and not reached, we could have an execution counter for each elements of conditionals but I'm not sure it would make it clearer.
