### ISSUE TITLE
Stupid typescript

### ISSUE THREAD

**Issue by hueniverse** [hapijs/lab#938]
Changing error codes without major because I guess they don't think anyone should be using error codes programmatically...

New error code 2769 added.

For people who care about strict typing, this is fucking absurd...

Disclaimer: I'm at the end of an 11 hours flight and this is not the kind of shit I need to solve 20 minutes before landing so I can fix a cascade of bugs in other modules.

**Comment by kanongil** [comment]
You should probably fix the typescript dependency to a major + minor version since typescript does not follow semver. See https://github.com/microsoft/TypeScript/issues/14116.

**Comment by hueniverse** [comment]
Good idea.
