### ISSUE TITLE
comma sepration issue in globals ignore

### ISSUE THREAD

**Issue by navneetgarggate6** [hapijs/lab#939]
I just checked that in latest version

**lab -I '__extends, __assign'** not working as there is a space after the comma this was working in previous version
although without space its working **lab -I '__extends,__assign'**

Just want to know so other users can change there code. This is also true for the .labrc.js

**Comment by hueniverse** [comment]
I don't see how. The line that does the processing has not changed in 5 years...

https://github.com/hapijs/lab/blame/master/lib/cli.js#L491

**Comment by navneetgarggate6** [comment]
Well I am getting following error when using following in my .labrc.js and my lab is "@hapi/lab": "^20.2.2"

module.exports={
  globals: '__extends, __assign',
};

The following leaks were detected:__assign

And when i replace the space than its working fine.

**Comment by hueniverse** [comment]
Space is not allowed.

**Comment by navneetgarggate6** [comment]
Ok, but it was working in previous version with space ("lab": "^15.4.0").

Also in error output contain spaces. So it creates confusion.

The following leaks were detected:__assign, __rest
