### ISSUE TITLE
code coverage can't reach 100% for this simple test

### ISSUE THREAD

**Issue by midnightcodr** [hapijs/lab#944]
I have the following codes (for simplicity I put the function into the test file)

```js
const Lab = require('@hapi/lab')
const { expect } = require('@hapi/code')
const lab = (exports.lab = Lab.script())

const sign = n => {
  if (n < 0) {
    return '-'
  } else if (n === 0) {
    return ''
  } else if (n > 0) {
    return '+'
  }
}

lab.experiment('tests', () => {
  lab.test('sign tests', () => {
    expect(sign(-1)).to.equal('-')
    expect(sign(0)).to.equal('')
    expect(sign(5)).to.equal('+')
  })
})
```

When I run `lab -c tests/sign.js`, I got 
Coverage: 94.74% (1/19)
tests/sign.js missing coverage on line(s): 10
Where line 10 is
```
  } else if (n > 0) 
```

I am pulling out my hair but can't figure out why Lab thinks my tests didn't cover that line. Ideas?

**Comment by hueniverse** [comment]
Probably it is always true or always false. Try using the html coverage reporter to get more details.

**Comment by midnightcodr** [comment]
@hueniverse , in the function it checks if input `n` is less than 0, equal to 0, or larger than 0. In my tests I cover all three scenarios (-1, 0 and 5). I still don't understand why line 10 is not covered. HTML report is here:

![Screen Shot 2019-09-24 at 2 40 38 PM](https://user-images.githubusercontent.com/1152119/65540400-519ca280-ded9-11e9-9227-b4ce6740e7e1.png)

**Comment by Marsup** [comment]
Mouse over the green area would have told you that. This condition is always true, I don't see how it couldn't be, unless you pass something else than a number that would make all 3 tests false.

**Comment by midnightcodr** [comment]
@Marsup thank you! Finally I got it. Here's the updated code that passes the tests:

```js
const sign = n => {
  if (n < 0) {
    return '-'
  } else if (n === 0.0) {
    return ''
  } else {
    return '+'
  }
}
```

**Comment by gerardolima** [comment]
hey, @midnightcodr, just a heads-up that you surely already know, but making equal comparison to floating point numbers might yield subtle approximation errors (i.e consider an aproximation to zero as 0.00000000000001). A safer approach could be:

```
const sign = n => {
  if (n < 0) {
    return '-'
  } else if ( Math.abs(n) < 0.000001 ) { // use your "zero" approximation here
    return ''
  } else {
    return '+'
  }
}
```

**Comment by midnightcodr** [comment]
@gerardolima good to know, I had a bit of hesitation when I used `n === 0` comparison. Thanks for pointing that out.
