### ISSUE TITLE
SonarQube compatible test execution report

### ISSUE THREAD

**Issue by arungeorge101** [hapijs/lab#973]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.14.0
* *module version*: 14.3.4
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*: SonarQube 7.9

#### What problem are you trying to solve?

Am trying to generate the unit test execution report that can be plugged into SonarQube so that the unit test execution results shows up in Sonar. 

For the coverage I generated the report using this in lab (-r lcov -o ./reports/coverage.lcov) and passed that report to sonar.javascript.lcov.reportPaths property. That worked fine and I can see the coverage in sonar. 

Now am trying to get the test execution part into sonar. As per the Sonar documentation,
https://docs.sonarqube.org/latest/analysis/coverage/ I need to generate the report based on the generic test format (https://docs.sonarqube.org/latest/analysis/generic-test/) and then pass the file to sonar.testExecutionReportPaths. I tried to use the lab xml reports generated by -r junit, -r clover but Sonar is unable to parse those xml reports.
We need a way to generate sonar compliant xml reporting.

lab -r sonar -o ./reports/execution.xml

```js
const some = 'properly formatted code example';
```

**Comment by hueniverse** [comment]
All I can suggest is to use one of the existing reports and write a script to change it to the expected format.

**Comment by arungeorge101** [comment]
If I spend time adding that report format in Lab code - will you consider
merging it in ?

**Comment by hueniverse** [comment]
Sorry but no. I am trying to keep it small and this is not a popular format.

**Comment by kiran8910** [comment]
> #### Support plan
> * _which support plan is this issue covered by?_ (e.g. Community, Core, Plus, or Enterprise): Community
> * _is this issue currently blocking your project?_ (yes/no): no
> * _is this issue affecting a production system?_ (yes/no): no
> 
> #### Context
> * _node version_: v12.14.0
> * _module version_: 14.3.4
> * _environment_ (e.g. node, browser, native): node
> * _used with_ (e.g. hapi application, another framework, standalone, ...): hapi
> * _any other relevant information_: SonarQube 7.9
> 
> #### What problem are you trying to solve?
> Am trying to generate the unit test execution report that can be plugged into SonarQube so that the unit test execution results shows up in Sonar.
> 
> For the coverage I generated the report using this in lab (-r lcov -o ./reports/coverage.lcov) and passed that report to sonar.javascript.lcov.reportPaths property. That worked fine and I can see the coverage in sonar.
> 
> Now am trying to get the test execution part into sonar. As per the Sonar documentation,
> https://docs.sonarqube.org/latest/analysis/coverage/ I need to generate the report based on the generic test format (https://docs.sonarqube.org/latest/analysis/generic-test/) and then pass the file to sonar.testExecutionReportPaths. I tried to use the lab xml reports generated by -r junit, -r clover but Sonar is unable to parse those xml reports.
> We need a way to generate sonar compliant xml reporting.
> 
> lab -r sonar -o ./reports/execution.xml
> 
> ```js
> const some = 'properly formatted code example';
> ```
> 
> #### Do you have a new or modified API suggestion to solve the problem?

@arungeorge101 Did you find an alternative to generate execution report for sonarQube?

**Comment by arungeorge101** [comment]
@kiran8910 Nope I havent, will let you know here if I get time to write it myself.
