### ISSUE TITLE
 The following leaks were detected:@@any-promise/REGISTRATION

### ISSUE THREAD

**Issue by SalathielGenese** [hapijs/lab#976]
#### Context

* *node version*: `node:erbium-alpine` (`v12.6.1`)
* *module version*:  `22.0.4`

#### What are you trying to achieve or the steps to reproduce ?

My story start when I wanted to complete a job test using Hapi.js instead of express... The job is long behind me. Also, part of the story is [right here](https://github.com/sequelize/sequelize/issues/11899#issuecomment-601628952). The next part is as follow...

`$ grep -rnE 'The following leaks were detected' node_modules`
```
node_modules/@hapi/lab/lib/reporters/console.js:295:            output += red('The following leaks were detected:' + notebook.leaks.join(', ')) + '\n';
```

So I added `console.log( new Error().stack )` right before that line... and got

```text
Error
    at module.exports.internals.Reporter.internals.Reporter.end (/opt/app/node_modules/@hapi/lab/lib/reporters/console.js:294:26)
    at module.exports.internals.Reporter.reporter.finalize (/opt/app/node_modules/@hapi/lab/lib/reporters/index.js:93:28)
    at Object.exports.report (/opt/app/node_modules/@hapi/lab/lib/runner.js:129:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/opt/app/node_modules/@hapi/lab/bin/lab:56:20)
```

I inspected the `internals.Reporter.internals.Reporter.end` function but could not see it setting any exit status.

So I tried `$ grep -rnE 'exit' node_modules/@hapi/lab` and there is a lot of match...

```text
node_modules/@hapi/lab/bin/lab:43:        process.exit(code);
node_modules/@hapi/lab/bin/lab:57:    process.exit(code);
node_modules/@hapi/lab/node_modules/.bin/eslint:56:    process.exitCode = 2;
node_modules/@hapi/lab/node_modules/.bin/eslint:94:        process.exitCode = cli.execute(process.argv, contents, "utf8");
node_modules/@hapi/lab/node_modules/.bin/eslint:100:        process.exitCode = 0;
node_modules/@hapi/lab/node_modules/.bin/eslint:102:        process.exitCode = 1;
node_modules/@hapi/lab/node_modules/.bin/eslint:107:    process.exitCode = cli.execute(process.argv);
node_modules/@hapi/lab/node_modules/source-map/CHANGELOG.md:232:  exit code.
node_modules/@hapi/lab/node_modules/source-map/dist/source-map.js:2045:    // return null, so we provide a flag to exit gracefully.
node_modules/@hapi/lab/node_modules/source-map/lib/source-map-consumer.js:601:    // return null, so we provide a flag to exit gracefully.
node_modules/@hapi/lab/lib/index.d.ts:37:         * Forces the process to exist with a non zero exit code on the first test failure.
node_modules/@hapi/lab/lib/reporters/clover/report.xml:4:        <metrics statements="{{cov.sloc}}" coveredstatements="{{hits cov.hits}}" conditionals="0" coveredconditionals="0" methods="0" coveredmethods="0" elements="{{cov.sloc}}" coveredelements="{{hits cov.hits}}" complexity="0" packages="{{packageCount}}" files="{{fileCount}}" classes="{{fileCount}}" loc="{{cov.sloc}}" ncloc="{{cov.sloc}}"/>
node_modules/@hapi/lab/lib/runner.js:103:            return process.exit(1);
node_modules/@hapi/lab/lib/cli.js:114:        process.exit(1);
node_modules/@hapi/lab/lib/cli.js:121:        process.exit(0);
node_modules/@hapi/lab/lib/cli.js:142:            return process.exit(1);
node_modules/@hapi/lab/lib/cli.js:158:            return process.exit(1);
node_modules/@hapi/lab/lib/cli.js:177:            description: 'exit the process with a non zero exit code on the first test failure',
node_modules/@hapi/lab/lib/cli.js:447:        process.exit(1);
node_modules/@hapi/lab/lib/cli.js:452:        process.exit(0);
node_modules/@hapi/lab/lib/cli.js:457:        process.exit(0);
node_modules/@hapi/lab/lib/cli.js:491:            process.exit(1);
node_modules/@hapi/lab/lib/cli.js:539:        process.exit(1);
node_modules/@hapi/lab/lib/cli.js:544:        process.exit(1);
```

So I instead tried

```js
process.exit = ( exit =>
    ( code ) =>
    {
        console.log( new Error().stack );
        exit( code );
    })( process.exit );
```

And I have my culprit

```text
Error
    at process.exit (/opt/app/src/server.js:9:90)
    at main (/opt/app/node_modules/@hapi/lab/bin/lab:57:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Now, line #56 just tells me that `@hapi/lab/lib/cli#run() returns an object with a `code` property.

- - -

Navigating the code had me travel to

```text
@hapi/lab/bin/lab:57
@hapi/lab/lib/cli:62
@hapi/lab/lib/runner:129
```

From there, `console.log( reporter.finalize.toString() )` shows that it is the implementation at

```text
@hapi/lab/lib/reporters/index:91
```

I did some `console.log` into the method's arrow function expression `const finalize` and got

```text
notebook.errors ::: []
notebook.failures ::: 0
notebook.leaks ::: [ '@@any-promise/REGISTRATION' ]
notebook.types ::: undefined
```

The tedious condition that follows also tests `(notebook.leaks && notebook.leaks.length)` and the condition body sets the `code` to `1`.

# QUESTION

What the hell is `@hapi/lab` leak ??? It doesn't seem documented anywhere. The doc says how to disable the feature I don't get why I need it in the first place. My node version already has `Promise` so I don't get it.

Thanks.

**Comment by cjihrig** [comment]
lab checks for leaked global variables. `any-promise` leaks a global variable, which lab detects. You can whitelist the individual global or disable global leak checking completely. Search in https://github.com/hapijs/lab/blob/master/API.md for "leak" for the flags to use.

**Comment by hueniverse** [comment]
@SalathielGenese next time, please find a more respectful tone. "What is the hell" is not a great way to ask for help.

**Comment by SalathielGenese** [comment]
Thank you @cjihrig. The edit is very insightful. Any change the documentation has a section on leaks.

Thank you @hueniverse to point it out. I am sorry to have shocked you. I was being sarcastic actually and meant not to be disrespectful.

Moreover, I highly esteem the work you guys are doing on `@hapi` [and I said it yesterday again, on Twitter.

So, again, I did not intend to look down on anyone nor this project.

Thank you.
