### ISSUE TITLE
Not recursing to locate test files

### ISSUE THREAD

**Issue by stevendesu** [hapijs/lab#979]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: v13.11.0
* *module version with issue*: v22.0.4
* *last module version without issue*: Unknown
* *environment* (e.g. node, browser, native): Node
* *used with* (e.g. hapi application, another framework, standalone, ...): HapiJS Application
* *any other relevant information*: package.json script: `lab -vclS --coverage-exclude build --coverage-exclude src/migrations -T node_modules/lab-transform-typescript **/*.test.js`

#### What are you trying to achieve or the steps to reproduce?

I have the following directory structure:

```
+ my-project
|-- src
|    |-- controllers
|    |-- migrations
|    |-- models
|    |    |-- User.ts
|    |-- routes
|    |    |-- api
|    |    |    |-- v1
|    |    |    |    |-- register.ts
|    |    |    |    |-- login.ts
|    |    |-- index.ts
|    |-- server.ts
|-- test
|    |-- api
|    |    |-- v1
|    |    |    |-- register.test.js
|    |    |    |-- login.test.js
|    |-- index.test.js
|-- package.json
```

I wanted to write one unit test file per route file so that I could easily map my tests to my endpoints

#### What was the result you got?

Tests in `test/index.test.js` run, but tests in `test/api/v1/register.test.js` do not, nor do tests in `test/api/v1/login.test.js`

#### What result did you expect?

All tests run

**Comment by hueniverse** [comment]
I don't think `**` format is supported on the command line path. But you don't need to specify it. lab will ignore files under /test without lab tests in them.
