### ISSUE TITLE
Error: EEXIST: file already exists when output directory already exists

### ISSUE THREAD

**Issue by chrisshiplet** [hapijs/lab#980]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 8.15.1
* *module version with issue*: 22.0.4
* *last module version without issue*: Unknown
* *environment* (e.g. node, browser, native): Node
* *used with* (e.g. hapi application, another framework, standalone, ...): Hapi
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

I run a suite of tests on a CI service. First I run `jest` with `jest-junit` set to output its results to `reports/jest-results.xml`.

Next I have a set of tests in a folder called `integration-test`. They execute with the following command:

```
lab -v -l -r junit -o reports/lab-results.xml -r console -o stdout integration-test
```

However, at the end of the tests I get the following error, and the terminal just hangs and has to be manually ended with a SIGINT:

```
(node:689) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir 'reports'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.exports.generate (/src/api/node_modules/@hapi/lab/lib/reporters/index.js:74:16)
    at options.reporter.forEach (/src/api/node_modules/@hapi/lab/lib/reporters/multiple.js:33:50)
    at Array.forEach (<anonymous>)
    at new module.exports.internals.Reporter (/src/api/node_modules/@hapi/lab/lib/reporters/multiple.js:15:22)
    at Object.exports.generate (/src/api/node_modules/@hapi/lab/lib/reporters/index.js:69:22)
    at Object.exports.report (/src/api/node_modules/@hapi/lab/lib/runner.js:66:32)
    at Object.exports.run (/src/api/node_modules/@hapi/lab/lib/cli.js:62:19)
    at main (/src/api/node_modules/@hapi/lab/bin/lab:56:48)
    at Object.<anonymous> (/src/api/node_modules/@hapi/lab/bin/lab:60:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
(node:689) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:689) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

  
  .

1 tests complete
Test duration: 3184 ms
The following leaks were detected:__core-js_shared__, __extends, __assign, __rest, __decorate, __param, __metadata, __awaiter, __generator, __exportStar, __values, __read, __spread, __spreadArrays, __await, __asyncGenerator, __asyncDelegator, __asyncValues, __makeTemplateObject, __importStar, __importDefault, __SENTRY__, fetch, Response, Headers, Request


  
  ...

3 tests complete
Test duration: 3675 ms
The following leaks were detected:__core-js_shared__, __extends, __assign, __rest, __decorate, __param, __metadata, __awaiter, __generator, __exportStar, __values, __read, __spread, __spreadArrays, __await, __asyncGenerator, __asyncDelegator, __asyncValues, __makeTemplateObject, __importStar, __importDefault, __SENTRY__, fetch, Response, Headers, Request
```

I have verified this doesn't have anything to do with Jest or the particular structure of the reports folder - changing the junit output to _any_ directory that already exists on the filesystem causes this issue. I also tested deleting the `lab-results.xml` in between test runs to make sure overwriting the file itself wasn't the issue.

#### What was the result you got?

Tests fail and hang

#### What result did you expect?

Lab should write to an existing filesystem directory if it already exists, instead of trying to create it

**Comment by Marsup** [comment]
That should be easy enough to fix by checking the directory doesn't exist before that `mkdirSync`.

**Comment by cjihrig** [comment]
The code uses `fs.mkdirSync()`'s `recursive` option. It should handle the case of the directory already existing. I think the problem is that you're using Node 8, which is end-of-life and does not support the `recursive` option. Please update your Node version.
