### ISSUE TITLE
When running debug on my unit tests in VScode and hitting a break point this is being added to every line 'global.__$$labCov._line('{full-file-path},{line-number})' ?

### ISSUE THREAD

**Issue by nikiwycherley** [hapijs/lab#983]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*:  12.13.1
* *module version*: @hapi/lab": "^22.0.4
* *environment* (e.g. node, browser, native): VScode 
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi/lab
* *any other relevant information*: only appears when debugging and i hit a break point

#### How can we help?

```js
return h.view('station', { model })

changes to 

global.__$$labCov._line('/home/niki/projects/flood-app/server/routes/station.js',73);return h.view('station', { model })
```

**Comment by Marsup** [comment]
You probably should disable code coverage when debugging your tests.

**Comment by nikiwycherley** [comment]
not sure how to do that, would it be adding something to the launch.Json to say exclude it?

**Comment by Marsup** [comment]
Are you using a labrc file for configuration?

**Comment by nikiwycherley** [comment]
no i dont think so

**Comment by nikiwycherley** [comment]
No wait, yes i am
```
module.exports = {
    coverage: true,
    threshold: 60,
  
    // lcov reporter required for travisci/codeclimate
    reporter: ['console', 'html', 'lcov'],
    output: ['stdout', 'coverage/coverage.html', 'coverage/lcov.info']
  }
  ```

**Comment by nikiwycherley** [comment]
Have got it working by changing the "debug unit tests" to go to the individual file instead of the node modules.
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/index.js"
    },
    {"type": "node",
      "request": "launch",
      "name": "Launch File",
      "program": "${workspaceFolder}/{path-to-test-file.js}",
      "envFile": "${workspaceFolder}/.env"
    }
  ]
}
```

**Comment by cjihrig** [comment]
Thank you for updating the issue. Glad you seem to have gotten things working.

**Comment by ten-kis** [comment]
I made this with my labrc file to make disable code coverage
![image](https://user-images.githubusercontent.com/67905843/148017032-87155d29-2b7c-431c-a0e0-c92ee05c41a6.png)

Unfortunately if you set `coverage: true` in labrc file you can't disable it from cli, If it would be possible I would just modify my launch.json which is now looks like this
```
  "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Lab Current File",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["test", "--", "-m", "60000", "-P", "${fileBasenameNoExtension}"],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "disableOptimisticBPs": true
        }
    ]
```
