### ISSUE TITLE
Unknown authentication strategy

### ISSUE THREAD

**Issue by Akash0333** [hapijs/lab#985]
If I have a route with auth: 'userAuth', when I m run test case it's giving me. Error Unknown authentication strategy.

Any solution, please

**Comment by cjihrig** [comment]
Sounds like you might be missing a `server.auth.strategy()` call somewhere in your server setup.

**Comment by Akash0333** [comment]
'use strict';

const Hapi = require('hapi');
const mysql = require('../lib/mysql');
mysql.mysqlConnection();
const routes = require('../routes');
const plugins = require('../plugins');
const basicAuth = require('../lib/basicAuth');
const server = Hapi.server({
    port: 3010,
    host: 'localhost'
});

exports.init = async () => {
   
    await server.initialize();
    server.route(routes);
    await server.register(plugins);
    server.auth.strategy()
    return server;
};

exports.start = async () => {

    await server.start();
    console.log(`Server running at: ${server.info.uri}`);
    return server;
};

process.on('unhandledRejection', (err) => {

    console.log(err);
    process.exit(1);
});

**Comment by Akash0333** [comment]
Already call

**Comment by cjihrig** [comment]
> `server.auth.strategy()`

Please see the docs for the correct usage of that method - https://github.com/hapijs/hapi/blob/master/API.md#-serverauthstrategyname-scheme-options.
