### ISSUE TITLE
Policy on updating typescript?

### ISSUE THREAD

**Issue by kanongil** [hapijs/lab#989]
What is the policy for typescript updates? The integrated version (v3.6) is trailing behind, leaving out support for newer features like the `asserts` return type.

Since any of the frequent minor updates can break the tested types, would it make sense to change the dependency to a `peerDependency`? If combined with the [optional flag](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md), it can also help reduce the install size for non-typescript usage. Of course, this runs the risk of [a breaking change](https://github.com/microsoft/TypeScript/wiki/API-Breaking-Changes) to the [unstable API interface](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API) that lab uses.

The latter issue could possibly be remedied by doing a pre-validation of the expected interface used in [`types.js`](https://github.com/hapijs/lab/blob/master/lib/types.js), and throwing an error if it doesn't match. It could also be remedied, by creating a travis cron job, which tests against the current `latest`, `rc`, and `next` tags, and taking action if it fails.

**Comment by cjihrig** [comment]
@kanongil since you added support for updating TS in https://github.com/hapijs/lab/pull/992, does this need to remain open?

**Comment by kanongil** [comment]
Yes, this is fixed with #992 that delegates the responsibility away.
